### ISSUE TITLE
creating a new package which includes fortran sources

### ISSUE THREAD

**Issue by JoyMonteiro** [iodide-project/pyodide#1024]
Hello,

I just came across pyodide, and it seems like a very exciting project which has already solved a variety of
problems that I was looking at.

I would like to make some progress towards running [climt](climt.readthedocs.io/) on the browser. Even if
we ignore certain parts such as the 3D dynamical core (which might require a webassembly version of
FFTW and OpenBLAS), there is a lot of climate modelling that can be done if we stick to the other
components available.

However, even these components have some fortran code underlying them. There is also an entire bunch of
[community accepted](https://dtcenter.ucar.edu/GMTB/v4.1.0/sci_doc/index.html) climate modelling components which we intend to wrap this year which could potentially be available via the browser.

My query is to understand how to one can compile packages which link to fortran sources while compiling Cython wrappers. climt does this automatically, but I understand it is not as straightforward when compiling to webassembly.

Any documents/advice/tools to enable us to compile climt (some if not all parts) to work well with pyodide would be greatly
appreciated.

Happy New Year!
Joy

**Comment by rth** [comment]
Currently we can run f2c for Fortran 77. This part [is done automatically](https://github.com/iodide-project/pyodide/blob/07e9352c6aaa7d4cc545f004751fcbe402de776c/pyodide_build/pywasmcross.py#L225). For Fortran 90 and later there is currently no known solution. Though there is hope one might be found in the future, see #184.

**Comment by JoyMonteiro** [comment]
Thanks, @rth. I see that LLVM 11.0 has already been released a few months ago.

I had read the blog post in https://github.com/iodide-project/pyodide/issues/184 by StarGate. 

Has this (fairly complicated) procedure has become easier since this new release of LLVM?

Otherwise, we could start with pure Python modules and then add the other components as
we go forward.

**Comment by rth** [comment]
> Has this (fairly complicated) procedure has become easier since this new release of LLVM?

It should become easier, I think, once #476 is resolved, which is on a good track right now.

**Comment by JoyMonteiro** [comment]
great! I'll keep a watch on that, and reopen this issue when more relevant.
