### ISSUE TITLE
Problems with conftest.py

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1031]
While working on #998 I ran into some significant bugs in `conftest.py` which caused a lot of spurious test failures. These bugs have been making development in `core` hard too on occasion but the effects on `pyodide.js` are much worse.
The main problem is the predicate in `PyodideInited`:
```python
        inited = driver.execute_script(
            "return window.pyodide && window.pyodide.runPython && window.pyodide.pyodide_py"
        )
```
This predicate triggers both false negatives and false positives, and both types cause useless test failures.

I tried in #995 to improve this predicate by attaching it to `languagePluginLoader` but I'm not sure whether it worked. It seems to me that those changes are an improvement but the system is still extremely brittle. Perhaps the problem is that I don't understand the execution model of `<script>` tags in html well enough.

Another problem that seriously harms the utility of the test output is that every test failure produces **enormous** amounts of the same stuff. If somehow we could reduce the amount of junk that gets output, it would make diagnosing failed tests much easier and more pleasant.

I think this is a high priority to fix. I think it's a blocking issue for doing anything like #792 or #998 and a modest but manageable impediment to the work I've been doing on core.

**Comment by hoodmane** [comment]
@dalcde Could you take a stab at this?

**Comment by dalcde** [comment]
Not directly addressing the concern, but I think we can simplify a lot of the current code by defining a `selenium.run_js_async` function that awaits on a promise and returns/throws appropriately. We seem to do this by hand in a lot of different places.

**Comment by dalcde** [comment]
driver.execute_async_script does the job neatly. I'm submitting a PR soon

**Comment by hoodmane** [comment]
I think this resolved by @dalcde's work on conftest.py.
