### ISSUE TITLE
Makefile: stale versions of pyodide_py

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1069]
The make recipe for `root/.built` depends on `src/pyodide-py/`, I think based on the idea that it will be rebuilt if any file in `pyodide-py` is new, then `pyodide-py` will also show that it has been modified. I thought maybe there was something wrong with my computer but I tested on two other machines I have ssh access to:
```sh
>>> mkdir test
>>> touch test/test
>>> stat test/test | grep Modify | sed "s/.*:\(.*\):.*/\1/"
26 # test/test minute modified
>>> stat test | grep Modify | sed "s/.*:\(.*\):.*/\1/" 
26 # test minute modified

>>> touch test/test
>>> stat test/test | grep Modify | sed "s/.*:\(.*\):.*/\1/"
27 # test/test minute modified changed
>>> stat test | grep Modify
26 # test minute modified is unchanged
```
This is quite a nuisance since I keep compiling with stale versions of pyodide-py.

**Comment by dalcde** [comment]
I think in general we should try to avoid using /.* files in the
Makefile

**Comment by hoodmane** [comment]
What does that mean? Are you saying that the best practice is to manually `touch src/pyodide-py` whenever I update `pyodide-py`? I thought the makefile and OS were supposed to cooperate to work out which files were stale.

**Comment by dalcde** [comment]
Nah I'm saying generating root/.built is not a good way to let Makefile
work out which files are stale, which is not exactly relevant to this
issue.

**Comment by hoodmane** [comment]
Okay, I don't know what that means. Thanks for the fix!
