### ISSUE TITLE
Use FORCE_ALIGNED_MEMORY

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#11]
Python and Numpy are both reportedly alignment clean, or at least were at one time when they worked on Sparc.  Setting this option should give us a speedup.

https://github.com/kripken/emscripten/blob/master/src/settings.js#L103

**Comment by rth** [comment]
FORCE_ALIGNED_MEMORY is no longer supported in emscripten 1.38.29+ ( https://github.com/emscripten-core/emscripten/pull/8260 )
