### ISSUE TITLE
It's hard to checkout tags that start with a number

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1112]
The most recent tag is "0.16.1". I think tags are supposed to have a "v" in front of them, i.e., `v0.16.1`. In this case I can do `git checkout v0.1.7`, but `git checkout 0.16.1` doesn't work:
```sh
error: pathspec '0.16.1' did not match any file(s) known to git.
```

**Comment by dalcde** [comment]
It works for me. Did you git fetch -t?

**Comment by hoodmane** [comment]
```sh
>>> git fetch -t
>>> git checkout 0.16.1
error: pathspec '0.16.1' did not match any file(s) known to git.
```

**Comment by rth** [comment]
You need to fetch from upstream, not origin though. Is it in the list of `git tag`? I think it's an issue with the tag not being downloaded, not about version format. 

>  I think tags are supposed to have a "v" in front of them

Probably but it depends on the project https://github.com/scikit-learn/scikit-learn/tags. I'm not sure it's worth re-changing the versioning scheme for this.

**Comment by hoodmane** [comment]
>You need to fetch from upstream, not origin though. Is it in the list of git tag? I think it's an issue with the tag not being downloaded, not about version format.

Yes, thanks, I just don't know how to use git. I guess the reason I couldn't get `0.16.1` but could get `v0.1.7` was not some sort of identifier restriction but because `v0.1.7` existed when I cloned the repo, and if I were a better scientist I could have tested out this alternate hypothesis by trying to checkout `0.15.0`. Thanks!
