### ISSUE TITLE
[BUG] Exporting notebooks from extremely-alpha

### ISSUE THREAD

**Issue by teonbrooks** [iodide-project/pyodide#113]
When a notebook is exported from <https://extremely-alpha.iodide.io>, it does not run locally. upon further inspection, it looks as though the `iodide.dev.css` and the `idodide.dev.js` files are given relative paths instead of absolute paths at export.

**Comment by mdboom** [comment]
Maybe this bug should go in `https://github.com/iodide-project/iodide`?

**Comment by teonbrooks** [comment]
oops. sorry @mdboom, I was browsing your project and dropped this bug in the wrong place
