### ISSUE TITLE
Execute Python code inside <script type='text/python'></script> tags

### ISSUE THREAD

**Issue by albertas** [iodide-project/pyodide#1164]
Brython allows to declare script tags with type 'text/python'. Would it be possible to do the same in Pyodide?
This code:
```
<script type="text/python"> 
print("Hello world!")  
</script>
```
Should be equivalent to this:
```
<script type="text/javascript">      
pyodide.runPythonAsync(`               
    print("Hello world!") 
`);
</script>
```

**Comment by rth** [comment]
Yes, it would be nice. It's was earlier proposed in https://github.com/iodide-project/pyodide/issues/764 and there is an initial implementation in https://github.com/iodide-project/pyodide/pull/692

Don't hesitate to comment there or continue that PR. Closing as a duplicate.
