### ISSUE TITLE
CPython tests randomly time out

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#119]
Occasionally, a CPython test will take longer than 10 minutes, and Circle-CI will thus cancel the test run for not having any output for more than 10 minutes.  None of the tests *should* take that long as a matter of course.  This doesn't seem to happen on any tests in particular (though we should document which ones here to see if there is a pattern).

A short-term solution might be to use [pytest-timeout](https://pypi.org/project/pytest-timeout/) to at least get a stack trace if a test hangs.

**Comment by rth** [comment]
Maybe this will be less of an issue after https://github.com/iodide-project/pyodide/pull/118 (with reusing of selenum fixture) was fixed...

**Comment by mdboom** [comment]
Let's hope!

**Comment by rth** [comment]
Closing as this hasn't happened in the last two weeks (as far as I'm aware), so it looks like #118 did help resolve it. Please re-open if it happens again..
