### ISSUE TITLE
Run Python unit tests

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#12]
We should have a mode to include and run all of the Python unit tests to see where we stand on things working.

**Comment by mdboom** [comment]
As of ee7eaf5cc84ba3bf5693349fa9a3d56f0d110c71, we have the infrastructure for tests in place on Travis.  Next step is to run actual Python unit tests there.

**Comment by mdboom** [comment]
Mostly working, but there are number of failing tests that can probably still be improved.

**Comment by rth** [comment]
> Mostly working, but there are number of failing tests that can probably still be improved.

Closing in favor of more specific issues on this topic https://github.com/iodide-project/pyodide/issues/144 , https://github.com/iodide-project/pyodide/issues/196 etc.
