### ISSUE TITLE
Performance issues with buffer conversions from python to javascript

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1202]
Hello @hoodmane, thank you for the magnificent APIs (deep/shallowCopyToJavaScript) that would eliminate the heavy cost of big array conversion from python to Javascript.  I think the shallowCopy version is designed for memory address reference instead of bulks of content copy. But I find the perfomance not so good as I've imagined, which is displayed as the following:
![image](https://user-images.githubusercontent.com/34263430/107121264-74600900-68cc-11eb-8e92-da3b8b09b5f4.png)

It takes about 1~7 seconds for shallowCopyToJavascript() to complete the memory address reference and maybe some necessary meta data copy I guess. However, it's not  adequate for a realtime computation.  Any suggestions for better conversion performance?

_Originally posted by @daoxian in https://github.com/iodide-project/pyodide/issues/1167#issuecomment-774488338_

**Comment by hoodmane** [comment]
Hi @daoxian. Thanks for reporting this bad behavior. 

The handling of memory buffers is currently not good, this is an issue we hope to fix at some point. I think the current behavior is to make a javascript `Array` of 1080 javascript `Array`s of 3-byte `Uint8Array`. The innermost layer is sliced out of the buffer memory so saying `arr[700][500][0] = 255` will adjust the original data, but populating those large javascript `Array`s is very inefficient at all (remember that an `Array` is a hashmap). 

My guess is it would do much better if you transposed the array to have shape `(3, 1080, 1920)`, though of course this isn't very ergonomic if for instance you are intending to use this data to back an image.

Would you look at #1168? That issue is closely related to the poor performance here. If you have an opinion about that discussion it would be helpful. One thing that limits my ability to fix the Buffer handling code is that I don't really know what the use cases look like, so I really appreciate any input you have. Of course if you want to take a stab at improving the buffer conversion code, let me know and I can tell you what I think you'll need to know.

**Comment by daoxian** [comment]
Indeed, it's much faster after the image transposed to (3, 1080, 1920).

**Comment by daoxian** [comment]
see the actual case from #1168  and codes in #1203

**Comment by daoxian** [comment]
@hoodmane 
The `shallowCopyToJavascript` method seems only available in ES6 JS, not in nodejs.
In Node.js, either of the follows will trigger a runtime error:
>  img = img.shallowCopyToJavascript(depth=1);
>  img = img.shallowCopyToJavascript(1);

` JsException: ReferenceError: depth is not defined`


And after I have a look at the code, I can't found the definition of variable `depth`:
>     shallowCopyToJavascript : function(){
>       let idresult = _python2js_with_depth(_getPtr(this), depth);
>       let result = Module.hiwire.get_value(idresult);
>       Module.hiwire.decref(idresult);
>       return result;
>     },

Maybe a param `depth`  should be there like function(depth) ?

**Comment by daoxian** [comment]
However, it takes  around 30~40ms for shallowCopyToJavascript to convert a image of  size (287, 287, 3), a little too long for the realtime computation.  I hope the conversion could be accomplished in no more than 10ms.

**Comment by hoodmane** [comment]
> However, it takes around 30~40ms for shallowCopyToJavascript to convert a image of size (287, 287, 3)

Again, I'm hoping to fix this soon, there is no technical reason that it can't be much faster.
