### ISSUE TITLE
Make cdn "full" folder public?

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1210]
The following gives a 403:
https://cdn.jsdelivr.net/pyodide/dev/full/ 
I think it'd be useful if it gave the directory listing instead.

**Comment by rth** [comment]
JsDelivr doesn't allow serving HTML files for security reasons, and I'm not sure how else we could show a listing. If it's with json files, we already have `packages.json` and there are plans to make it more extensive #791

**Comment by hoodmane** [comment]
Okay, well this isn't worth much effort if it is tricky. In my head it was just a `chmod`.

**Comment by rth** [comment]
The infrastructure is that we have an S3 that JsDelivr routes though different CDN (Cloudflare, Flastly, ) with additional layers of cache in between. I guess if that URL returned something by the S3 that's not an HTML file, it would then be served downstream. But it would probably mean we have to manually compute the listing, and that's already what `packages.json` is doing more or less.
