### ISSUE TITLE
Language question: nomenclature for "type conversion"

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1232]
In #1231 based on discussion in #1192 we introduced the word "conversion" to describe the behavior of `toJs` of converting a native object from one language into a native copy in the other language. We use the term "proxy" to describe producing an object in one language that redirects requests into the other language. The `python2js` and `js2python` functions will most immutable objects and proxy most everything else. The current section of the documentation named "Type Conversions" is describing the behavior of `python2js` and `js2python`. If we also use the word "conversion" to describe the behavior of  `toJs`, then we're using the same word "conversion" to mean two different things.

Anyone have an idea of how to resolve this name clash?

**Comment by daoxian** [comment]
The word "replicate" means to reproduce something, to construct a copy of something, to make a facsimile".  The objects or instances in Python are likely but not mandatorily totally the same as the equivalents that in JS. We expect a similar behavior between them. So I think "replicate" or "replication/replica" may be a candidate.

**Comment by casatir** [comment]
Replicate sounds good. I also thought about "mirror".

**Comment by hoodmane** [comment]
"mirror" is similar to "proxy", "reflect". "replicate" suggests "duplicate" / "copy". The nice thing about "convert" is that you normally "convert" from one thing to another "I converted the image from a jpg to a png" or "I converted the object from python to javascript". 

How about type translations, since we are translating from one language to another?

**Comment by hoodmane** [comment]
So in particular, the idea is that `python2js` and `js2python` will do "type translation". Depending on the object, to translate we either "proxy" or "convert" it as appropriate. We choose to proxy things as much as possible when in doubt. If we "proxy" the object, it *may* be possible to explicitly cause it to be "converted" with the `toJs` and `toPy` APIs.

I think this sounds okay?

**Comment by casatir** [comment]
Crystal clear!

**Comment by hoodmane** [comment]
Okay I am going with "type translation" for now then. Thanks @daoxian @casatir for the feedback!
