### ISSUE TITLE
Use pyodide.org domain for documentation

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#1243]
As part of https://github.com/iodide-project/pyodide/issues/1217 we can probably switch the documentation to pyodide.org domain. There are several options there,
 1. use  `docs.pyodide.org` for the readthedocs documentation, and possibly make a separate home page for `pyodide.org` with GH pages. This is for instance what dask is doing with https://dask.org/ vs https://docs.dask.org 
    - the advantage is that it's easy to setup and we can still rely on ReadTheDocs
    - the disadvantage in terms of search indexing is that this would correspond to two separate domains
 2. have a single documentation domain `pyodide.org` with a home page and the documentation as a subfoder. This is what for instance, https://numpy.org/ is doing.
    - this would be preferable for search engines
    - however it likely means we won't be able to use ReadTheDocs and have to switch to a manual deployment of the docs via Github pages or Netlify. Which is more challenging particularly for managing versions.
    - we would also be able to do it, only once we have some rudimentary home page.

WDYT?

**Comment by phorward** [comment]
Hello @rth, thanks for your considerations on this. I mostly agree with the second option, although it might require more effort in configuration, or manual intervention. I think, that first creating the homepage and then doing decisions on where to host the docs should be done in exactly this order, as you stated it already.

**Comment by phorward** [comment]
@rth are you owner of that domain? Do you need assistance?

**Comment by rth** [comment]
yes, I was waiting for more feedback, but I think we can go forward with it.

So if we go with option 2 and stay with ReadTheDocs for now to keep it simple, it just means that the documentation will be at
 - `pyodide.org/en/latest/` for master
 - `pyodide.org/en/stable/` for the last stable release

there is 302 (temporary) redirect from `/` to `/en/latest/` (we should maybe switch it to stable). This also guarantees that current documentation links to readthedocs are going to be correctly redirected to this domain.

If in the future we decide to use another hosting (e.g. GitHub pages) we will just have to preserve this URL scheme. What do you think?

The alternative is to switch to GitHub pages now but it would require more work and the issue is that we won't be able to redirect from RTD to the new domain there, so some users might end up on outdated docs.

**Comment by rth** [comment]
OK I went ahead with these changes, with a PR to update links in the readme with in https://github.com/iodide-project/pyodide/pull/1301
