### ISSUE TITLE
The getRawBuffer() API in Chrome browser spends more time than that in Firefox

### ISSUE THREAD

**Issue by daoxian** [iodide-project/pyodide#1265]
> > Is the getRawBuffer() API in Chrome browser any different from that in Firefox? I found a performance lag in Chrome. In Firefox it takes 1ms to run the API, but 10~50 ms in Chome.
> 
> No clue why you're seeing this. Will try to reproduce.

Have you reproduced the issue in Chrome?  @hoodmane  
I find that it takes around 5~15ms for JS entering the `getRawBuffer` method. 

>   Module.PyProxyBufferMethods = {
>     getRawBuffer : function(type = "u8"){
>       console.log( "enter function\n");
>       let ArrayType = type_to_array_map.get(type);
>       console.log( "type_to_array_map.get done\n");
>       if(ArrayType === undefined){
>         throw new Error(`Unknown type ${type}`);
>       }
>       console.log( "before _getPtr\n");
>       let this_ptr = _getPtr(this);
>       console.log( "before memview_get_buffer\n");
>       let buffer_struct_ptr = __pyproxy_memoryview_get_buffer(this_ptr);
>       console.log( "after memview_get_buffer\n");
>       if(buffer_struct_ptr === 0){
>         throw new Error("Failed");
>       }
> 

the log is:
![image](https://user-images.githubusercontent.com/34263430/108373578-05bf6b80-723b-11eb-97fe-f59e6152aed3.png)

_Originally posted by @daoxian in https://github.com/iodide-project/pyodide/issues/1221#issuecomment-778743321_

**Comment by hoodmane** [comment]
I can't reproduce this. On my computer entering raw buffer takes consistently <1ms as you would expect:

```javascript
async function test(){
    await pyodide.runPythonAsync("import numpy as np");
    x = pyodide.runPython("np.arange(287*287*3).reshape([287,287,3])");
    console.log("1. enter test");
    let buf = x.getRawBuffer();
    console.log("2. got buffer");
    buf.release();
    console.log("3. released buffer");
}
test()
```


![image](https://user-images.githubusercontent.com/8739626/108404604-ea217a00-71d4-11eb-8e3d-6fa62e4f8999.png)

**Comment by daoxian** [comment]
After some experiments, the lag is not always the case, will close for now.
