### ISSUE TITLE
Console echo without newline

### ISSUE THREAD

**Issue by jcubic** [iodide-project/pyodide#1276]
Just the heads up, the jQuery Terminal added support for echo without newline, it would be hard modify the library so it's monkey patch extension

https://github.com/jcubic/jquery.terminal/blob/master/js/echo_newline.js

it was added to NPM some time ago. It's based on example that was little bit to long so it was added to the repo.

but it may be more bullet proof and if there is a bug it can be fixed in jQuery Terminal and if you use cdn with latest version the fix will be automatically deployed.

**Comment by jcubic** [comment]
To run the extension you just need to include the file and you will be able to use:
```javascript
term.echo('xxx', { newline: false });
```

**Comment by rth** [comment]
Thanks for the information @jcubic ! https://github.com/iodide-project/pyodide/pull/1274 aimed to improve this, but using echo without newlines would indeed be ideal. Don't hesitate to comment on that PR.

 cc @hoodmane

**Comment by hoodmane** [comment]
In #1274 I was trying to do exactly this =)
