### ISSUE TITLE
pyodide._module._PyMem_Malloc does not properly allocate memory

### ISSUE THREAD

**Issue by daoxian** [iodide-project/pyodide#1283]
For example:
first, we alloc a 10-bytes mem:

> ptr = pyodide._module._PyMem_Malloc(10);

then get an array from the mem:

> arr=pyodide._module.HEAP8.subarray(ptr, ptr + 10);  

we'll get a Int8Array of random item values.

Now let's check the underlying buffer, arr.buffer, we'll see a zero-filled ArrayBuffer.  Why the value of arr[x] does not equal to its underlying arr.buffer[x] ?

![image](https://user-images.githubusercontent.com/34263430/109097312-0cc60c80-775a-11eb-8e40-359f727943c8.png)

**Comment by hoodmane** [comment]
This is how subarray works:
```
x = new Uint8Array(20)
y = x.subarray(10, 15);
console.log(y.buffer === x.buffer); // true
z = new Uint8Array(y.buffer); // z will be just like x
x[0] = 1;
y[0] = 7;
console.log(x[0],  z[0]); // 1 1
console.log(x[10], z[10], y[0]); // 7 7 7
```

**Comment by daoxian** [comment]
> This is not a bug, it's just how subarray works:
> 
> ```
> x = new Uint8Array(20)
> y = x.subarray(10, 15);
> console.log(y.buffer === x.buffer); // true
> z = new Uint8Array(y.buffer); // z will be just like x
> x[0] = 1;
> y[0] = 7;
> console.log(x[0],  z[0]); // 1 1
> console.log(x[10], z[10], y[0]); // 7 7 7
> ```

I mean in pure JS, the value of arr.buffer[0] should equal to that of arr[0], and arr.buffer[1] should equal to that of arr[1], and so on.  But after allocate memory on pyodide heap, 
![image](https://user-images.githubusercontent.com/34263430/109242626-6a1f9380-7816-11eb-90ea-e4c49a69ab50.png)
the values of arr and its buffer are not equal.

**Comment by hoodmane** [comment]
Screenshot looks as expected. This is just how `subarray` works.

**Comment by daoxian** [comment]
Here's an example that differs:

Using pyodide heap malloc:
> ptr = pyodide._module._PyMem_Malloc(10);
> arr=pyodide._module.HEAP8.subarray(ptr, ptr + 10);
> arr2=new Int8Array(arr.buffer,0,10);
> arr[0]=123
> arr2[0]   // == 0, not 123

while using JS native:

> arr=new Int8Array(10);
> arr2=new Int8Array(arr.buffer,0,10);
> arr[0]=123
> arr2[0]   // == 123

**Comment by hoodmane** [comment]
Try:
```
arr=new Int8Array(20);
arr2=arr.subarray(10,20);
arr[0]=123
arr2[0] // == 0
```

**Comment by daoxian** [comment]
I see...   arr.buffer means the start address of memory block.

**Comment by hoodmane** [comment]
Yeah this is frustrating if you were expecting to change the type of the typed array by doing `let arr2 = new Uint32Array(arr1.buffer);`. There should be a more convenient API for that type of conversion, but I think the only way is pretty cumbersome.
