### ISSUE TITLE
Compare with plotly dash

### ISSUE THREAD

**Issue by j209** [iodide-project/pyodide#1314]
How we can compare pyodide with [plotly-dash](https://github.com/plotly/dash)

**Comment by rth** [comment]
plotly-dash is a web app with a backend. So you can ran any Python library you want on the backend.

pyodide doesn't require a backend, Python packages are run on the frontend, but it also means that the list of packages that you can use is more restricted. Currently we support pure Python wheels from PyPi and packages built as part of pyodide. Some of the stdlib modules (multiprocessing, sockets, threading) are also not supported.

I'm going to close this issue as answered but don't hesitate to comment.
