### ISSUE TITLE
Generate snapshot builds from dev/master

### ISSUE THREAD

**Issue by dmondev** [iodide-project/pyodide#1316]
Would it be possible to generate snapshot builds from the development branch, so users behind very restrictive firewalls can test/use the current development version ?

Thank you !!!

**Comment by hoodmane** [comment]
Have you tried the jsdelivr url?
https://cdn.jsdelivr.net/pyodide/dev/full/pyodide.js

**Comment by rth** [comment]
You mean that cdn.jsdelivr.net is blocked for you? It should be widespread on websites. Unless they are blocking by file type?

You could try getting CircleCI artifacts directly for master https://github.com/iodide-project/pyodide/issues/648.

**Comment by dmondev** [comment]
@hoodmane/ @rth, Thanks, but I cannot use an external cdn.

I'm also packaging some additional libraries as part of my own build. So I currently start from the prebuild Docker image, and add generate/build additional packages from there.

I see the artifacts in CircleCI:

https://app.circleci.com/pipelines/github/iodide-project/pyodide/2174/workflows/4c3ee3d1-3e38-496b-b10a-6a2cf75628eb/jobs/23156/artifacts

This is great ! 

Yes, I can get the artifacts individually, but it would be great if there was a single file to download (tar.bz2 ?)

Thanks !!

**Comment by rth** [comment]
> Yes, I can get the artifacts individually, but it would be great if there was a single file to download (tar.bz2 ?)

If you can download it there, that's probably the way to go. You can get the packages.json, get all the package names from there. Or you can build it locally.

Sorry, we are not going to add more maintenance work for us for a fairly unique use case :) So I'm closing this but don't hesitate to open other issues.

**Comment by dmondev** [comment]
@rth, 

If you think it would make sense to do this, I could send a PR.

I see it could be an additional command in **.circleci/config.yml (deploy-s3)**

**Comment by rth** [comment]
Right but that one is officially deployed via cdn.jsdelivr.net which you say is blocked. I would rather not advertise the direct S3 URLs, as they are not cached and can translate into some costs for us particularly if bots start hitting them.

So unless there is more demand for this, I would rather not provide a .tar.bz2 of packages for each commit on master, in addition to individual packages we already provide.

We are hoping to make a release soon which would also address your concern I imagine.

**Comment by dmondev** [comment]
Oh, I would just save the single file as an artifact in CircleCI, that would be enough, no need to go to s3, if that's ok.

Yes, for this release I'm mainly interested in the javascript Promise compatibility, and being able to build additional packages with the development pre-built image.

Thinking about it, this exercise would require a the Docker image to be published as well, since I won't be able to build from scratch. 

That's ok, I appreciate your responses anyway.

Thanks !!

**Comment by rth** [comment]
OK, feel free to send a PR to also store package archive in CircleCI artifacts (on master only). We can't guarantee that it will remain available in the long term though, particularly after the next release is available.
