### ISSUE TITLE
Potential memory leak in hiwire.c

### ISSUE THREAD

**Issue by johnwason** [iodide-project/pyodide#1326]
I am profiling memory for my application, which sends an updated nested dictionary to JS every 100 ms. I call deepCopyToJavascript and destroy the proxy before handing it off. I am seeing continual memory growth, and during profiling, one of the culprits appears to be converting numpy uint8 arrays to JS arrays. The report has the array allocation here:

https://github.com/iodide-project/pyodide/blob/ab249a0a50e401783dda7a270b5de8d26d0c3f33/src/core/hiwire.c#L185

Looking through the hiwire code, I can't figure out what new_value is supposed to accomplish. From what I can tell, it places it in a JS dict and never deletes it. I hand off the converted dictionary to Vuex and never touch it again. It should be destroyed when the data is replaced 100 ms later, but it is still being retained.

**Comment by hoodmane** [comment]
Hi @johnwason thanks for your interest. As you say, we currently leak memory like crazy. I am definitely interested in improving the situation, and am interested in any input you have.

So the story is that WebAssembly cannot directly touch references to Javascript objects. The Javascript objects do not live in linear memory and all Wasm values are actually numbers. The pointers are all just numbers which are references into the `Uint8Array` backing the Wasm memory. We need some way to handle Javascript objects, so what we do is store them in a table and pass around indexes into the table (JsRefs).

Each call to `let ref = hiwire.new_value(jsobj)` is supposed to be matched with a call to `hiwire.decref(ref)`, (or from C, `hiwire_decref(ref)`, or wrappers like `hiwire.pop_value` or `hiwire_CLEAR`). If no matching call happens, then we leak the Javascript object.

See also:
https://fitzgeraldnick.com/2020/08/27/reference-types-in-wasmtime.html

>Without the reference types proposal, WebAssembly can only manipulate simple integer and floating point values. It can’t take or return references to the host’s objects like, for example, a DOM node on a Web page or an open connection on a server. There are workarounds: for example, you can store the host objects in a side table and refere to them by index, but this adds an extra indirection and implementing the side table requires cooperating glue code on the host side. That glue code, in particular, is annoying because it is outside of the Wasm sandbox, diluting Wasm’s safety guarantees, and it is host-specific. If you want to use your Wasm module on the Web, in a Rust host, and in a Python host, you’ll need three separate glue code implementations. This makes WebAssembly less attractive as a universal binary format.

**Comment by johnwason** [comment]
I think that it would make sense for deepCopyToJavascript to copy the data and abandon all references to the webassembly data. "Deep copy" would imply this behavior. I have my own modified version of Pyodide for my project, so if you can show me where I need to decref I can add it. I assume it is around here:

https://github.com/iodide-project/pyodide/blob/ab249a0a50e401783dda7a270b5de8d26d0c3f33/src/core/python2js.c#L431

**Comment by hoodmane** [comment]
> it would make sense for deepCopyToJavascript to copy the data and abandon all references to the webassembly data

Yeah it's trying to do that.

It looks to me like the reference returned from line 431 there gets correctly deallocated here:
https://github.com/iodide-project/pyodide/blob/de7c3420103fabbf01c589fcf2a429d157a6bd5e/src/core/pyproxy.c#L785

**Comment by johnwason** [comment]
Is that called for data that is stored inside a dict? That appears to be for the top level object.

**Comment by hoodmane** [comment]
What's the shape of the Python buffer you are using, is it 1d or more?

By the way, what do you think of the `toJs` behavior for buffers? Do you like the way the API works? Would the API in #1215 work better for you?

**Comment by hoodmane** [comment]
> Is that called for data that is stored inside a dict? That appears to be for the top level object.

Are you talking about the dict called `cache`? That should be removed here:
https://github.com/iodide-project/pyodide/blob/ab249a0a50e401783dda7a270b5de8d26d0c3f33/src/core/python2js.c#L549

**Comment by johnwason** [comment]
I am using an older commit of Pyodide (a4fad9b) because of bugs in emscirpten 2.x (https://github.com/emscripten-core/emscripten/issues/13607), so it is still deepCopyToJavascript() I will have to read the draft carefully to understand the differences. One annoyance is I can't convert to JS from Python and pass that way. I only use JS for the display layer, so I don't interact with the object on the JS side, it is passed directly to Vue or the DOM. I have a small wrapper function that does the conversion to work around this problem.

**Comment by johnwason** [comment]
The version of `python2js_with_depth` in my version looks like this:

```
JsRef
python2js_with_depth(PyObject* x, int depth)
{
  PyObject* map = PyDict_New();
  JsRef result = _python2js_cache(x, map, depth);
  Py_DECREF(map);
  return result;
}
```
so the problem I am seeing may have already been fixed in a later commit I don't have. I haven't found where it is changed yet.

**Comment by hoodmane** [comment]
I think it's unlikely that it's been fixed, but it's possible.

**Comment by hoodmane** [comment]
Oh never mind, you're absolutely right that the added lines here:
https://github.com/iodide-project/pyodide/blob/de7c3420103fabbf01c589fcf2a429d157a6bd5e/src/core/python2js.c#L547
fix the problem.

**Comment by hoodmane** [comment]
Incidentally, have you tried checking out all of `src/core`, `packages/micropip`, and `src/pyodide.js` from the up-to-date master? I suppose there might be issues with the patches etc that have changed but I don't know if any changes to `core` have needed the new emscripten.

**Comment by johnwason** [comment]
Unfortunately all the updates past the commit I have to other files require emscripten 2.x.

I will work around this problem by converting everything to primitives. The arrays are small and I don't absolutely need the array type. If I have a chance I will run a test case the more current version of pyodide to see if  the leak still occurs.

The issue can be closed if you think the problem is on my end.

**Comment by hoodmane** [comment]
Actually I can confirm there's still a leak here in the master version, so better to leave it open.
