### ISSUE TITLE
creating python cells in the web GUI

### ISSUE THREAD

**Issue by mash-graz** [iodide-project/pyodide#133]
there is no way to add new python cells or change the type of an existing cell to python in the actual iodide web GUI interface. this makes it very hard for interested users to create now pyodide notebooks in their browsers.

**Comment by rth** [comment]
Thanks for the report. I can reproduce it (unless I missed something in the UI).  Possibly related to https://github.com/iodide-project/iodide/issues/539. Could you please re-open this issue at https://github.com/iodide-project/iodide (and close it here) -- that would be a better place for it. Also please provide a link to the notebook you were using there.

**Comment by mash-graz** [comment]
> Could you please re-open this issue at https://github.com/iodide-project/iodide (and close it here)...

o.k -- i'll do it.

> Also please provide a link to the notebook you were using there.

it's also happening when you open the [offical introductory demo notebook of pyodide](https://iodide.io/pyodide-demo/python.html) -- that's why i posted my bug report here in this section.

![](http://users.mur.at/ms/attachments/pyodide1.png)

and:
![](http://users.mur.at/ms/attachments/pyodide2.png)

perhaps it would be better to write "open your preferred text editor and insert a cell" as long as this issue isn't fixed.  ;)
