### ISSUE TITLE
Loading multiple packages 

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#135]
Currently execution of `pyodide.loadPackage` (from JS) appears to happen asynchronously, which leads to errors when two packages are loaded that share dependencies,
```js
pyodide.loadPackage('numpy')
pyodode.loadPackage('matplotlib')
```
in the iododide notebook leads to,
```js
{node: undefined, setErrno: ƒ, errno: 17, code: "EEXIST", message: "File exists", …}
```

<details>

```js
ErrnoError {node: undefined, setErrno: ƒ, errno: 17, code: "EEXIST", message: "File exists", …} code: "EEXIST"errno: 17message: "File exists"node: undefinedsetErrno: ƒ (errno)stack: "Error↵    at new ErrnoError (http://127.0.0.1:8000/pyodide.asm.js:4:107855)↵    at Object.mknod (http://127.0.0.1:8000/pyodide.asm.js:4:91421)↵    at Object.create (http://127.0.0.1:8000/pyodide.asm.js:4:91659)↵    at Object.createDataFile (http://127.0.0.1:8000/pyodide.asm.js:4:111134)↵    at finish (http://127.0.0.1:8000/pyodide.asm.js:4:117628)↵    at processData (http://127.0.0.1:8000/pyodide.asm.js:4:117988)↵    at Object.createPreloadedFile [as FS_createPreloadedFile] (http://127.0.0.1:8000/pyodide.asm.js:4:118135)↵    at DataRequest.finish (http://127.0.0.1:8000/numpy.js:1:9279)↵    at DataRequest.onload (http://127.0.0.1:8000/numpy.js:1:9187)↵    at processPackageData (http://127.0.0.1:8000/numpy.js:1:10398)"__proto__: Error
    at Object.ensureErrnoError (http://127.0.0.1:8000/pyodide.asm.js:4:107913)
    at Object.staticInit (http://127.0.0.1:8000/pyodide.asm.js:4:108153)
    at Object.pyodide (http://127.0.0.1:8000/pyodide.asm.js:4:680298)
    at HTMLScriptElement.script.onload (eval at f.addEventListener (https://iodide.io/dist/iodide.pyodide-20180623.js:12:195416), <anonymous>:152:24)
mknod @ pyodide.asm.js:4
create @ pyodide.asm.js:4
createDataFile @ pyodide.asm.js:4
finish @ pyodide.asm.js:4
processData @ pyodide.asm.js:4
createPreloadedFile @ pyodide.asm.js:4
finish @ numpy.js:1
onload @ numpy.js:1
processPackageData @ numpy.js:1
(anonymous) @ numpy.js:1
xhr.onload @ numpy.js:1
load (async)
fetchRemotePackage @ numpy.js:1
loadPackage @ numpy.js:1
(anonymous) @ numpy.js:1
(anonymous) @ numpy.js:1
```
</details>

While loading these two packages one after the other works fine. Preventing simultaneous execution of `pyodide.loadPackage` might be way around it.

Also loading multiple packages in one call, e.g,
```js
pyodode.loadPackage(['numpy', 'matplotlib'])
```
is currently not supported. Not sure if that's something we want API wise but it wouldn't be too difficult to add, as all the code internally already stores the packages to load in an array.

**Comment by mdboom** [comment]
I think loading multiple packages worked at one time.  I'm totally in favor of restoring that.

**Comment by rth** [comment]
For the issue of multiple calls to `pyodide.loadPackage`, here is a test that fails (originally from https://github.com/iodide-project/pyodide/pull/136),
```py
from .conftest import TimeoutException

def test_load_packages_simultaneous(selenium_standalone):
    selenium = selenium_standalone
     from selenium.common.exceptions import TimeoutException
     selenium.run_js(
        'window.done = false\n'
        'pyodide.loadPackage("numpy")\n'
        'pyodide.loadPackage("matplotlib")'
        '.then(function() { window.done = true; })')
    try:
        selenium.wait.until(PackageLoaded())
    except TimeoutException as exc:
        print(selenium.logs)
        raise TimeoutException()
    assert selenium.logs.count('Loading numpy') == 1
```
Also quoting @mdboom's comment https://github.com/iodide-project/pyodide/pull/136#discussion_r214914175,

> This sort of thing could get flaky on Chrome. On Chrome, we are forced to load the wasm asynchronously, but unfortunately that uses global variables to set up, so you can't actually load wasm modules simultaneously. All that happens in emscripten itself, but I don't think it actually does any locking around simultaneous loading.
>
> We may want to add our own locking around this case. i.e., if there's already an active promise, attach the new promise to run after that promise.

The above test fails on Firefox I think as well, BTW.

I have tried two approaches,
 - waiting for the promise to complete before executing any code in `loadPackage` in https://github.com/rth/pyodide/commit/60cae30aa3acaa57c0cfccd7acf37b7aa2d39b88
 - making `toLoad` variable global (same as `loadedPackages` is), as I believe the issue may arise when the packages was added to `toLoad` in one call, but is not yet in `loadedPackages`, so it might be staged for loading again in a following `loadPackage` call  https://github.com/rth/pyodide/commit/41e91f815bb30e477bef623355222886bdca41b9 

Though I haven't managed to make neither of them work so far...
