### ISSUE TITLE
Optimize startup time...

### ISSUE THREAD

**Issue by jedie** [iodide-project/pyodide#137]
I think the biggest problem with pyodide is the same as with PyPy.js: The long startup time because of big downloads...

If i compare:

https://pypyjs.org/ - Loads **4,2MB** Biggest files:

-  **pypyjs.vm.js (2MB)**
-  **pypyjs.vm.js.zmem (2MB)**

https://iodide.io/pyodide-demo/python.html Loads **14,2MB** Biggest files:

-  **pyodide.asm.data (11MB)**
-  **pyodide.asm.wasm (2,5MB)**

I think here is some optimizing potential, isn't it?

pypyjs.vm.js.zmem used zlib for compression, see: https://github.com/pypyjs/pypyjs/blob/9038af4f9f80e96df15114b8328e7a517979ab61/tools/compress_memory_initializer.py#L70

Discussion about PyPy.js compression is here: https://github.com/pypyjs/pypyjs.github.io/issues/4

**Comment by rth** [comment]
This is very promising, particularly given that `.data/.wasm` have a more than 3x compression ratio e.g. with gzip,
```sh
% du -sh pyodide.asm.*
12M     pyodide.asm.data
3.1M    pyodide.asm.data.gz
56K     pyodide.asm.data.js
12K     pyodide.asm.data.js.gz
2.9M    pyodide.asm.js
368K    pyodide.asm.js.gz
8.3M    pyodide.asm.wasm
2.5M    pyodide.asm.wasm.gz
```

**Comment by rth** [comment]
For the record, using,
```
uglifyjs --compress --mangle
```
can be used to reduce the size of e.g. `pyodide.asm.js` a bit (to 2.6 MB from 3.0MB), but https://github.com/iodide-project/pyodide/pull/152 will probably be a more general solution in any case.

**Comment by rth** [comment]
Also `.wasm` files are served gzip compressed by default from Github Pages (where the demo notebook) see https://github.com/WebAssembly/spec/issues/573#issuecomment-340872550 and I also double checked this.

Though this does not automatically extend to all the other files with the `.data` extension generated by emscripten unfortunately.

**Comment by devxpy** [comment]
I was actually discussing the same thing over at https://github.com/pypyjs/pypyjs/issues/212.

My proposal is that if we could find a way to cache the binaries on the target browser, in  a way that any website built using  pyiodide 
or pypyjs can use the same binary, that should be quite acceptable.

Since this is a Mozilla project, we can alsp try to get native browser support for caching at least popular interpreters on the client. This would obviously also benefit other interpreted languages as well.

**Comment by rth** [comment]
> but #152 will probably be a more general solution in any case.

Closing as files served via the CDN now uses Brotly compression. Other optimization approaches are found in https://github.com/iodide-project/pyodide/issues/646

> might I bring up the possibility of having native browser support for caching at least popular interpreters on the client? :-)

It's ~7.4 MB to download for core pyodide that are then cached by the browser, which should be fine?
