### ISSUE TITLE
Build issues after #1369

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#1375]
Yet again I can't figure out how to build after a change to the build system. I ran `make clean` in `emsdk`, `cpython`, and in the root directory and restarted the docker environment. After this, `make` leads to the error:

```sh
./tools/dependency-check.sh
emcc    -c -o src/core/docstring.o src/core/docstring.c
/bin/bash: emcc: command not found
```

Can anyone help me out?

**Comment by hoodmane** [comment]
Okay, cd'd into `emcc` and ran `make` and then cd'd into `cpython` and ran make. Now I get:

```
make[1]: Entering directory '/src'
./tools/dependency-check.sh
src/core/docstring.c:2:10: fatal error: 'Python.h' file not found
#include "Python.h"
```

**Comment by rth** [comment]
It's really strange: that PR should be only minor refactoring for Makefiles without any changes in the way they work. Have you managed to find a solution?

**Comment by hoodmane** [comment]
I messed around more and the problem went away. I'm not sure what caused it or what fixed it.
