### ISSUE TITLE
Can it support turtle?

### ISSUE THREAD

**Issue by wusfen** [iodide-project/pyodide#1381]

**Comment by rth** [comment]
The native tutle module from stdlib is based on [tkinter](https://docs.python.org/3/library/tkinter.html) which we don't support. 

However there is a turtle re-implementation for Brython and adapted for pyodide by @casatir [here](https://framagit.org/casatir/basthon-kernel/-/tree/master/src/modules/turtle) . You can try it as part of the Basthon project console [here](https://console.basthon.fr/?from=examples/spirale.py).

Closing the issue but don't hesitate to comment further.
