### ISSUE TITLE
Incorrect ContentType for pyodide.asm.data in CircleCI artefacts

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#174]
When testing the artefacts built in Circle CI, e.g.,
  https://640-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/python.html
(which corresponds to https://github.com/iodide-project/pyodide/commit/16b15968ec085f0a9540feb6bfd642d997788f4c though the exact commit doesn't matter),

when using `"url" : "./pyodide_dev.js"` to load the development version, `pyodide.asm.data` is served incorrectly with  `Content-Type: text/plain;charset=UTF-8` and loading subsequently fails with,

```py
TypeError: Response has unsupported MIME type
```

I'm not sure how MIME type is exactly determined in ngnix (the used server) in this case (whether other parameters in addition to extension are taken into account) , but locally,
```bash
% file ./build/pyodide.asm.data
./build/pyodide.asm.data: Python script, ASCII text executable
% file ./build/numpy.data 
./build/numpy.data: data
```
and `pyodide.asm.data` does indeed look like a Python script.

Full request and response headers can be found below,

<details>

**Request headers**
```
GET /0/home/circleci/repo/build/pyodide.asm.data HTTP/1.1
Host: 640-122663163-gh.circle-artifacts.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://640-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/python.html
Cookie: [...]
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```
with 
**Response headers**
```
HTTP/1.1 200 OK
Cache-Control: max-age=31556926
Content-Encoding: gzip
Content-Type: text/plain;charset=UTF-8
Date: Tue, 18 Sep 2018 21:40:12 GMT
Server: nginx
Set-Cookie: [...]
Strict-Transport-Security: max-age=15724800
X-CircleCI-Identity: artifacts-service-v1.0-7685584459-6cvkc
transfer-encoding: chunked
Connection: keep-alive
```
</details>

Being able to load packages from CircleCI artifacts would help testing PRs.  This also means that users who deploy files on their server (e.g. NGNX) might run into a similar issue.

Github pages must use different settings because there the `content-type` is `application/octet-stream`, as expected.

**Comment by mdboom** [comment]
Both of these servers are sort of doing a reasonable thing, I guess.  It's tricky when you don't have access to the webserver configuration to make these things right.

We could, I suppose, have file_packager.py add a few bytes of binary garbage to the beginning to fool the webserver.

We could also try using a different file extension.  On my Linux box, /etc/mime.types has the following entry:

```
application/octet-stream                bin lha lzh exe class so dll img iso
```

So I guess we could use "bin"?  Shouldn't be hard to change now that we've forked file_packager.py...

**Comment by rth** [comment]
True, though I was hoping we could keep local changes in `file_packager.py` to a minimum, to make synchronization with upstream easier.

**Comment by mdboom** [comment]
Sure.  In this case, I suspect they may take the `data` -> `bin` change pretty readily, since it solves a pretty general problem.

**Comment by mdboom** [comment]
This is sorta closed by #170.  I think it's working "by accident" a little, so it's up to you whether we want to close this or keep it open.

**Comment by rth** [comment]
Actually, I'm still getting this error about `Response has unsupported MIME type` in CircleCI with the last commit on master (that includes lz4 compression),

https://714-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/python_dev.html

both for chrome and firefox, even if the content-type of the `pyodide.asm.data` is now `application/octet-stream` as expected. Maybe I'm missing something. Tried disabling browser cache and using a private navigation tab.

**Comment by mdboom** [comment]
It looks like the broken fetch is actually `pyodide.asm.wasm` which needs to have a mimetype of `application.wasm` (but almost nothing understands that MIME type yet.  I'm investigating whether CircleCI provides any way for us to override MIME types.

**Comment by mdboom** [comment]
Just to close the loop on this: I wasn't able to find a way to convince Circle-CI to serve the correct mime type.  Over time, OSes will update to include `application/wasm` in their `mime.types` file, but who knows how long that will take.

**Comment by mdboom** [comment]
I filed a bug with Circle-CI: https://discuss.circleci.com/t/serve-wasm-artifacts-with-the-application-wasm-mime-type/25385

**Comment by rth** [comment]
Thanks for investigating this!

**Comment by rth** [comment]
Closing as this was resolved in https://github.com/iodide-project/pyodide/pull/628 I think (or they fixed in on the CircleCI side). The new issue is https://github.com/iodide-project/pyodide/issues/648
