### ISSUE TITLE
Calling stub instead of sigaction warning

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#190]
When running tests with debug flags in #189,

```
test/test_common.py::test_import[firefox-kiwisolver]
test/test_common.py::test_import[firefox-cycler]
test/test_common.py::test_import[firefox-matplotlib]
```
produces a number of following warnings,
```
Calling stub instead of sigaction()
Calling stub instead of sigaction()
Calling stub instead of sigaction()
# repeated >10x times
```
sometimes followed by,
```
Calling stub instead of __libc_current_sigrtmin
Calling stub instead of __libc_current_sigrtmax
```

(full traceback can be found in https://github.com/iodide-project/pyodide/issues/189#issue-363659037)

As mentioned in https://github.com/kripken/emscripten/issues/6987#issuecomment-412965421

> That sigaction warning may be important - signals are not actually supported on the web, so the question is whether your app uses them in an important way.

Sigaction appear to be implemented in muscl, but not used in emscripten (the warning is raised [here](https://github.com/kripken/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/library_signals.js#L43)). Maybe it could be also something worth disabling explicitly in `pyconfig.h` similarly to what is done in https://github.com/iodide-project/pyodide/pull/187,
```c
/* Define to 1 if you have the `sigaction' function. */
#undef HAVE_SIGACTION
```
which in CPython appears to be used in,
```
Modules/readline.c
Modules/faulthandler.c
Modules/signalmodule.c
Python/pylifecycle.c
```

**Comment by rth** [comment]
Though in CPython if `sigaction` is not available `signal` is mostly used instead,
```c
  #ifdef HAVE_SIGACTION
      (void)sigaction(signum, &user->previous, NULL);
  #else
      (void)signal(signum, user->previous);
  #endif
```
which is also [a stab in emscripten](https://github.com/kripken/emscripten/blob/20602efb955a7c6c20865a495932427e205651d2/src/library_signals.js#L11-L15) (except for `SIGALRM`) so this may not matter that much in practice. Still it might be good to disable all the CPython functionality that is not available.

Will make a PR once https://github.com/iodide-project/pyodide/pull/187 is merged..

**Comment by mdboom** [comment]
Cool.  This all makes sense.  I wonder what the signal it's trying to send actually is...  Obviously it's not something critically important, because things "just work", more just curious...

**Comment by rth** [comment]
FWIW, now we indeed get,
```
Calling stub instead of signal()
```
instead of the previous identical `sigaction` warning..
