### ISSUE TITLE
LinkError: import object field '___cxa_find_matching_catch_14' is not a Function

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#191]
Another recurrent issue detected as part of #189 when built with `-s ERROR_ON_UNDEFINED_SYMBOLS=1`, is the error, 
```py
LinkError: import object field '___cxa_find_matching_catch_14' is not a Function
```
e.g. after,
```py
    import pandas._libs.window as _window
ImportError: Could not evaluate dynamic lib: /lib/python3.7/site-packages/pandas/_libs/window.so
# ..
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 35, in eval_code
    exec(compile(mod, '<exec>', mode='exec'), ns, ns)
  File "<exec>", line 1, in <module>
ImportError: Could not evaluate dynamic lib: /lib/python3.7/site-packages/kiwisolver.so
```
there are also other `LinkErrors` e.g.
```py
E           from . import _path, rcParams
E       ImportError: Could not evaluate dynamic lib: /lib/python3.7/site-packages/matplotlib/_path.so
E       LinkError: import object field 'invoke_iiddddi' is not a Function
```

`___cxa_find_matching_catch` is an emscripten function and I'm not sure if it's a bug there or if we are just failing to export it in the built `.so`, e.g, if it should be added to the `-s EXPORTED_FUNCTIONS` option in the Makefile.

Very remotely related to https://github.com/iodide-project/pyodide/issues/188

**Comment by mdboom** [comment]
It's not clear to me whether or not these things matter in practice.  My gut reaction is to postpone dealing with these until we start seeing unit tests that are affected by this.

**Comment by rth** [comment]
Having seen this error in a while, so probably not relevant anymore. Closing.
