### ISSUE TITLE
Punt to Javascript for text encoding/decoding

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#22]
The tables for some of the larger CJK encodings are quite large in the Python implementation.  There should be no need for this, since the browser / OS already has them.

We should punt out to Javascript to handle encoding/decoding for codecs that we don't ship with Pyodide -- requiring some mapping between the Python names for the codecs and the web ones.

There is a polyfill [here](https://github.com/inexorabletash/text-encoding) to handle some of the cross-browser differences.

I'd consider this very low priority.  Python code should generally stick to Unicode and let the input/output layer handle encoding/decoding anyway.

**Comment by hoodmane** [comment]
@rth @dalcde Since pr #79 supposedly obsoletes this, seems like it could be closed.

**Comment by rth** [comment]
Thanks @hoodmane ! Closing as resolved by #79
