### ISSUE TITLE
Find an alternative to setup.py install --old-and-unmanageable

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#220]
Currently  `install_for_distribution` in `pyodide_build/pywasmcross.py` uses,
```
host/bin/python3 setup.py install --skip-build --prefix=install --old-and-unmanageable
```
as far as I know, the last option is setuptools only and doesn't work with distutils. While for some projects it might be straightforward to patch the `setup.py` to use setuptools, it's less the case in scipy  (https://github.com/iodide-project/pyodide/pull/211) which uses the custom distutils from numpy. 

The alternative could be to use `pip`, and the discussion in https://github.com/conda-forge/staged-recipes/issues/528 is very relevant. For instance, conda forge currently uses,
```
python -m pip install . --no-deps
```
and I wonder if we could do something similar. Possibly with `--prefix=install` and `--no-build-isolation`? Though I have not found an equivalent of `--skip-build` so far..

**Comment by mdboom** [comment]
The main reason for `--old-and-unmanageable` is to skip the metadata required for uninstallation of packages, which doesn't really make sense in our context.  But that's not critical except for file size reduction.

I think the `--skip-build` part will be the hardest to replicate.  At the point this runs, we've already built the package in a pretty custom way, and I think `pip` will want to handle the whole thing itself.

**Comment by rth** [comment]
Yeah, I agree that pip may be doing too many things and solving issues we don't have. In the https://github.com/iodide-project/pyodide/pull/211/files#diff-172f80631d9c4fea4847ee23a9743e6aR226 I ended up trying with `--old-and-unmanageable` and if that fails (one possibility is that it's not supported as we use distutils), try without it. It seems to work well enough though it's not very clean. Maybe improving that would be sufficient..

**Comment by mdboom** [comment]
We could also just try removing `--old-and-unmanageable` altogether and see if anything breaks and what the extra file size is.  It may be negligible.

**Comment by rth** [comment]
Yes, removing it does produce errors with setuptools roughly as follows https://github.com/pypa/setuptools/issues/672#issue-167150002,

> You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

(I forgot to include the actual message)

**Comment by mdboom** [comment]
Ah, I see.  It's just trying to help us not shoot ourselves in the foot, but in this case we know what you're doing.

The hack to try the flag and then remove it if that fails seems not to bad in that case.
