### ISSUE TITLE
Investigate compilation flags

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#234]
Currently we compile everything with `-O3`, it could be worth examining if other options might yield a better size / performance compromise.

According to https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#how-to-optimize-code,

> Building with `-O3` or `-Os` can produce an ever better build than `-O2`, and are worth considering for release builds. -O3 builds are even more optimized than `-O2`, but at the cost of significantly longer compilation time and potentially larger code size. `-Os` is similar in increasing compile times, but focuses on reducing code size while doing additional optimization. It’s worth trying these different optimization options to see what works best for your application.

So currently we are more tending toward performance. It would be interesting to know how in our case `-O2` and `-O3` perform with respect to,
 - the benchmark suite performance (that now runs in CI)
 - the packages size (it's listed in one of the build steps in CI)
 - (and to a lesser extent) the build time (which is also shown in CI).

Given that all of these metrics are shown in CI, the simplest bight be to just make a `WIP` Pull Request and try several options out. One can find the places where flags can be changed by searching for `-O3` occurrence in the code base.

Other things to try could be LLVM optimizations (with llvm-opts).

**Comment by aditj** [comment]
Can I take this up? :smile:

**Comment by rth** [comment]
Sure, @aditj contributions would be welcome.

**Comment by rth** [comment]
This is probably something we have to do continuously, particularly as we update emscripten. Closing it for now.
