### ISSUE TITLE
Binary package compatibility

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#241]
As reported by @tiwariayush when building pyodide master locally (without Docker) on Debian based Linux then trying to use that with scipy package build by Circle CI (that uses Docker) one gets,  

1. On chrome,
```
RuntimeError: function signature mismatch
    at wasm-function[2954]:1031
    at wasm-function[2947]:714
    at wasm-function[11956]:10
    at wasm-function[805]:687
    at wasm-function[816]:82
    at wasm-function[2717]:37598
    at wasm-function[15610]:7
    at wasm-function[2712]:3903
    at wasm-function[811]:238
    at wasm-function[2722]:899
```
2. On firefox,
```
RuntimeError: Indirect call signature mismatch
```
when trying to import a scipy module that has C extensions. At the same time doing this works fine for packages built with the same Docker image (e.g. I have been doing this in https://github.com/iodide-project/pyodide/pull/226 to get a package that is not yet included in master).

It may mean that with respect to "binary" package compatibility, not only packages built with different pyodide versions may not be compatible, but it would also apply to packages built in different environements (though maybe it's only specific to scipy). 

There is a report with a similar error message in https://github.com/kripken/emscripten/issues/5034 but that one appears to be Chrome specific, and so might be due to other factors.

There may not be much we can do about it, short of using the same Docker image. Just opening this issue for future reference. Maybe it could be worth adding a short description in the docs about it (or at least the current backward compatibility siutuation)?

**Comment by mdboom** [comment]
I'm pretty sure that's not how this is *supposed* to work.  I unfortunately can't reproduce.  I can load the scipy package in the CircleCI artifacts into a Pyodide otherwise built natively on my Fedora machine without issues.

Is it possible the native and docker are at slightly different versions, particularly with different NUM_PARAMS values?

**Comment by rth** [comment]
Nevermind, the `NUM_PARAMS` values were indeed different.

Circle CI was working because currently on master (and in the scikit-learn PR) we use the Circle CI cache for emsdk from the scipy PR (that went in with the joblib PR -- as I was trying to make all this work together). So packages built on master with CircleCI have a larger `NUM_PARAMS` than what is actually written in the code and that would indeed be an issue when mixing packages rebuilt from scratch from master and the scipy PR.

So the above errors are just due to a different value of `NUM_PARAMS`.

**Comment by tiwariayush** [comment]
Hi, sorry for late response. 

Thanks @rth for clarifying the problem. I rebuild again using #226 and used the scipy build files from the latest build for `circleCI`:

https://1616-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/scipy.js
https://1616-122663163-gh.circle-artifacts.com/0/home/circleci/repo/build/scipy.data

This made it possible to use both `scipy` as well as `scikit-learn` (almost all models of scikit-learn).

**Comment by rth** [comment]
Great, thanks for the confirmation @tiwariayush !
