### ISSUE TITLE
Explore Zstd compression

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#243]
As suggested by @jakirkham in https://github.com/iodide-project/pyodide/pull/211#issuecomment-436521429 ,

> FWIW people have been playing with using [Zstd](https://github.com/facebook/zstd) to compress Conda packages and like it. Not sure how viable that is for your use case (or how easy it would be to get Zstd in the browser), but it could be an interesting area to explore.

That could be an interesting direction to explore as a replacement for the current lz4 file system compression. According to its [home page](https://github.com/facebook/zstd) it can produce a ~30% better compression ratio, while keeping a reasonably fast read and write speeds.

To take the analogy of compressed file systems, BTRFS added support for it recently, and [benchmarks](https://www.phoronix.com/scan.php?page=article&item=btrfs-zstd-compress&num=4) show that overall it performs quite well in that use case.

There is also an existing buid for webassembly in https://github.com/yoshihitoh/zstd-codec

A direction that could be worth exploring to make package sizes smaller.

Earlier related discussion can be found in #235

**Comment by jakirkham** [comment]
One additional point to add is Zstd has the ability to build up a dictionary that does well for a large amount of data and then apply that dictionary to compress small chunks. IOW one could use Zstd to find the best way to compress many popular packages as one big piece of data and then save this dictionary, which can then be used to compress the packages individually as well as any new packages that enter the ecosystem. This should give a better compression ratio than merely trying to compress packages individually.

ref: https://github.com/facebook/zstd#the-case-for-small-data-compression

**Comment by rth** [comment]
> Zstd has the ability to build up a dictionary that does well for a large amount of data and then apply that dictionary to compress small chunks

That looks very impressive!

**Comment by madhur-tandon** [comment]
@rth Can I be assigned this and get some starter tips as well?

**Comment by rth** [comment]
This would imply more patches on top of emscripten and/or its file-packager, so for now I'm not sure it's worth it. Besides we use the brotli compresion when distributing files via the CDN which already offers comparable compressions ratios @ similar decompression speeds https://peazip.github.io/fast-compression-benchmark-brotli-zstandard.html
