### ISSUE TITLE
Port scikit-image

### ISSUE THREAD

**Issue by oeway** [iodide-project/pyodide#253]
Hi, I am trying to make some demos for image processing, would be great to have scikit-image also supported.

**Comment by rth** [comment]
scikit-image would be nice. It depends on merging https://github.com/iodide-project/pyodide/pull/211 which in turns depend on https://github.com/iodide-project/iodide/pull/1122 I think.

**Comment by oeway** [comment]
A general question, would it be possible that scikit-image could be supported sometime soon, since https://github.com/iodide-project/pyodide/pull/211 is already merged?

**Comment by rth** [comment]
It would be possible if someone makes it happen :) Would you be interested in making a PR?

Looks like, besides scipy, scikit-image has a few other dependencies,
https://github.com/scikit-image/scikit-image/blob/master/requirements/default.txt
```

numpy>=1.11
scipy>=0.17.0
matplotlib>=2.0.0,!=3.0.0
networkx>=2.0
pillow>=4.3.0
imageio>=2.0.1
PyWavelets>=0.4.0
dask[array]>=0.9.0
cloudpickle>=0.2.1
```
we might get away with skipping the last two (cf https://github.com/scikit-image/scikit-image/issues/3410) and networkx will be added in https://github.com/iodide-project/pyodide/pull/271, but that still leaves at least `pillow` and `imageio`. I'm not sure how large pillow is (I hope not too large). As to pywavelets, it's only used in denoising so it might be easier to patch that import in a first step..
 
Would you be interested in making a PR to add one of scikit-image dependencies?

**Comment by oeway** [comment]
@rth I would love to contribute, however, at the moment I am quite busy with other stuff, and I have no experience in compiling these libraries.

**Comment by rth** [comment]
@oeway I also don't have much bandwidth to work on this at the moment, unfortunately. Hopefully someone will make it happen :)

**Comment by grlee77** [comment]
If you want to get PyWavelets to work it is probably not too hard. It mainly just needs Cython to build (and there is no OpenMP). It can optionally use C99-complex, but that can be disabled. I am a maintainer for it, so can help with any issues you might encounter.

**Comment by chigozienri** [comment]
> If you want to get PyWavelets to work it is probably not too hard. It mainly just needs Cython to build (and there is no OpenMP). It can optionally use C99-complex, but that can be disabled. I am a maintainer for it, so can help with any issues you might encounter.

@grlee77 PyWavelets built without any issues, thanks!
