### ISSUE TITLE
Loading available packages fail if called after trying to load non-existent package

### ISSUE THREAD

**Issue by tiwariayush** [iodide-project/pyodide#254]
Hi, I am not able to load available package(s), after trying to load a non-existent package.

For example: 

```
# First available package to be loaded, it succeeds as expected
pyodide.loadPackage('numpy')
PROMISE fulfilled

# Trying loading non-existent package, it fails as expected
pyodide.loadPackage('sympy')
PROMISE rejected

# Trying loading available package, gets rejected (NOT EXPECTED)
pyodide.loadPackage('matplotlib')
PROMISE rejected
```

I tried it on my built version of pyodide (both from pyodide `master`  as well as from #226 ).
I'm running into this problem both on Chrome as well as firefox.

**Comment by rth** [comment]
Thanks for the report. I can confirm on master. Below is a test to reproduce it in the test suite, I think,
```py
def test_load_hadle_failure(selenium_standalone):
    selenium = selenium_standalone
    selenium.load_package('pytz')
    selenium.run('import pytz')
    selenium.load_package('pytz2')
    selenium.load_package('pyparsing')
    assert 'Loading pytz' in selenium.logs
    assert 'Loading pytz2' in selenium.logs
    assert "Unknown package 'pytz2'" in selenium.logs
    assert 'Loading pyparsing' in selenium.logs
```

it may be a regression after https://github.com/iodide-project/pyodide/pull/145 or https://github.com/iodide-project/pyodide/pull/136, will try to check.
