### ISSUE TITLE
support named arguments/keywords in `JsProxy_Call`

### ISSUE THREAD

**Issue by oeway** [iodide-project/pyodide#261]
Python function calls support named arguments, but in JS there is no native named arguments. In ECMAScript 6, functions can take an object with default values:
```javascript
 function js_range({ a = 0, b = 10 }) {
        console.log(`${a}-${b}`)
 };

execute `js_range({})` in the JS console will get `0-10` as output.
execute `js_range({a: 99, b: 999})`  in the JS console will get `99-999` as output.
```

Right now we can do this in pyodide:
```python
from js import js_range

js_range({'a': 99, 'b': 999})

```

However, I think it would be better to call functions defined in JS (e.g.: `js_range` defined above) with named arguments in Python. The following code is not working now, but would be really great to have this feature:
```python
from js import js_range

js_range(a=99, b=999)
```

As to my understanding so far, this type of conversion should be relatively simple.  I found a function `JsProxy_Call` in https://github.com/iodide-project/pyodide/blob/master/src/jsproxy.c#L99 . 

`static PyObject* JsProxy_Call(PyObject* o, PyObject* args, PyObject* kwargs)`

In order to support named argument style, we just need to check if `kwargs` is empty or not, if not, pass kwargs as a JS object and append to the argument list.

**Comment by mdboom** [comment]
This is a cool idea.  Is there a way to tell if the Javascript function is of this form?  I'm trying to see around corners if there might be negative consequences to doing this if the function isn't expecting this convention.
