### ISSUE TITLE
python2js : support numpy arrays with non float dtype

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#267]
Currently, there is a test that checks that numpy array can be converted to javascript array in `test_runpythonasync`, but while this work for default dtype, this fails for e.g. int,
```py
def test_numpy_array2js(selenium_standalone):
    selenium_standalone.load_package('numpy')
    output = selenium_standalone.run(
        """
        import numpy as np
        np.zeros(5, dtype='int')
        """
    )
    assert output == [0, 0, 0, 0, 0]
```
produces,
```
>       assert output == [0, 0, 0, 0, 0]
E       assert [{}, {}, {}, {}, {}] == [0, 0, 0, 0, 0]
E         At index 0 diff: {} != 0
E         Use -v to get the full diff

test/test_python.py:490: AssertionError
```
where on the left side, we get `PyProxy` objects.

**Comment by rth** [comment]
There is some support for typed arrays (see https://github.com/iodide-project/pyodide/blob/master/docs/type_conversions.md#typed-arrays) but mostly for js2python I think?

That same documentation states,

> Numpy arrays are currently converted to Javascript as nested (regular) Arrays. A more efficient method will probably emerge as we decide on an ndarray implementation for Javascript.

So this issue was about the first sentence not working expected.

As to a more efficient array representation in JS, I guess it's an open topic, and suggestions are very welcome. Once one gets e.g. a typed array in JS, the question is what is the best way to do some usefil operations on it. That would probably require some library. Something like https://github.com/iodide-project/untitled-math-project might be relevant as well.

**Comment by oeway** [comment]
@mdboom For the ndarray representation in js, I have been using a simple object representation in one of my project. What I did is to get the raw bytes by using `array.tobytes()`, then just wrap the raw bytes in a dictionary [(code)](https://github.com/oeway/ImJoy-Engine/blob/2f30440545e851db991cd8e17aa0ac5eb88e29f8/imjoy/imjoyWorkerTemplate.py#L174).
```js
 js_obj = {__type__: 'ndarray', __value__ : BYTES,  __shape__: [10, 10, 10], __dtype__: 'int32'}
```
Then this object can be transferred(in my case), or converted to a JS object, the raw bytes are converted into ARRAY_BUFFER:
```js
 js_obj = {__type__: 'ndarray', __value__ : ARRAY_BUFFER,  __shape__: [10, 10, 10], __dtype__: 'int32'}
```
In JS, we can then use it, for example use it in [numjs](https://github.com/nicolaspanel/numjs/) or [tensorflow.js](https://js.tensorflow.org/) by converting this objects depending on the contexts: [to Tensorflow.js](https://github.com/oeway/ImJoy/blob/eb39289ecd4a784ee7e2cdbb7b88b8abefad8690/web/public/static/jailed/_JailedSite.js#L539), and [to NumJS array](https://github.com/oeway/ImJoy/blob/eb39289ecd4a784ee7e2cdbb7b88b8abefad8690/web/public/static/jailed/_JailedSite.js#L533).

To convert the JS ndarray back to a Python numpy array ([ref](https://github.com/oeway/ImJoy-Engine/blob/2f30440545e851db991cd8e17aa0ac5eb88e29f8/imjoy/imjoyWorkerTemplate.py#L213)):
```python
np_array = np.frombuffer(js_obj['__value__'], dtype=js_obj['__dtype__']).reshape(tuple(js_obj['__shape__']))
```

If you want more powerful representation, perhaps also have a look at [numjs](https://github.com/nicolaspanel/numjs/blob/master/src/ndarray.js) and [tensorflow.js](https://github.com/tensorflow/tfjs-core/blob/v0.12.0/src/ops/tensor_ops.ts). But I would suggest a very simple representation to keep it flexible.

About the idea of exposing an api for handle the encoding/decoding, what I have in mind is to have a intermediate dictionary/object representation through an encoding function ([e.g.](https://github.com/oeway/ImJoy-Engine/blob/2f30440545e851db991cd8e17aa0ac5eb88e29f8/imjoy/imjoyWorkerTemplate.py#L131)) and a decoding function ([e.g.](https://github.com/oeway/ImJoy-Engine/blob/2f30440545e851db991cd8e17aa0ac5eb88e29f8/imjoy/imjoyWorkerTemplate.py#L191)):

1. The encoding will produce a `dict` in Python, where the content only support primitive types(numbers, string, bytes etc.). The dictionary will be converted through `python2js` to a JS object (recursively). 
2. User can register handler functions to decide how should a Python object can be represented into an Python dictionary. And also how should the JS object coming out from `python2js` be represented/converted in JS. 
3. Do the same for js2python to make it more generic.

With the above steps and api, the user can then decide what to do with the objects, for example we will be able to handle the conversion between numpy and js object.

One additional benefit of such an intermediate object representation is that we will be able to send the object through `postMessage` for webworkers or even through `websocket` to elsewhere.

**Comment by mdboom** [comment]
These are some really good ideas.

I think we need:
1. A default behavior that is unsurprising and will work for most cases, without adding too many extra dependencies or complexity
2. A way to customize that behavior when necessary

I've sort of been plugging on 1 first, but maybe it makes sense to come at it through 2 as you are doing.

Would you be interested in putting together a PR to handle the adding of encoding/decoding hooks?

**Comment by oeway** [comment]
Thanks, I can potentially do a PR and I would love to contribute, but I am quite busy with other stuff at the moment, and it's not gonna happened before Christmas. So feel free to incorporate them if someone else get a chance to work on it.

**Comment by JackChen20200818** [comment]
> To clarify some of the discussion above: Javascript typed arrays convert to Numpy arrays automatically, since Numpy arrays provide a superset of their functionality. This happens without copying the data.

@mdboom According to my observation, "Javascript typed arrays converting to Numpy arrays happens without copying data" is not correct.  For example, on the JS side:

> arr=new Uint8ClampedArray([1,2,3,4]);

while on the python side:

> pyodide.runPython(`
>   arr=np.asarray(js.arr)
>   arr[0] = 0
>   print(arr)
> `);
> 
which result is:

> [0 2 3 4]

again back to the JS side:

> console.log(arr)

the result is:

>  Uint8ClampedArray(4) [1, 2, 3, 4]

Js typed array  arr[0] is not changed, it proves that the memory are not shared, but copied.

**Comment by hoodmane** [comment]
@JackChen20200818 That is a bug though. If you read the code responsible for this in `python2js_buffer.c`, you will see that it is intended to convert Numpy arrays without copying data, but it just doesn't quite work correctly. Clearly some tests like your sample code to check whether or not data has been copied would be useful additions to the test suite.
