### ISSUE TITLE
Loading an unknown package from a custom URL

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#291]
As discussed in https://github.com/iodide-project/pyodide/pull/286,

by @madhur-tandon 
> The URL generated is correct and this issue is not related to it. The reason that it doesn't work without adding it to packages.json file is because the function load_package is defined that way. It checks if the package we are trying to load is present in this file, else, it returns the error of Unknown package 'numpy-broken'

and @mdboom 

>  I thought if you provided a URL, it wouldn't try to do the dependency resolution using packages.json. @rth: Is that how that's supposed to work? How does one load a completely unknown package?

**Comment by rth** [comment]
Hmm, this was definitely expected to work.

While building scikit-learn in https://github.com/iodide-project/pyodide/pull/226 there was a time where scipy was not yet merged in master, and so I just copied  the `scipy.{js,data}` from another PR into the scikit-learn PR. That worked even when `scipy` was not in `package.json`. Maybe there was a regression with the latest changes to `src/pyodide.js`, will investigate.

**Comment by mdboom** [comment]
Thanks.  It feels like it probably is an unintentional regression somehow.

**Comment by rth** [comment]
Yes, I'm wondering if it wasn't introduced in https://github.com/iodide-project/pyodide/commit/6cf40c49dd7f682419869d95cab20279d064e3cc which fixed https://github.com/iodide-project/pyodide/issues/254

I think previously it just printed to the log `unknown package {name}` but kept running for a valid URL..
