### ISSUE TITLE
Update examples URLs to use the new deployement location

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#294]
As mentioned in https://github.com/iodide-project/iodide/pull/1178#issuecomment-453089677 by @mdboom 

> The old approach (using Github pages) wouldn't scale to the file sizes required by Scipy.

> The new URL is: extremely-alpha.iodide.app/pyodide-0.4.0/pyodide.js

> ...and of course there are github releases, too, for folks who want to do their own deployment of the resources.

It would be great to update the links of the demo example (and the repo-url to use extremely-alpha.iodide.app).

Tried very quickly https://extremely-alpha.iodide.app/pyodide-0.4.0/python_dev.html with https://extremely-alpha.iodide.app/pyodide-0.4.0/pyodide_dev.js and loading https://extremely-alpha.iodide.app/pyodide.asm.data.js  errors with HTTP 404 since the URL points to the incorrect subdirectory, so maybe something might need to be adjusted (or I'm doing something wrong)..

**Comment by rth** [comment]
Also, it might we worth updating https://github.com/iodide-project/pyodide-demo description to reflect that it no longer contains the latest pyodide version..

**Comment by madhur-tandon** [comment]
I am willing to take this up :)

**Comment by vladdoster** [comment]
Did this ever get resolved?

**Comment by wlach** [comment]
> Did this ever get resolved?

Yes, I believe it did, this issue was filed before we had the external-facing server and the pyodide example notebook: https://alpha.iodide.io/notebooks/300/

If there are still problems, probably best to just file a new issue, since much of this issue refers to stuff that is obsolete.
