### ISSUE TITLE
Decimal is 450x slower than native

### ISSUE THREAD

**Issue by jstafford** [iodide-project/pyodide#315]
The Decimal data type performs 450 times slower in pyodide than the same code run natively. 

To test this I replaced the benchmarks with two of my own. The first I called `large_list`, and it multiplies two 1000 item lists of floats. It runs a very reasonable 10x slower than native. The second test is identical to the first, except that instead of floats it uses Decimals. It runs a painful 450x slower than native.
Here is `large_list`:
```
# setup: A = [2.1 for i in range(1000)] ; B = [3.2 for i in range(1000)]
# run: large_list(A, B)

def large_list(A, B):
    return [a*b for a,b in zip(A,B)]
```
Here is `large_decimal_list`:
```
# setup: from decimal import Decimal ; A = [Decimal('2.1') for i in range(1000)] ; B = [Decimal('3.2') for i in range(1000)]
# run: large_decimal_list(A, B)

def large_decimal_list(A, B):
    return [a*b for a,b in zip(A,B)]
```
And here is the resulting `benchmarks.json` file:
```
{
  "pystone": {"native": 0.456669, "firefox": 2.843, "chrome": 2.95},
  "large_decimal_list": {"native": 0.004931997666264781, "firefox": 2.188, "chrome": 2.229016110777778},
  "large_list": {"native": 0.002595901883776403, "firefox": 0.0214444444444444, "chrome": 0.025382222222222122}
}
```

When I profile similar code in the browser, I see that 95% of the total time (27% self time) is spent in one function (__PyEval_EvalFrameDefault), but I don't know how to proceed on debugging this further. I looked through the Decimal code at 
pyodide/cpython/build/3.7.0/host/lib/python3.7/_pydecimal.py, and at the PyEval_EvalFrameDefault code at pyodide/cpython/build/3.7.0/host/Python-3.7.0/Python/ceval.c  but nothing jumped out at me as a likely culprit.

**Comment by mdboom** [comment]
It looks like the C implementation of decimal isn't being built, so it's falling back to the Python implementation, which is understandably much slower.

The process would basically involve adding the appropriate incantations to `Setup.local`.
