### ISSUE TITLE
Package from PyPI

### ISSUE THREAD

**Issue by filips123** [iodide-project/pyodide#344]
There should be a support to install Python packages from PyPI. Unfourcantly, some packages require patches, but it should be at least possible to install directly-working packages.

**Comment by hamilton** [comment]
yes, see #38 about PyPI support

**Comment by rth** [comment]
> For pure Python packages that have a wheel on PyPi, there is also an implementation in #147

Closing since preliminary support was merged. See https://github.com/iodide-project/pyodide/blob/master/docs/pypi.md

**Comment by filips123** [comment]
@rth What about packages with C dependencies? Can they be installed/compiled automatically or would this require manual code changes?

**Comment by rth** [comment]
> rth What about packages with C dependencies?

Well to build C extensions, you need the emscripten / llvm toolchain. It seems unlikely that it would work directly in the browser (at least in the near future, as far as I know).

**Comment by filips123** [comment]
@rth Even if package provides a wheel?

**Comment by rth** [comment]
Wheels are architecture specific. Currently PyPi doesn't have wheels for the wasm target as far as I know. If those are supported one day, I imagine it could work.

**Comment by filips123** [comment]
So, could WASM wheels be proposed to PyPI?

**Comment by rth** [comment]
The issue is that currently pyodide is not stable enough. In particular, there is a few build env variables that when changed make packages incompatible with those built before. 

@mdboom Might know more about future development plans on this topic.

**Comment by filips123** [comment]
@rth I have another question... Is possible to also support installing pure-Python packages that don't provide a wheel, but only ZIP or TAR file?

**Comment by mdboom** [comment]
I don't have any plans to install packages from tarballs or zips.  This would imply running arbitrary `setup.py` files, which at best might not work and at worst is a security risk.  This is one of the main reasons to push the community to wheels.

**Comment by mdboom** [comment]
As for the earlier question about wasm wheels -- I agree with @rth that that is probably a bit premature.  Once we could guarantee ABI stability, that would be a great idea, but right now would probably be a major headache.

**Comment by rth** [comment]
I have opened a separate issue to discuss the possibility of binary wheels https://github.com/iodide-project/pyodide/issues/655
