### ISSUE TITLE
Feasible to enable sqlite3?

### ISSUE THREAD

**Issue by msabramo** [iodide-project/pyodide#345]
I was messing around with trying to getting [nltk](
https://www.nltk.org/) to work, but quickly ran into the issue that importing nltk fails right off the bat because some of the corpus modules (like [panlex_lite](https://www.nltk.org/_modules/nltk/corpus/reader/panlex_lite.html)) import sqlite3, but pyodide specifically [excludes sqlite3 in `remove_modules.txt`](
https://github.com/iodide-project/pyodide/blob/master/remove_modules.txt#L9). Even if you just want to use a sentence lexer, you’re out of luck because the lexers end up depending on some of those corpora.

I played around a bit with including a WASMized sqlite3 (e.g.:  
https://github.com/mandel59/sqlite-wasm or https://github.com/kripken/sql.js/) but didn’t get too far. 

Wondering if it’s worth the effort to get it working?

**Comment by msabramo** [comment]
See #352

**Comment by madhur-tandon** [comment]
I think this can be closed now since the PR for ``sqlite3`` is merged.
CC: @mdboom @msabramo
