### ISSUE TITLE
Porting  Beautiful Soup?

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#349]
Hi.  A lot of data is available on the web. 
Would it be hard for me to port beautiful soup?

Here is the setup.py file for beautiful soup.
https://github.com/waylan/beautifulsoup/blob/master/setup.py

It requires LXML and html5lib

https://pypi.org/project/html5lib/
says html5lib is pure python.

The LXML looks harder.  From
https://lxml.de/build.html#cython

> The lxml.etree and lxml.objectify modules are written in Cython. Since we distribute the Cython-generated .c files with lxml releases, however, you do not need Cython to build lxml from the normal release sources. We even encourage you to not install Cython for a normal release build, as the generated C code can vary quite heavily between Cython versions, which may or may not generate correct code for lxml. The pre-generated release sources were tested and therefore are known to work.

So should this be easy or hard to get beautiful soup running?  I am a reasonably good python developer, have some C background.

**Comment by hamilton** [comment]
@PythonLinks I believe we just merged in `beautifulsoup4` as of a couple days ago: https://github.com/iodide-project/pyodide/pull/341

I don't think it's made it in the most recent release. @mdboom is this right?

**Comment by mdboom** [comment]
That's correct.  This hasn't been deployed yet.

**Comment by madhur-tandon** [comment]
With the release of version 0.11.0, I think this can be closed too. Or Should we wait for https://github.com/iodide-project/iodide/pull/1735 to get merged first? CC: @mdboom
