### ISSUE TITLE
Add CompilePython Function

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#350]
So thank you for a very interesting product. 

You have a runPython function, but no compile python function. 
For Data Science, maybe you run the code once, so that is fine.  But for a general Python in the browser, it would be great to have two commands.  One to compile to bytecode, the other to execute said bytecode.  And keep the current runPython command.

At that point PyOdide would become quite interesting for single page web applications. 

I spent half an hour poking around the code, but could not figure out how to do it..  

Warm Regards
Chris

**Comment by mdboom** [comment]
Compiling Python is so fast, I doubt there would be much benefit for the complexity.  It probably would take longer to send the bytecode over the wire back to Javascript.  Can you provide an example where you've seen this have a measurable performance impact?

**Comment by rth** [comment]
Closing unless we can demonstrate that this would have a significant improvement on performance which would be worth the added complexity.
