### ISSUE TITLE
mkpkg tool should take source URLs as ``.tar.gz`` and not ``.whl``

### ISSUE THREAD

**Issue by madhur-tandon** [iodide-project/pyodide#363]
The ``mkpkg`` tool automatically creates ``meta.yaml`` files for pure python packages. It was introduced here: https://github.com/iodide-project/pyodide/pull/331. It automatically fetches the required information from ``PyPI``. However, the ``source`` ``url`` and ``source`` ``sha256`` that are fetched correspond to the ``.whl`` files in most of the cases. The script ``buildpkg.py`` however requires the files to be of the type ``.tar.gz``. 

From my observation, the files of type ``.tar.gz`` hosted on https://pypi.org are usually the last on the list of available files to download. Thus, this could be simply fixed by indexing ``-1`` instead of ``0`` in the line https://github.com/iodide-project/pyodide/blob/b95b6692f8dd933cbf42191a1dfd99c3f72ad575/pyodide_build/mkpkg.py#L21

**Comment by madhur-tandon** [comment]
I think this is already addressed by @msabramo's PR here: https://github.com/iodide-project/pyodide/pull/356. @msabramo Feel free to write ``Closes https://github.com/iodide-project/pyodide/issues/363`` in your PR description. I didn't realise that you had already tackled this 🥇 💯

**Comment by madhur-tandon** [comment]
OR maybe I should close this already, @mdboom What do you suggest?

**Comment by msabramo** [comment]
Haha, @madhur-tandon, you and I think alike. 🙌 😄

**Comment by mdboom** [comment]
We can leave this open until #356 is merged.
