### ISSUE TITLE
Time module in standard lib

### ISSUE THREAD

**Issue by JanMatas** [iodide-project/pyodide#371]
Hi,

first of all, thanks for the great project. This is all massively impressive.

I have been tinkering around with pyodide for a while and it seems that I can't get python `time` module to work. For example, `pyodide.runPythonAsync('import time\ntime.sleep(10)\nprint(5)')` returns immediately (with 5 being correctly printed), but I would expect it to resolve after 10 seconds.

I was wondering if I am doing something wrong or if this functionality is not yet supported.

Best,
Jan

**Comment by mdboom** [comment]
Using `sleep` is not possible from WebAssembly.  [This article](https://github.com/emscripten-core/emscripten/wiki/Asyncify) does a good job explaining why (though unfortunately the alternative solutions aren't great).

We do need to address async stuff in general in Pyodide, but we don't have a good solution yet.

**Comment by JanMatas** [comment]
Thank you for the details!
