### ISSUE TITLE
https urllib bug

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#375]
Here is a very short python 3 program which runs on Linux, but not on Pyodide. 

%% py
```
from urllib.request import urlopen
site = 'https://www.fridaysforfuture.org/events/map'

def doit():
    with urlopen(site) as response:
        page = response.read()
        snippet = page [0: 400]
        # On Linux print the result.
        #print (snippet)
        #on Iodide return the result        
        return snippet
doit()    
```
At the end of this issue  is the error message I get when running it on Iodide. 

At first I thought urllib is not available, but it is.  Your web site even says Python has access to the full web api.   Then I thought maybe you support 
http: but not yet https:  I know in Linux Https requires some additional library. 
 In any case a reasonably quick web search does
not yield any answer, so I thought I would at least report it. 

I think it should be reasonably easy to use javascript to fetch the data, then 
I can have beautiful soup parse it.  So I do not want to work too hard to fix this bug, but I thought it would be good to report it. 

The error message is below.
Thanks
Chris

Error: Traceback (most recent call last):
  File "/lib/python3.7/site-packages/pyodide.py", line 44, in eval_code
    return eval(compile(expr, '<eval>', mode='eval'), ns, ns)
  File "<eval>", line 10, in <module>
  File "<exec>", line 5, in doit
  File "/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/lib/python3.7/urllib/request.py", line 548, in _open
    'unknown_open', req)
  File "/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/lib/python3.7/urllib/request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

_hiwire_throw_error()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.js:8:42138
{anonymous}()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.wasm:wasm-function[355]:0xdee4f
{anonymous}()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.wasm:wasm-function[382]:0xe0afe
pyodide/Module.__runPython()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.js:8:2041773
_runpython_init_js/Module._runPythonInternal()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.js:8:46210
internal()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.js:8:46780
_runpython_init_js/Module.runPythonAsync()@https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.js:8:47265

**Comment by mdboom** [comment]
Networking in Python does not work, since it relies on low-level networking primitives (socket) that aren't allowed in the browser sandbox.

"Supporting the Web API" means supporting the APIs that Javascript provides to do things on a web page.

Like you say, the best way forward for now is to use Javascript to perform the networking, and then pass it along to Python.

We might be able to provide emulation of the high-level networking interfaces in Python on top of the Javascript API, but that work has not been done.

**Comment by mdboom** [comment]
The high-level API probably could be rewritten to use Javascript APIs.  Lower level networking won't be available, however, due to browser sandboxing.

**Comment by filips123** [comment]
@mdboom Yes, I know. This would be useful in case of packages from PIP which only use `urllib` and other native modules.

There should be support for packages for HTTP requests (`urllib`, `urllib3`, `http.client`, `requests`), SSL (#529), and other high-level networking (and other) libraries.

But I also saw [libdweb](https://github.com/mozilla/libdweb) which are "Firefox extensions containing an experimental libdweb APIs". Some of those APIs include support for TCP and UDP sockets. It would be also good to support that (but maybe later) in case if Pyodide will be one day so stable that it will be possible to create Firefox extensions with it.

**Comment by dberardo-com** [comment]
is this somehow related to: https://github.com/koenvo/pyodide-http/issues/28 ?
