### ISSUE TITLE
Is there a way to output the code used in the computation like in Jupyter?

### ISSUE THREAD

**Issue by vrthra** [iodide-project/pyodide#377]
Jupyter allows one to include the code used in the evaluation in the report. That is, the results are included inline. Is there a way to achieve something similar in pyodide? That is, is there a magick that I cak use to output the currently executed block to the report?

**Comment by mdboom** [comment]
There's an open issue for this in Iodide here: https://github.com/iodide-project/iodide/issues/727

Closing as a dupe.
