### ISSUE TITLE
Importing pandas is extremely slow (and even 2x slower when done from a code cell)

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/pyodide#378]
Running https://alpha.iodide.io/notebooks/222/ causes a hang at `Loading pandas, pytz, python-dateutil, numpy, matplotlib, pyparsing, kiwisolver, cycler`.

I tinkered more and found that `import pandas` works fine when executed from REPL (though typing / ui is unresponsive while it happens, so maybe some threading issues as well), but hangs completely when executed from a code cell.

I use an up-to-date Chrome on Windows: `Version 73.0.3683.103 (Official Build) (64-bit).`

**Comment by vadimkantorov** [comment]
I waited longer, and finally https://alpha.iodide.io/notebooks/222/ works, it just takes 250 seconds (at cold start; and 180 seconds when all files are cached) to run - which is terribly slow. During this time the interpreter and the UI is blocked and is unresponsive.

**Comment by vadimkantorov** [comment]
Running in a recent Firefox (with a cold cache) also takes around 1.5 minutes. Firefox even suggested 5 times to kill the page :) The code editor was also unresponsive during execution.

**Comment by wlach** [comment]
Hmm, using the latest version on alpha.iodide.io, I'm not seeing this. Doing "import time; s = time.time(); import pandas; time.time() - s", it takes about 6 seconds whether done from the console or from inside a code cell.

@vadimkantorov can you reproduce this? If so I think we should just close this in favor of #347

**Comment by vadimkantorov** [comment]
I don't see big difference between a code cell and REPL anymore, but on my Chrome on Windows it takes around 12seconds (with warm cache)

**Comment by rth** [comment]
Closing as mostly resolved, as far as I can tell. There isn't much we can do about iodide from the pyodide repo in any case.

**Comment by vadimkantorov** [comment]
One thing that could be useful to know in pyodide context: Chrome won't cache files larger than ~30Mb: https://github.com/emscripten-core/emscripten/issues/12212

If any of the libraries end up larger than this size, they get re-downloaded each time. So some chunking is needed

**Comment by rth** [comment]
30MB compressed or uncompressed? Scipy is now 35MB uncompressed (22MB brotly compressed) https://github.com/iodide-project/pyodide/issues/240#issuecomment-775384365 so it should be cached. If not we can probably slim it down the remaining 5 MB for instance by removing test files https://github.com/iodide-project/pyodide/issues/617  All other packages should be below that limit.

**Comment by vadimkantorov** [comment]
Can't tell. I was tetsing with a simple Python web server, not sure if it does gzip-compression, probably not

**Comment by vadimkantorov** [comment]
35Mb is some rough limit from my memory, best would be just checking about scipy specifically at Network tab to see if it gets 304

**Comment by rth** [comment]
With Chrome 88 and default settings scipy appears to be cached fine,
![image](https://user-images.githubusercontent.com/630936/107284061-7e654180-6a5d-11eb-816f-3212d8bd38b2.png)
