### ISSUE TITLE
Iodide MASTER still includes Pyodide 0.10 not 0.11.0

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#379]
If you take a look at: 
https://github.com/iodide-project/iodide/blob/master/webpack.config.js#L37

It says
const PYODIDE_VERSION = process.env.PYODIDE_VERSION || "0.10.0";

It should be 0.11.0

Hurrah!  My first clear simple useful issue. 

Or am I missing something?
Warm Regards
Chris

**Comment by mdboom** [comment]
0.11.0 was tagged like 10 hours ago... :)

https://github.com/iodide-project/iodide/pull/1735 updates it.  It will need to go through CI and get deployed...

**Comment by rth** [comment]
Closing as resolved.
