### ISSUE TITLE
importing the same python object several times should return the same js object

### ISSUE THREAD

**Issue by lovasoa** [iodide-project/pyodide#382]
Currently, the following notebook does not work as intented

```python
%% md
# Click me!
%% py
from js import document

def f(*args):
    document.querySelector("h1").innerHTML += "(>.<)"

document.body.addEventListener('click', f)
document.body.removeEventListener('click', f)

%%js
pyodide.pyimport("f") == pyodide.pyimport("f")
```

pyodide creates a new js wrapper around the same python function each time it needs one, which makes using some web APIs such as `removeEventListener` impossible.

**Comment by mdboom** [comment]
Thanks for finding this.  Indeed, you make a good point, and it would be good to fix this if possible.
