### ISSUE TITLE
any project to enable to run r program language on Iodide environment

### ISSUE THREAD

**Issue by osper66** [iodide-project/pyodide#385]
Hi.

 Current I just know this long-awaited project.

 Mozilla has any plan or idea to r(https://www.r-project.org/) , another famous data science tool?

  Thank you for advance.

**Comment by mdboom** [comment]
Yeah -- I know some R developers are interested in it, and it Mozilla we're happy to provide guidance, but don't have much bandwidth at the moment to work directly on this.  One of the big blockers there is getting a good Fortran compiler for WebAssembly.

**Comment by rth** [comment]
Closing this as likely out of scope for Pyodide for now, since we focus on Python.
