### ISSUE TITLE
Calling `dir` on JsProxy type objects returns empty list

### ISSUE THREAD

**Issue by typon** [iodide-project/pyodide#388]
From the example code:

```python
from js import document
elt = document.getElementById("targetElement")
elt.innerText = "I am changed!"
elt.style.backgroundColor = '#ffcccc'
dir(elt)
```
This returns `Array(0)[]` in the console.

Does `JsProxy` type have no `__dict__` attribute? It might be hard to do metaprogramming tasks on these objects without this information.

**Comment by mdboom** [comment]
Good point.  This should probably be doable.
