### ISSUE TITLE
stdout on alpha.iodide.io console?

### ISSUE THREAD

**Issue by Hekkun** [iodide-project/pyodide#392]
Hi guys,

I am relatively new to all this, and I couldn't figure out where else to ask this. I apologize if this is the wrong place and feel free to move or delete if so. Perhaps having a forum someewhere might be good?

On the alpha.iodide.io website, using the pyodide chunk or the py console, it never displays stdout, stderr etc as far as I can tell. How do I see this? 

![image](https://user-images.githubusercontent.com/49700980/56474985-ca816500-6436-11e9-82b9-de2389c06a4c.png)

**Comment by mdboom** [comment]
We have an open issue for this [here](https://github.com/iodide-project/iodide/issues/727).  Closing this as a duplicate.

In the meantime, it will show up in the web browser's console (in Development Tools).
