### ISSUE TITLE
[feature request] seaborn module

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/pyodide#399]
It's a matplotlib wrapper that depends on:
```
mandatory:
numpy (>= 1.9.3)
scipy (>= 0.14.0)
matplotlib (>= 1.4.3)
pandas (>= 0.15.2

optional: 
statsmodels (>= 0.5.0)
```

so I hope it could work in the base setup without many issues.

**Comment by rth** [comment]
Would you like to make the PR @vadimkantorov ? :)

**Comment by rth** [comment]
Nevermind, since it's a pure python wheel, it should be usable from PyPi as  discussed in https://github.com/iodide-project/pyodide/issues/413 once that issue is resolved.

**Comment by vadimkantorov** [comment]
I hope the PyPi way doesn't break trying to install `statsmodels`

**Comment by rth** [comment]
Aww, I have not checked all the dependencies. `statsmodels` would indeed need to be packaged, I think, as  pre-build C extensions for WASM do not exist on PyPi.

**Comment by vadimkantorov** [comment]
`statsmodels` is optional, so probably even without it most graph helpers would work

**Comment by rth** [comment]
Hi @vadimkantorov,

I think using micropip to install from PyPi is a better way, and packaging it separately won't really help much cf https://github.com/iodide-project/pyodide/issues/643

It does seem to work and dependencies are pulled correctly,

<details>
<summary>index.html</summary>

```
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <script type="text/javascript" src="https://pyodide.cdn.iodide.io/pyodide.js"></script>
  <script type="text/javascript">
    languagePluginLoader.then(function () {

        pythonCode = `
          def do_work(*args):
              import seaborn
              print(seaborn.__version__)

          import micropip
          micropip.install('seaborn').then(do_work)
        `

        languagePluginLoader.then(() => {
          return pyodide.loadPackage(['micropip'])
        }).then(() => {
          pyodide.runPython(pythonCode);
        })
  
    });
  </script>
</body>
</html>
```
</details>

<details>
<summary>Log</summary>

```
Python initialization complete pyodide.asm.js:8:56380
Loading micropip from default channel pyodide.js:129:17
Loading distlib from default channel pyodide.js:129:17
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ pyodide.asm.js:8:31197
Loading pandas from default channel pyodide.js:129:17
Loading pytz from default channel pyodide.js:129:17
Loading python-dateutil from default channel pyodide.js:129:17
Loading numpy from default channel pyodide.js:129:17
Loading scipy from default channel pyodide.js:129:17
Loading matplotlib from default channel pyodide.js:129:17
Loading pyparsing from default channel pyodide.js:129:17
Loading kiwisolver from default channel pyodide.js:129:17
Loading cycler from default channel pyodide.js:129:17
0.9.1.rc0
```
</details>

though I haven't checked beyond printing `seaborn.__version__` (and it's slow due to scipy size).  Closing, please comment if you think otherwise :)
