### ISSUE TITLE
Unable to evaluate Python cells in Safari

### ISSUE THREAD

**Issue by joseph-long** [iodide-project/pyodide#402]
Using Safari Version 12.1 (14607.1.40.1.4) on macOS 10.14.4, I am unable to run pyodide examples (though other iodide examples work). 

The only error that appears in the (devtools) console when I try to run a `%% py` block is 

```
[Error] Unhandled Promise Rejection: undefined
	(anonymous function)
	rejectPromise
	promiseReactionJob
```

I carved out a subset of one of the Pyodide examples that reproduces this behavior here: https://alpha.iodide.io/notebooks/2154/

<img width="1137" alt="Screen Shot 2019-04-28 at 9 45 10 PM" src="https://user-images.githubusercontent.com/31168267/56876815-e8cefe00-69fe-11e9-8b18-65cb8f1a254a.png">

**Comment by joseph-long** [comment]
(Though not visible in the screenshot, I did try with my ad blocker off just to be sure and observed the same behavior.)

**Comment by mdboom** [comment]
Are there any network failures on the networking pane?

**Comment by joseph-long** [comment]
No, it requests `https://alpha.iodide.app/pyodide-0.10.0/pyodide.asm.wasm` and gets back 2 MB with a HTTP 200 response code. The "preview" pane in Network does show "An error occurred trying to load the resource", but I think that's because you cannot preview a WASM file.

I should have mentioned that there's also this in the error console:
```
[Error] TypeError: undefined is not an Object. (evaluating ''msTrackingProtectionEnabled' in window.external')
	Global Code (2154:52)
```

but it appeared unrelated.

**Comment by mdboom** [comment]
I can duplicate this, but I still have no clue why it's happening.  We haven't really done any testing on Safari up to this point -- it's not clear what the difference may be.

**Comment by joseph-long** [comment]
Rats, I was hoping it'd be something obvious to the developers :) I've run in to issues with fetching resources in Safari due to differences in their interpretation of (I think) the Same Origin Policy, but that's just a guess. I'll poke around and see if I can get closer to the root cause.

**Comment by joseph-long** [comment]
Submitted to Safari Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=197472

**Comment by joseph-long** [comment]
I cloned and built Pyodide myself, and got a slightly different error:

```
Unhandled Promise Rejection: TypeError: WebAssembly.compileStreaming is not a function. (In 'WebAssembly.compileStreaming(fetch(wasmURL))', 'WebAssembly.compileStreaming' is undefined)
(anonymous function) — pyodide_dev.js:302
promiseReactionJob
```

This could be related, since it's the same error type. According to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compileStreaming#Browser_compatibility) that's an API that isn't available in Safari.

**Comment by mdboom** [comment]
Hmm...  I guess we'll need to add some sort of compatibility shim [here](https://github.com/iodide-project/pyodide/blob/master/src/pyodide.js#L302)

**Comment by joseph-long** [comment]
As a more general feature request / suggestion, it would be nice to have some feedback in Iodide for when things are busy downloading WASM blobs. I know there's a "Loading Python language plugin" message, but maybe there's a way to show a progress bar or a loading spinner?

**Comment by mdboom** [comment]
@joseph-long: Yeah -- we've done some work in that area (the work indicator in the upper right), but there's always room for improvement.  Please feel free to file an issue over in iodide-project/iodide with any ideas you might have.
