### ISSUE TITLE
why "rm -rf emsdk" in emsdk Makefile ?

### ISSUE THREAD

**Issue by wi11yp** [iodide-project/pyodide#405]
The docker instructions on the README file say you can "repeatedly run make inside the Docker environment to test your changes". But running **make** again seems to delete the entire emsdk folder needing a full emscripten rebuild which takes at least 1 hour on my machine.
Is this an issue that is only happening to me, or an issue in the documentation or the Makefile?

**Comment by mdboom** [comment]
That should only be running if you say `make clean`.  Are you just invoking `make` alone?

**Comment by wi11yp** [comment]
My bad :(

I think the bynaryen build failed which means the Makefile didn't "succeed" https://github.com/iodide-project/pyodide/blob/c8db5b6433ef58e50e41355717335395de67f111/emsdk/Makefile#L25.

Since it din't "finish", the whole emsdk process had to start from scratch again (which as mentioned, takes a loooong time).
