### ISSUE TITLE
pyodide.js as /one/ js file?

### ISSUE THREAD

**Issue by void4** [iodide-project/pyodide#415]
Right now pyodide.min.js loads further scripts and data from your website. Would it be possible to bundle everything into one file so it becomes easier to develop sites that work offline?

**Comment by rth** [comment]
The [`SINGLE_FILE` emscripten parameter](https://github.com/emscripten-core/emscripten/blob/f64d84e683489472bcd6062a506707c22390ab97/src/settings.js#L1260-L1270) could be relevant, though currently the import system assumes that there is one .js / data file per package and it would require significant work to change that I think.

Is the issue that there multiple data files, or that these are loaded from the iodide server? If it's the latter, see https://github.com/iodide-project/pyodide/pull/408 for instructions on serving packages locally.

**Comment by void4** [comment]
Mostly the latter, thank you!
