### ISSUE TITLE
Split scipy.data into multiple chunks to fit in cache

### ISSUE THREAD

**Issue by SimonBiggs** [iodide-project/pyodide#416]
Currently within Chrome the scipy.data size (160 MB) is larger than the maximum file size that Chrome will store in cache. Is is possible to split scipy.data into a few separate files so that they end up being stored within cache?

**Comment by rth** [comment]
Indeed. A more long term solution for reducing scipy size is outlined in https://github.com/iodide-project/pyodide/issues/240

**Comment by SimonBiggs** [comment]
Kk, for now I think we might just vendor out a few things from scipy ourselves. We're mostly using a few functions that are pretty standalone.

**Comment by rth** [comment]
This should be solved with https://github.com/iodide-project/pyodide/pull/1102, scipy is now 35MB instead of 160MB cf https://github.com/iodide-project/pyodide/issues/240#issuecomment-775384365
