### ISSUE TITLE
zipimporter fails with: "not a Zip file"

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/pyodide#418]
The relevant CPython source is: https://github.com/python/cpython/blob/master/Lib/zipimport.py

```
%% fetch
arrayBuffer: zipball=https://cors-anywhere.herokuapp.com/https://github.com/vadimkantorov/test/archive/master.zip
%% py
import js
with open('master.zip', 'wb') as f:
    f.write(js.zipball.tobytes())

import zipimport
zipimport.zipimporter('master.zip') 
# zipimport.ZipImportError: not a Zip file: 'master.zip'
```

**Comment by mdboom** [comment]
Things seem to be working consistently in terms of passing the data around in Pyodide.

However, this file fails to import even in native Python, so maybe something is invalid in the file itself?

```
Python 3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 19:59:33) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zipimport
>>> zipimport.zipimporter("master.zip")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
zipimport.ZipImportError: not a Zip file: 'master.zip'
```

**Comment by vadimkantorov** [comment]
It's strange, the zip-archive is created by GitHub. And if I use `zipfile.ZipFile`, it is read correctly from Python as well, but not from within `zipimport`.

**Comment by vadimkantorov** [comment]
Too bad Python doesn't like the zip files from GitHub. Seems like a bug in Python / GitHub.

**Comment by vadimkantorov** [comment]
Reported to Python at https://bugs.python.org/issue36914

**Comment by mdboom** [comment]
Cool.  This will be a handy thing to do when it works.  Good reason to update to Python 3.8 when it's available.

**Comment by vadimkantorov** [comment]
Except I don't know if Python will like to find modules in subdirectories `master.zip / reponame-master / something.py`. A relevant feature request here is to add some fetch magic to download files directly onto the file system.

**Comment by mdboom** [comment]
Yeah -- since it looks like the Zipfile support works on these files (it's just the zipimporter that doesn't work), we could unzip to the filesystem, add the appropriate paths to `sys.path` and then import.

**Comment by vadimkantorov** [comment]
That I already do :)
```
%% fetch
arrayBuffer: lab=https://cors-anywhere.herokuapp.com/https://github.com/schitaytesami/lab/archive/master.zip

%% py
import os, sys, io, zipfile
import js
if not os.path.exists('lab-master'):
    zipfile.ZipFile(io.BytesIO(js.lab)).extractall('.')
    sys.path.append('lab-master')
import election_data
```

**Comment by odesiuz** [comment]
The solution to this problem is using the sys.path to unzip and add the modules. Say you have a zip file `master.zip` containing modules like `lab-master.py` and `do_stuff.py` you can add the modules from the zip file as
```
import sys
sys.path.insert(0, master.zip)
sys.path.append(master)
import lab-master
import do_stuff
```

or you can append just one module like this:
```
import sys
sys.path.insert(0, master.zip)
sys.path.append(do_stuff)
import do_stuff
```

**Comment by kanikaKanu90** [comment]
I am facing similar issue with python 3.12

Below code is giving NameError: name 'extra' is not defined

import sys
from sys import path
path.insert(0, '..\\packages\\pack.zip')
print(extra.ugly.omega.FunO())

Note: I have a folder packages inside that a zip file named pack 
          pack.zip contains extra package.. which has subpackages 
          
         Not sure what I am doing wrong, not getting any clue.. also tried below but no success:
         
         # from zipimport import zipimporter
         # importer = zipimporter('..\\packages\\pack.zip')
         # importer.is_package("extra") 
         
         Looking for some help. Thanks in advance.
