### ISSUE TITLE
possible to call javascript function from python code?

### ISSUE THREAD

**Issue by shi-yan** [iodide-project/pyodide#421]
Hello, 

I saw the document regarding type conversion between python and js.

is it the only way to achieve interoperability between  js and python? Can python call js functions? basically I want to use python to draw some graph on my webpage using webgl. And maybe using html ui to control the python code. 

Thanks!

**Comment by shi-yan** [comment]
I saw that through "import js", I can have access to the global js object window. and if I define a function there, I can have access to it from python

**Comment by mdboom** [comment]
Yes.  This is documented [here](https://github.com/iodide-project/pyodide/blob/master/docs/type_conversions.md#using-javascript-objects-from-python)

**Comment by Suffro** [comment]
@mdboom the documentation you linked to does not exist anymore.

**Comment by rth** [comment]
@Suffro The updated link for that documentation is [here](https://pyodide.org/en/stable/usage/type-conversions.html).
