### ISSUE TITLE
Pyodide Tutorial at PyCon LT Help Needed

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#424]
I will be offering a tutorial on Pyodide at PyCon LT May 25th or 26th in Vilnius Lithuania. 

If any of the senior Pyodide developers will be there I would be grateful if you would attend to answer any of the questions which are beyond me. 

If you are new to Pyodide, and would like to learn how ot use it, as opposed to how to develop it, I invite you to attend my tutorial. Here is an updated description. 

Learn how to use Python's Data Science libraries, running in the browser. After an brief talk about Python in the browser, we learn how to use Python and Javascript together to fetch data, to calculate and to display results.

Iodide/Pyodide, offered by Mozilla, is like Jupyter Notebooks, but the optional cPython kernel runs in the browser, compiled to Web Assembly. All that is needed is a file server, and a web browser, no compute server is required. This is particularly good for schools, and web apps, so that the servers do not get overloaded by thousands of users. Pyodide already has a rich collection of Python libraries compiled to Web Assembly. 32 as of last week, certainly all the ones which I need.

It is best to develop web applications using a combination of Python and Javascript. We learn how to use Python in the browser, import data and libraries and calculate results. We learn how to communicate bidirectionally between Python and Javascript to calculate and display results. We plot things from both Javascript and Python. We learn the difference between the browser console and the Iodide console. We exercise all the different types of cells. Markdown, Python, Javascript, Raw, Fetch and CSS. We also build a simple web app using Pyodide without Iodide.

By the end of the tutorial the student should be comfortable using the basic tools, and be ready to begin their own custom projects.

**Comment by mdboom** [comment]
Thanks for letting us know. I don't think any of the core team will be able to make it to PyCon LT, but best of luck with the presentation.  Perhaps we could participate remotely, timezone and schedules permitting.  DM me on Gitter to work out the details.

I'm closing this, as it's not really an issue (describing a unit of work to complete).
