### ISSUE TITLE
iodide.output is flakey

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#429]
I could get the following to run from jsmd, but not from the py console, 
and sometimes not from the javascript console. 

I played with it for 20 minutes, could not get a reliable failure.  

sometimes something would work, someimes not. 
This is on the current production server. 

in any case import document, document, getElementById works, so that is good enough for me. 

%% py 
from js import iodide
mydiv = iodide.output.element("div")
mydiv.innerHTML = "HELLO 4"
iodide.output.text("FRED")
TypeError: Cannot read property 'append' of null

**Comment by rth** [comment]
This should probably be moved to the iodide repo. I don't have permissions to do that, so closing for now as it's out of scope for pyodide in any case.
