### ISSUE TITLE
Make package fetching happen automatically

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#43]
Right now, to load a package (a Python library that isn't in the core distribution), you have to add a Javascript cell with:

```
pyodide.loadPackage('numpy')
```

It would be great if all it took was (from Python):

```
import numpy
```

This is tricky, because the fetching must happen asyncronously, so you have to have a way to hop back to a currently running code cell after fetching the content.  I think this will require some shenanigans with the embedded Python interpreter, which doesn't seem to have a sort of "pause and resume" API.  But maybe I just haven't found it.

**Comment by mdboom** [comment]
I'm starting to wonder if this isn't such a great idea.  If we want to specify particular versions of packages, we'll need more of an API than Python's `__import__` can provide.  Having a separate step might make sense.

**Comment by bcolloran** [comment]
fwiw -- imo, from a UX perspective it would totally fine if users must specify which modules they want fetched at the time they load the language plugin (i think @hamilton suggested this somewhere, but not sure what issue number). I don't find it awkward or cumbersome at all, and it might even make a it a little less magical. I defer to you on this of course, but imo -- don't lose sleep on this one if it's too tough ;-)

**Comment by rth** [comment]
This now works with `pyodide.runPythonAsync`  -- closing.
