### ISSUE TITLE
0.12 release dumps files in the current directory

### ISSUE THREAD

**Issue by PythonLinks** [iodide-project/pyodide#436]
Usually when I open up a tar ball, it creates a directory and adds files below it. 
But I am always careful to first create a junk directory, and then open in that one. 
Thank god I did it this time.  You drop all the files in the main directory. 
Much better if they went into a pyodide directory. 

Hope that helps.

**Comment by mdboom** [comment]
This isn't a bad idea.  We'll also need to fix the Iodide deployment at the other end that pulls in these tarballs.
