### ISSUE TITLE
Update numpy to 1.16.2

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/pyodide#437]
Pyodide ships NumPy v1.15.1 (which was released on August 22, 2018), now there is v1.16.2 (which was released one month ago)

**Comment by rth** [comment]
@vadimkantorov A PR to update numpy would be very welcome :)

**Comment by vadimkantorov** [comment]
I'd need to edit https://github.com/iodide-project/pyodide/blob/master/packages/numpy/meta.yaml and test if the patches are still needed (in case no new quirks were introduced by NumPy)?

**Comment by mdboom** [comment]
Yep.

**Comment by algomaster99** [comment]
@rth @mdboom Shall I take up this issue?

**Comment by rth** [comment]
Sure, thanks @algomaster99 !

**Comment by joseph-long** [comment]
This is a blocker for #410 (at least, for including the most recent Astropy)

**Comment by artorias111** [comment]
Hey! I'd like to take this up and work on it if no one's working on it.
