### ISSUE TITLE
Release caching

### ISSUE THREAD

**Issue by SimonBiggs** [iodide-project/pyodide#452]
Would it be possible to have each release have all its respective files (such as pyodide.js) and all the other related files marked with their respective version and build number? That way the server could set browser caching to something drastic like 1 year, and it is guaranteed that pyodide-0.13.0.js will never change so that caching is not an issue. Users just then need to manually point to the pyodide js file that matches the version they want to use.

Another example of this in practice. Let's say numpy is at version 1.16.4. Its js and data files would look like numpy-1.16.4_0.js etc. And the respective pyodide-0.13.0.js would point to that specific numpy path. Let's say we don't upgrade the version of numpy, but the wasm build of numpy has been optimised or changed, that final build number allows us to bust the cache for that case. So pyodide-0.13.0.js would still point to numpy-1.16.4_0.js but pyodide-0.13.1.js would point to numpy-1.16.4_1.js (with the build number iterated).

Let me know your thoughts.

Cheers,
Simon

**Comment by mdboom** [comment]
I agree this is a great idea.

The reasons this isn't currently being done are mostly silly / secondary.  I'd like to find a way to host these in an "open source" way that wouldn't be tied to a corporate account, to make it easy to have outside collaborators.  Unfortunately, Pyodide pretty quickly hits up against the file size limits of Github Pages, free Netlify and things like that.  Having multiple versions would be even more so.

But I'd love to solve this problem if you have any thoughts or suggestions.

**Comment by SimonBiggs** [comment]
The only issue with GitHub pages at the moment I think is the size of scipy? There was an issue (https://github.com/iodide-project/pyodide/issues/240) that a believe proposes a solution to keep that file size down.

I think GitHub pages is a viable long term "open sourcey" solution. Potentially scipy's size is the only blocker?

**Comment by SimonBiggs** [comment]
Also, once you host on GitHub pages, set up the DNS with CloudFlare, and then within the CloudFlare panel you can set the caching to be 1 year. Which if once a file is up there, it never changes, will work perfectly :).

**Comment by SimonBiggs** [comment]
Actually instead of a build number, just take a hash of the file contents and append the hash to the end of the file. That way if the version hasn't changed you don't have to implement any logic to see if the build artefact has changed. Just pump out the artefact with a version now (for information purposes) and a hash. That way if it hasn't changed it will just align with an already existing file, if it has changed they'll sit next to each other in coexistence.

**Comment by rth** [comment]
Closing as versioned URLs were added in 0.15. Though there are still some open questions to make this work sustainably long term, particularly if the volume of downloads increases significantly https://github.com/iodide-project/pyodide/issues/651#issuecomment-631690264
