### ISSUE TITLE
pyiodide.iodide.io seems down

### ISSUE THREAD

**Issue by vadimkantorov** [iodide-project/pyodide#456]
While running a notebook from https://definitely-staging.iodide.io: `Python plugin failed to load: https://pyodide.iodide.io/pyodide.js not found`

https://downforeveryoneorjustme.com/pyodide.iodide.io confirms

**Comment by mdboom** [comment]
Note this is only on staging.

See https://github.com/iodide-project/iodide/pull/1896

Once that's merged and redeployed to staging, we should be golden again.

**Comment by mdboom** [comment]
Should be fixed now.  @vadimkantorov : Please reopen if not.
