### ISSUE TITLE
Use of Mozilla's logo in a talk

### ISSUE THREAD

**Issue by SimonBiggs** [iodide-project/pyodide#457]
Hi @mdboom,

I'm giving a talk in Montreal in a couple of weeks and I was hoping to feature Pyodide quite heavily. I couldn't find a logo for pyodide itself, so I figured I might use Mozilla's logo. Is that okay?

See the current draft of the slides at https://simonbiggs.net/iccr2019

**Comment by PythonLinks** [comment]
Your slides look really nice. 
They add a lot of credibility to the whole Pyodide project. 

So I added a link to them from 
https://pythonlinks.info/the-first-pyodide-application

I presume that you have now fixed the problem with the window freezing during processing. 
So I deleted that paragraph. 

One comment.  I still do not really know what your application does. 
A one sentence description for those not in your field would be very helpful. 

Keep up the great work.

**Comment by SimonBiggs** [comment]
I haven't fixed the freezing no. I can't use webworkers unfortunately. I can delegate the work to another tab though. Not sure if I'll have time to do that before the conference though.

**Comment by SimonBiggs** [comment]
Not sure how I feel about having the talk published as anything more than a draft before the talk actually occurs. Once my talk is done I'll look to it from the PyMedPhys docs. Maybe look to it then?

**Comment by SimonBiggs** [comment]
@PythonLinks so as not to clutter the pyodide issues let's move the app question conversation over to https://github.com/pymedphys/pymedphys/issues/374

**Comment by PythonLinks** [comment]
I deleted the link.

**Comment by mdboom** [comment]
@SimonBiggs: That's true -- Pyodide doesn't have a logo.  Someone with more artistic talent than I should create one ;)   

I am not a lawyer, but I think it's fine to use the Mozilla logo in order to give credit to those parts (as you do in your slides).

**Comment by SimonBiggs** [comment]
Kk, thanks for that.

**Comment by SimonBiggs** [comment]
> @SimonBiggs: That's true -- Pyodide doesn't have a logo. Someone with more artistic talent than I should create one ;)

I believe @richardbmx is usually pretty keen to get his name out there by designing logos for open source projects.

**Comment by richardbmx** [comment]
@SimonBiggs  If I like to make logos to open source projects doing logos for projects
