### ISSUE TITLE
matplotlib figure doesn't update when elements are changed

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#46]
It's somehow not triggering the call to `draw_idle` like it should...

**Comment by hamilton** [comment]
I'm noticing from https://github.com/iodide-project/iodide/pull/631 that this seems to still be an issue (specifically in `?ipynb=https://raw.githubusercontent.com/mdboom/strata-mpl-tutorial/master/Introduction to matplotlib.ipynb`)

**Comment by mdboom** [comment]
Yeah, I'm seeing this, too.  Reopening...

**Comment by mdboom** [comment]
Clearing the browser cache fixes it for me.  This whole caching problem is something we'll be able to fix more readily once we move to s3...
