### ISSUE TITLE
Update some doc links in Sphinx docs

### ISSUE THREAD

**Issue by willingc** [iodide-project/pyodide#478]
A few action items to polish on the Sphinx docs:

- [x] Add RTD badge to README
- [ ] Check some of the markdown link targets to GitHub which did not convert correctly with m2r. May need from swap m2r to recommonmark.
- [ ] Make the installation instructions more visible - right now they are being pulled in under Projects section and README

**Comment by rth** [comment]
> Check some of the markdown link targets to GitHub which did not convert correctly with m2r. May need from swap m2r to recommonmark.

We switched to https://github.com/executablebooks/MyST-Parser which is even better.

> Make the installation instructions more visible - right now they are being pulled in under Projects section and README

There have been a fair amount of documentation reorganization since and I think these point have been resolved. Thanks @willingc !
