### ISSUE TITLE
Demo does not run on Firefox mobile

### ISSUE THREAD

**Issue by encocan** [iodide-project/pyodide#490]
Hello

I tried running the demo in the latest Firefox for Android and also Firefox Focus for Android but the demo gets stuck at "Python plugin downloaded, initializing".

Is there any way to use this on mobile?

**Comment by rth** [comment]
Latest release works fine with Firefox mobile 84.1 as far as I can tell, including for loading packages (tried with numpy). Closing please comment if you still experience issues.

The mobile UI for `console.html` can certainly be improved https://github.com/iodide-project/pyodide/issues/1046
