### ISSUE TITLE
remove style loading code after iodide #2085 merges

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/pyodide#494]
we should remove [these lines](https://github.com/iodide-project/pyodide/blob/master/src/pyodide.js#L373) from Pyodide after https://github.com/iodide-project/iodide/pull/2085 is merged

_Originally posted by @mdboom in https://github.com/iodide-project/iodide/pull/2085#issuecomment-515623642_

**Comment by rth** [comment]
As far as I can tell, this was resolved since, we no longer have styling code.
