### ISSUE TITLE
Getting `TypeError: Module[prop] is undefined` when importing package

### ISSUE THREAD

**Issue by matham** [iodide-project/pyodide#507]
When running the following [notebook](https://alpha.iodide.io/notebooks/2883/) (run the full notebook), I get the following error:

```
TypeError: Module[prop] is undefined
get/env[prop]()@https://pyodide.cdn.iodide.io/pyodide.asm.js:8:9106
{anonymous}()@https://pyodide.cdn.iodide.io/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[214]:0xafb7
{anonymous}()@https://pyodide.cdn.iodide.io/pyodide.asm.js line 8 > WebAssembly.Module:wasm-function[1366]:0x5a15d
{anonymous}()@https://pyodide.cdn.iodide.io/pyodide.asm.wasm:wasm-function[2981]:0x359d92
...
```

I ran into the same issue when running the notebook in a local pyodide build. I grep'ed for `Module[prop]` and found it in the middle of `pyodide.asm.js` as `...Module["setThrew"](1,0)}}}return env[prop]=function(){return Module[prop].apply(null,arguments)}}};var info={global:{"NaN":NaN,Infinity:Infinity}...` So I manually edited it from `function(){return Module[prop].apply(null,arguments)}` -> `function(){}` and that made the issue go away locally. But of course I still have the same issue on https://alpha.iodide.io.

**Comment by matham** [comment]
Ok, I narrowed this down a bit to just Pillow.

The following simplified code results in the same issue:

```
%% py
import numpy as np

%%js
// Prep and load kivy/pillow from our custom github path
pyodide._module.packages.dependencies["Pillow"] = []
pyodide.loadPackage('https://cdn.jsdelivr.net/gh/matham/kivy@pyodide_serve/pyodide_js/Pillow.js')

%% py
import PIL
from PIL import Image
```

Specifically, it's the line `from PIL import Image` that causes it.

**Comment by matham** [comment]
I hit this in a different situation and looking through the code in emscripten likely responsible (https://github.com/emscripten-core/emscripten/blob/1.38.30/src/support.js#L406), I think this was fixed in 1.38.31 (https://github.com/emscripten-core/emscripten/pull/8431) because the only code that I could see being responsible for the error was replaced.

**Comment by inesani** [comment]
Hi @matham, I just ran into the same issue you describe here. I followed your advice and erased the function content and the error went away. Thank you so much for this patch, you saved me loads of time. Have you had the chance to get new insights on the problem?

**Comment by matham** [comment]
As I hinted in my last comment, I believe the ultimate cause is a bug in emscripten, which is likely fixed in a newer version than what is used by pyodide currently. But I'm not really sure as I have not reversed engineered the emscripten code to find the exact nature of the bug.

**Comment by matham** [comment]
There is a PR to update emscripten: https://github.com/iodide-project/pyodide/pull/480 but I guess it's not yet ready.

**Comment by matthew-brett** [comment]
I run into this error with the following notebook:

```
%% py
import scipy.stats as sps

%% py
sps.linregress([0, 1, 2, 3], [3, 3, 2, 5])
```

The error occurs on the second cell, not the first.  I guess this is something to do with some internal Scipy imports?

By the way - combining the two cells into one causes my CPU usage to go to 100% and my laptop to slow down dramatically, for a minute or so.

**Comment by rth** [comment]
> The error occurs on the second cell, not the first. I guess this is something to do with some internal Scipy imports?

Yes, scipy support is still very patchy, as we have to use f2c to compile Fortran for now among other things https://github.com/iodide-project/pyodide/issues/184 and some failing modules have their imports removed to avoid errors at import time.

>> I think this was fixed in 1.38.31 
>
> As I hinted in my last comment, I believe the ultimate cause is a bug in emscripten, 

Thanks for investigating! We are at 1.38.30 now and we really need to update at least to 1.38.35 https://github.com/iodide-project/pyodide/issues/476#issuecomment-633009818 where emscripten switched to their newer build system.

**Comment by rth** [comment]
Updating to emscripten 1.38.31 should have fixed this. Please comment if it's not the case.

For the particular case of `scipy.stats.linregress` there is a different error now, opened https://github.com/iodide-project/pyodide/issues/677

**Comment by matham** [comment]
Looks like I was wrong and that the error is still there. It's just that in 1.38.31 they re-arranged the code so the error is slightly different (#677).

**Comment by rth** [comment]
Thanks for checking @matham ! Let's continue this discussion in https://github.com/iodide-project/pyodide/issues/677 since the error message is different and users will probably end up there now.
