### ISSUE TITLE
Using webgl speed up numpy in pyodide?

### ISSUE THREAD

**Issue by linkerlin** [iodide-project/pyodide#511]
Is it possible?

**Comment by matham** [comment]
If you're talking about GPU computation, numpy doesn't currently have any GPU support afaik on any platform. I guess the question is whether e.g. pytorch can run in the browser. Pytorch (torch) is probably the closest to numpy syntax that I know.

`ONNX.js` supports GPU in the browser with webgl shaders, so you should already be able to do this by simply making the required js calls directly from pyodide. If you are after the numpy/pytorch syntax perhaps there's a way to compile the pytorch backend (`THNN`, I believe) to use webgl and compile it with emscripten? But it's not likely to be easy if no one has done that yet.

**Comment by rth** [comment]
Closing, since the comment above provides a detailed answers the question. I don't think the situation has changed much since.

>  Pytorch (torch) is probably the closest to numpy syntax that I know.

Maybe https://github.com/google/jax now as well. Anyway running existing scientific code with something else than numpy is not that easy even without involving WASM.

**Comment by JonathanSum** [comment]
@matham matham
@rth THus, I am asking. Does it support Pytorch? It said it includes the 75 package and allows to install python wheel. It looks like Pytorch does not have the wheel.

**Comment by rth** [comment]
> THus, I am asking. Does it support Pytorch? It said it includes the 75 package and allows to install python wheel.

Not currently. See https://stackoverflow.com/a/64407516/1791279
