### ISSUE TITLE
Adding a new Pyodide package: statsmodels

### ISSUE THREAD

**Issue by inesani** [iodide-project/pyodide#514]
Hi all, I am currently working with some statistical tests that are supplied by the **statsmodels** package. Although this package is not available from the prebuilt version of pyodide I would really appreciate some help on how to integrate it.

I have seen you provide a guide in here: https://github.com/iodide-project/pyodide/blob/master/docs/new_packages.md

The statsmodels package does have C/C++/Cython files and I am quite new to this. I suppose you have already done this process for packages like numpy and I am asking for some more info, scripts or help on how to do this step by step and obtain the .data and .js files.

I thank you in advance and I strongly wish i can keep working with pyodide :)

**Comment by rth** [comment]
The easiest is probably making a PR that adds `packages/statsmodels/meta.yaml` (see how that is done for other packages) and see if that builds sucessfully in CI. With luck it might work straight away: C/Cython/F77 extensions should be built automatically. If something doesn't work then you would need to add patches work around those issues...

You can also built it locally https://github.com/iodide-project/pyodide#getting-started that might be faster to iterate without rebuilding all pyodide from scratch.

**Comment by inesani** [comment]
I followed your advice and I built it locally.  No patches were needed and it was fairly simple.  I have my `.data` and  `.js` files now :) I believe that the Pull Request is failing on CI because of the importing in chrome test. I have manually added statsmodel to the `packages.json` file and it is working fine now on both Chrome and Firefox. Thank you for the help. I will chose the issue now.
