### ISSUE TITLE
Import Custom Python Chunk Format

### ISSUE THREAD

**Issue by Neuroforge** [iodide-project/pyodide#518]
Hello,

I've been reading the documentation in https://buildmedia.readthedocs.org/media/pdf/test-pyodide/sphinx/test-pyodide.pdf. 

When using pyodide from javascript and wanting load a package what is the format of the chunk? It appears to be a js file, but what should it contain? Raw python? Python wrapped with quotes and summated? 
```
" ...foo \n" +
 "...bar \n" +
```

This is the description from the docs.

```
However, if you want to use your own custom package or load a package from another provider, you’ll need to use the
pyodide.loadPackage function from a Javascript chunk. For example, to load a special distribution of Numpy
from custom.com:
%% js
pyodide.loadPackage('https://custom.com/numpy.js')
After doing that, the numpy you import from a Python chunk will be this special version of Numpy
```

**Comment by mdboom** [comment]
It needs to be a "Pyodide package" -- the format and how to build is described [here](https://github.com/iodide-project/pyodide/blob/master/docs/new_packages.md), though #498 will add the loading of individual Python files this way.

**Comment by rth** [comment]
Closing as resolved. Unless there are unanswered questions?
