### ISSUE TITLE
Contributing Packages

### ISSUE THREAD

**Issue by fallaciousreasoning** [iodide-project/pyodide#526]
I've got a few packages with C dependencies python that I'm interested in using to port an existing Python project to the web. I was wondering if you guys are interested in me cleaning them up and upstreaming them.

## [regex](https://pypi.org/project/regex/)
Pretty simple, it doesn't have any external dependencies, so it Just Worked<sup>TM</sup>.

Branch here: https://github.com/fallaciousreasoning/pyodide/tree/compile-python-regex

## [lxml](https://pypi.org/project/lxml/)
More complicated. Has a dependency on libxml and libxslt. This adds a not insignificant chunk of time to the initial build. Not sure how widely used this is or whether you'd be interested in it here.

Maybe we need some kind of opt-in for building dependencies, or a system like [emscripten-ports](https://emscripten.org/docs/compiling/Building-Projects.html#emscripten-ports)? It doesn't seem sustainable to add everything here.

Branch here: https://github.com/fallaciousreasoning/pyodide/tree/compile-python-lxml

**Note:** It's not finished yet, but I have the lxml package building /woot/. Also, I have no idea what I'm doing so there are (many) things I'm almost certainly doing the wrong way.

## [html5-parser](https://pypi.org/project/html5-parser/)
Depends on lxml, not started.

## [Pillow](https://pypi.org/project/Pillow/)
I initially started by trying to port this, but it seemed kind of complicated, so I started looking at the other packages to try and work up to it. Suspect that this will be the most interesting to Pyodide.

--------------------

Just wanted to end by saying you guys are doing some awesome stuff, keep up the good work!

**Comment by filips123** [comment]
@fallaciousreasoning Would you be able to also port [Cytoolz](https://github.com/pytoolz/cytoolz)?

> `cytoolz` supports Python 2.7+ and Python 3.4+ with a common codebase. It is developed in Cython, but requires no dependecies other than CPython and a C compiler. Like `toolz`, it is a light weight dependency.

**Comment by mdboom** [comment]
We're always interested in package additions.  Just file pull requests!

**Comment by fallaciousreasoning** [comment]
File #538 for [regex](https://pypi.org/project/regex/). I'll follow up with the others when I have time to clean them up a bit :)

@filips123 I can have a look at it but it might take me a while to get around to. If it doesn't have any external dependencies you can probably copy what I did in #538 for regex and it will Just Work<sup>TM</sup>.

I'm going to close this as @mdboom has answered my question.
