### ISSUE TITLE
should data club demo run-all?

### ISSUE THREAD

**Issue by bcolloran** [iodide-project/pyodide#53]
i know it was not really designed explicitly to work with run all (it's really meant as a cell-by-cell demo), but is the data club demo here:
https://iodide.io/pyodide-demo/data-club-demo-2018-05-29.html
an appropriate test case for async stuff?

**Comment by mdboom** [comment]
I think the only change necessary is to make the `loadPackage` calls use `evalQueue.await`.  Everything else should be synchronous.
