### ISSUE TITLE
pyodide seems to crash iOS browsers (safari and chrome)

### ISSUE THREAD

**Issue by shi-yan** [iodide-project/pyodide#533]
Initially I thought iOS browser doesn't support wasm.

My code to detect wasm support is the following:

```javascript
    let isWebassemblySupported = function()
    {
        if (typeof WebAssembly === "object" && typeof WebAssembly.instantiate === "function") 
        {
            return true;
        }
        return false;
    }
```

Surprisingly , it says wasm is supported by IOS browsers. But then pyodide would crash the browser.

**Comment by mdboom** [comment]
Yeah -- it's unlikely that an iOS device would have sufficient RAM for Pyodide.  We should probably detect iOS and fail gracefully with a better error message.

**Comment by rth** [comment]
> Yeah -- it's unlikely that an iOS device would have sufficient RAM for Pyodide. 

Memory requirements were reduced in https://github.com/iodide-project/pyodide/pull/600 so it should no longer be an issue. Closing, please comment if you still run into problems.

Remaining known issues with Safari specifically are https://github.com/iodide-project/pyodide/issues/524 and https://github.com/iodide-project/pyodide/issues/721

**Comment by drscotthawley** [comment]
@rth Newbie here. The problem I'm running into is that my page https://alpha.iodide.io/notebooks/6593/? will not load on any iOS browser, whether it's Safari, Chrome, or Brave.  Can't tell what the error is because my Desktop is Linux and AFAIK one needs the iOS device to a Mac to see Web Inspector, so not sure if it's from one of those other issues or this one.

**Comment by drscotthawley** [comment]
Update: Managed to connect my iOS device to my Mac and iodide makes the Web Inspector window on the Mac crash and disappear! Yikes. 

Given that debugging iOS browsers is only possible for Safari (not Chrome or Brave), and you have no plans to support Safari (as per #524 & #721 ), then it appears that using Pyodide with iOS is a no-go.

**Comment by rth** [comment]
> and you have no plans to support Safari

See https://github.com/iodide-project/pyodide/issues/721#issuecomment-738223668 . We just don't the resources to do it at the moment. However if someone would be interested in investigating the issues with Safari that would be great.

>  [Error] Blocked a frame with origin "https://alpha.iodide.io" from accessing a frame with origin "https://alpha.iodide.app". Protocols, domains, and ports must match.

That doesn't seem to be an issue with pyodide but rather [iodide](https://github.com/iodide-project/iodide).
