### ISSUE TITLE
WebAssembly idea

### ISSUE THREAD

**Issue by daxthenuke** [iodide-project/pyodide#534]
Maybe WebAssembly will work beter if made from this.
https://www.yattag.org/ 
It is frontend python library.
Im new so this is all i can do.

**Comment by Daniel-at-github** [comment]
Thanks for the contribution, looked into yattag, it's a web generation library but no luck with webassembly (not explicitly supported).
Can close this issue.

> Im new so this is all i can do.

Welcome to the python community then, you will have fun here.
