### ISSUE TITLE
How to expose pandas as j

### ISSUE THREAD

**Issue by davidpham87** [iodide-project/pyodide#542]
Hello, the project is really interesting.

I wondered if we could expose python packages as JS libraries? Something similar to tensorflow-js which expose `tfjs` and then handle conversion and all?

We desperately need pandas in the browser! Thanks!

**Comment by mdboom** [comment]
The docs about [using pyodide from javascript)[https://github.com/iodide-project/pyodide/blob/master/docs/using_pyodide_from_javascript.md] should help.  Let us know where you get stuck!

**Comment by davidpham87** [comment]
How would you exchange data from JavaScript to Python?

**Comment by mdboom** [comment]
This is described [here](https://github.com/iodide-project/pyodide/blob/master/docs/type_conversions.md)

**Comment by rth** [comment]
Closing, as all questions have been answered as far as I can tell. Please comment if it's not the case.
