### ISSUE TITLE
ImportError: cannot import name 'document' from 'js' 

### ISSUE THREAD

**Issue by ansoncsh** [iodide-project/pyodide#561]
Hi,

I create a simple HTML webpage to load the Pyodide web worker and I try to run this line.

<pre>from matplotlib import pyplot as plt</pre>

However, I get the following error. How to fix it?

<pre>Python exception:
Traceback (most recent call last):
   File "/lib/python3.7/site-packages/pyodide.py", line 42, in eval_code
     exec(compile(mod, '<exec>', mode='exec'), ns, ns)
   File "<exec>", line 3, in <module>
   File "/lib/python3.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
     _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
   File "/lib/python3.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
     [backend_name], 0)
   File "/lib/python3.7/site-packages/matplotlib/backends/wasm_backend.py", line 23, in <module>
     from js import document
ImportError: cannot import name 'document' from 'js' (unknown location)</pre>

**Comment by wlach** [comment]
Loading DOM stuff from a web worker is not currently supported, and probably will never be due to technical limitations of how web workers operate

https://pyodide.readthedocs.io/en/latest/using_pyodide_from_webworker.html#caveats

We could probably explain some of this better (PRs welcome!), but this is pretty much as designed.

**Comment by MarcSkovMadsen** [comment]
I just got this one as well when trying to use [panel convert]() with matplotlib https://panel.holoviz.org/user_guide/Running_in_Webassembly.html.

I tried deploying it from awesome-panel.org/sharing.

![image](https://user-images.githubusercontent.com/42288570/208315237-ec2cb197-5e23-49d7-8536-7d483f2d7a05.png)

**Comment by jim22k** [comment]
Note that you can still use matplotlib in a Pyodide web worker if you use a static backend.

```python
import matplotlib
matplotlib.use("AGG")
import matplotlib.pyplot as plt
```

You can build a chart, convert to PNG, and return that to the main thread.
