### ISSUE TITLE
Remove Dependency on libfreetype6-dev (during build)

### ISSUE THREAD

**Issue by sergio97** [iodide-project/pyodide#562]
## Issue
The dependency on libfreetype6-dev is probably a bug.  The build system tries really hard to not pull in headers from the system (since those may be different versions from the ones being used in emscripten), but it looks like it's leaking.

### Steps to Reproduce
```bash
sudo apt remove libfreetype6-dev
make
```

**Comment by rth** [comment]
> Steps to Reproduce

Do you mean you get errors without system libfreetype6-dev? 

The `libfreetype6` headers are necessary to build matplotlib on the host system. The log of this build is then used to build matplotlib with emscripten. Indeed, I'm not sure if the right freetype headers are used during this second build.

**Comment by wlach** [comment]
Just noticed this when trying to build on a fresh Mac system. I needed to run `brew install freetype` for matplotlib to build, otherwise I get this:

```
BUILDING MATPLOTLIB
            matplotlib: yes [2.2.3]
                python: yes [3.7.6 (default, Jan  3 2020, 13:00:27)  [Clang
                        11.0.0 (clang-1100.0.33.16)]]
              platform: yes [darwin]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.15.1]
      install_requires: yes [handled by setuptools]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                        could not be found.  You may need to install the
                        development package.]
                   png: no  [pkg-config information for 'libpng' could not
                        be found.]
                 qhull: yes [pkg-config information for 'libqhull' could not
                        be found. Using local copy.]
```

(it seems like `brew install freetype` brings libpng along for the ride)

**Comment by rth** [comment]
We are no longer requiring libfreetype6-dev for the build and using it from emscripten ports, so this as been resolved. Thanks!
