### ISSUE TITLE
Add xlrd module to pyodide

### ISSUE THREAD

**Issue by wlach** [iodide-project/pyodide#564]
For loading excel files from pandas, we need xlrd. We should add this package to pyodide, so people don't have install it via micropip (which works, but is a hassle and a roadblock)

**Comment by madhur-tandon** [comment]
I think we can close this since https://github.com/iodide-project/pyodide/pull/566 is merged now.

**Comment by wlach** [comment]
> I think we can close this since #566 is merged now.

Yup! Thanks for the prod
