### ISSUE TITLE
Icons on the header are misaligned

### ISSUE THREAD

**Issue by algomaster99** [iodide-project/pyodide#583]
Icons which run cells and notebooks and help are not exactly centre aligned.

![Screenshot from 2019-12-10 16-02-05](https://user-images.githubusercontent.com/35191225/70522289-d73dff00-1b66-11ea-8c21-0746b2b0c21c.png)

I think they can be fixed by adjusting the padding (removing `padding-top` and `padding-bottom` - works on my machine :smile: )

**Comment by SuyashSalampuria** [comment]
Has the issue been fixed. Because the most recent code gives me correct alignment
![Screenshot from 2020-01-02 18-46-02](https://user-images.githubusercontent.com/44131389/71668782-425aaa00-2d90-11ea-91c5-853b58b4950f.png)

**Comment by wlach** [comment]
This is actually an iodide issue, not a pyodide one -- it was fixed with iodide-project/iodide#2570
