### ISSUE TITLE
Compilation fails on Fedora 31

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#588]
Hello.
I have cloned pyodide from git and trying to compile following the instructions from README:
```
$ make
./tools/dependency-check.sh
make -C emsdk
make[1]: Entering directory '/home/hiisi/workspace/pyodide/emsdk'
if [ -d emsdk ]; then rm -rf emsdk; fi
git clone https://github.com/juj/emsdk.git
Cloning into 'emsdk'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 1787 (delta 22), reused 27 (delta 18), pack-reused 1749
Receiving objects: 100% (1787/1787), 1010.19 KiB | 4.01 MiB/s, done.
Resolving deltas: 100% (1129/1129), done.
sed -i -e "s#CPU_CORES = max(multiprocessing.cpu_count()-1, 1)#CPU_CORES = 3#g" emsdk/emsdk
( \
	cd emsdk && \
	./emsdk install --build=Release sdk-tag-1.38.30-64bit binaryen-tag-1.38.30-64bit && \
	cd .. && \
	(cat patches/*.patch | patch -p1) && \
	cd emsdk/binaryen/tag-1.38.30_64bit_binaryen/ && \
    make && \
  cd ../../.. && \
	cd emsdk/clang/tag-e1.38.30/build_tag-e1.38.30_64/ && \
    make && \
    cd ../../.. && \
	./emsdk activate --embedded --build=Release sdk-tag-1.38.30-64bit binaryen-tag-1.38.30-64bit && \
    touch .complete \
)
Error: No tool or SDK found by name 'sdk-tag-1.38.30-64bit'.
make[1]: *** [Makefile:13: emsdk/.complete] Error 1
make[1]: Leaving directory '/home/hiisi/workspace/pyodide/emsdk'
make: *** [Makefile:252: emsdk/emsdk/.complete] Error 2
```
All the dependencies installed but it fails installing emsdk. Is it emscripten bug or pyodide?

**Comment by AndyLockhart** [comment]
same to me
the result of './emsdk list'
```
All recent (non-legacy) installable versions are:
         1.39.4
         1.39.3
         1.39.2
         1.39.1
         1.39.0
         1.38.48
         1.38.47
         1.38.46
         1.38.45
         1.38.44
         1.38.43
         1.38.42
         1.38.41
         1.38.40
         1.38.39
         1.38.38
         1.38.37
         1.38.36
         1.38.35
         1.38.34
         1.38.33
```
emsdk 1.38.30 has been deprecated?

**Comment by AndyLockhart** [comment]
try replace 'sdk-tag-' to 'sdk-fastcomp-tag-' at emsdk/Makefile, 'sdk-fastcomp-tag-1.38.30-64bit' is available in emsdk list

**Comment by Hiisi5** [comment]
> try replace 'sdk-tag-' to 'sdk-fastcomp-tag-' at emsdk/Makefile, 'sdk-fastcomp-tag-1.38.30-64bit' is available in emsdk list

Thank you, that actually worked. I guess it is a recent major update of emscripten.

**Comment by nathanross** [comment]
![patchFailure](https://user-images.githubusercontent.com/6265059/71552135-7286ff00-29c4-11ea-8835-0eaa3843a068.png)

I tried that workaround and it compiled for about three hours then got the error in my image above right at the end.

My assumption is this workaround isn't quite enough. Either that or I'm doing something wrong. I'm in a fresh virtualbox VM install of lubuntu with all the dependencies afaik, i'm just making the change above and then running make, so, not a lot special.

**Comment by aseering** [comment]
@AndyLockhart here's a PR with your suggested change.  I had to make a few more (related) changes to get it to build:
https://github.com/iodide-project/pyodide/pull/589

**Comment by wlach** [comment]
This should be fixed now
