### ISSUE TITLE
numpy fails to import

### ISSUE THREAD

**Issue by gabrielfreire** [iodide-project/pyodide#59]
I can't import numpy, has anyone ever had this problem? am i doing anything wrong?
Browser: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
My code
```javascript

languagePluginLoader.then(() => {
    // pyodide is now ready to use...
   pyodide.loadPackage('numpy').then(() => {
        pyodide.runPython('import numpy as np');
       
  });
});
```

the error
```console
Error: Traceback (most recent call last):
  File "/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: Could not evaluate dynamic lib: /lib/python3.6/site-packages/numpy/core/multiarray.so
RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: Could not evaluate dynamic lib: /lib/python3.6/site-packages/numpy/core/multiarray.so
RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.


    at _hiwire_throw_error (https://iodide.io/pyodide-demo/pyodide.asm.js:4:34764)
    at wasm-function[330]:1321
    at wasm-function[333]:621
    at Object.Module.__runPython (https://iodide.io/pyodide-demo/pyodide.asm.js:4:1853747)
    at Object.Module.runPython (https://iodide.io/pyodide-demo/pyodide.asm.js:4:37861)
    at t (https://iodide.io/dist/iodide.pyodide-20180605.js:12:191465)
    at https://iodide.io/dist/iodide.pyodide-20180605.js:110:12423
    at dispatch (https://iodide.io/dist/iodide.pyodide-20180605.js:46:27803)
    at code.cellType.p.then (https://iodide.io/dist/iodide.pyodide-20180605.js:12:191240)
```

**Comment by mdboom** [comment]
This looks like the Chrome-incompatibility issue in #22 and #55 which was just merged and deployed a few hours ago.  Would you mind clearing your browser cache, trying again and reporting back?

**Comment by gabrielfreire** [comment]
Hi @mdboom, thank you for your response, everything is working as expected.

I have a question tho.
Is it possible for me to load any python package i want ? is there a place where i can learn how to generate those package files (**numpy.data/numpy.js**) ?

**Comment by mdboom** [comment]
See docs/new_packages.md for info on building new packages.  Pure python tends to be pretty straightforward, but things with C or Cython extensions can be trickier.

**Comment by gabrielfreire** [comment]
Calling `pyodide.runPython` multiple times doesn't seem to be the problem
i tried this

```javascript
let pythonCode = (audioBuffer, step, wind, sampleRate) => { 
    return `w = ${wind}
step = ${step}
max_freq = 8000
eps = 1e-14
sample_rate = ${sampleRate}
samples = np.array([${audioBuffer.toString()}])
assert not np.iscomplexobj(samples)
hop_length = int(0.001 * step * sample_rate)
fft_length = int(0.001 * w * sample_rate)
window = np.hanning(fft_length)
window_norm = np.sum(window ** 2)
scale = window_norm * sample_rate
trunc = (len(samples) - fft_length) % hop_length
x = samples[:len(samples) - trunc]
nshape = (fft_length, (len(x) - fft_length) // hop_length + 1)
nstrides = (x.strides[0], x.strides[0] * hop_length)
x = as_strided(x, shape=nshape, strides=nstrides)
x = np.fft.rfft(x, axis=0)
x = np.absolute(x)**2
x[1:-1, :] *= (2.0 / scale)
x[(0, -1), :] /= scale
freqs = float(sample_rate) / fft_length * np.arange(x.shape[0])
ind = np.where(freqs <= max_freq)[0][-1] + 1
result = np.transpose(np.log(x[:ind, :] + eps))
    `
};

function _spectrogramFromAudioBuffer (audioBuffer, step, wind, sampleRate) {
    py(pythonCode(audioBuffer, step, wind, sampleRate));
    let x = py('x');
    let freqs = py('freqs');
    let spectrogram = py('result');
    return { x: x, freqs: freqs, spectrogram: spectrogram };
}
```

i got almost the same speed, sometimes faster **(1,002s**) was the fastest

**Comment by mdboom** [comment]
Thanks for your patience with the rough edges on this very new project.

I'm not surprised to hear that Chrome is slower than Firefox -- that's been my experience thus far.  It also is less memory efficient since at the moment we are force to load all dynamic libraries whether they are used or not in Chrome.  Plus, we just got it working at all yesterday :)

But, in general, a slowdown of 5x is not outside the range I've seen in my own benchmarking.  See http://droettboom.com/blog/2018/04/11/profiling-webassembly/

That said, there are a few places here that might help (though it's hard to say by how much without measuring):

- Create a function in Python, import that to Javascript (using `pyodide.pyimport(...)`) and just call it.  That will prevent the need to parse the Python each time.
- This code is converting the audioBuffer array to a string and back when it's passed from Javascript to Python.  Creating a Python function and calling it should convert the buffer in a much more efficient way.  Going even further, you could place the audioBuffer on the C/wasm heap and then just create the Numpy array to point at that, avoiding the copy altogether.  I keep meaning to create some helper functions for that, but haven't got to it yet.  Are you able to share your work thus far (including the Javascript side) so I could use it as a starting point?

**Comment by gabrielfreire** [comment]
I really loved your tips, it really sounds like it could run much faster doing this way but i ran into some problems
i've made this experiment with a function
```javascript
let spectrogram = () => { 
    return `def spectrogram(audioBuffer, step, wind, sampleRate):
    w = wind
    step = step
    max_freq = 8000
    eps = 1e-14
    sample_rate = sampleRate
    # samples = np.array(audioBuffer)
    
    return audioBuffer`
}
py(spectrogram());
```
But when i pass my audioBuffer `Float32Array(46908)` it becomes a bigger and different array of type `Uint8ClampedArray(187632)`
see code below:
```javascript
function _spectrogramFromAudioBuffer (audioBuffer, step, wind, sampleRate) {
    let spec = pyodide.pyimport('spectrogram');
    let spectrogram = spec(audioBuffer, step, wind, sampleRate);
    console.log(spectrogram) // Uint8ClampedArray(187632)
    return { spectrogram: spectrogram };
}
```
i think that doing this way i lost the ability to parse whatever i need from the C method _runpython and can't pass my array back and forth the way i used to, maybe there is some hacky way? i tried to pass a `Buffer` to `.decode()` in python and `json.loads()` but then i noticed i wasn't in nodeJS and would need to install some extra stuff `Buffer is undefined`

--- _"you could place the audioBuffer on the C/wasm heap"_ 
this sounds like Japanese to me but i'll google 
 and try to learn how to do this thing.

--- _"Are you able to share your work thus far (including the Javascript side) so I could use it as a starting point?"_ 
yes of course, i'll just try to organize the code a little better because right now it looks like a war, i'm just experimenting a lot of things out, as soon as it looks more presentable i'll put it on github and let you know.

**Comment by mdboom** [comment]
When you pass an array from Javascript to Python, it becomes a raw memory pointer, represented as a `Uint8ClampedArray`.  To get the type back, you need to use `np.frombuffer` (which initializes a numpy array from existing memory), rather than `np.array`, which would interpret each byte as an array element.  So try:

```
np.frombuffer(buffer, dtype=float32)
```

(This is the sort of low-level detail that we need to hide inside a helper library at some point -- that just doesn't exist yet...)

**Comment by gabrielfreire** [comment]
Great tip, thanks! god bless numpy
i got between 0.1s to 0.5s, **AWESOME!** 

that's my class so far, i'm still having some problems with the spectrogram now, getting some Null values on the array, but this is probably some 
```javascript
const py = (code) => {
    return pyodide.runPython(code);
}
class AudioGenerator {
    constructor() {
        this.context = new AudioContext();
        this.numpyLoaded = false;
        this.cache = {};
        pyodide.loadPackage('numpy').then(() => {
            py(`import json\nimport numpy as np\nfrom numpy.lib.stride_tricks import as_strided`);
            py(this._spectrogram());
            this.pySpectrogram = pyodide.pyimport('spectrogram');
            this.numpyLoaded = true;
            console.log('numpy loaded');
        });
    }
    _soundFile(filePath) {
        return new Promise((resolve, reject) => {
            console.info('_soundFile()');
            const request = new XMLHttpRequest();
            request.open('GET', filePath, true);
            request.responseType = 'arraybuffer';
            request.onreadystatechange = function(event) {
              if (request.readyState == 4) {
                if (request.status == 200 || request.status == 0) {
                  resolve(request.response); 
                } else {
                  reject({error: '404 Not found'});
                }
              }
            };
            request.send(null);
          });
    }
    _spectrogram () {
        return `def spectrogram(audioBuffer, step, wind, sampleRate):
        w = wind
        step = step
        max_freq = 8000
        eps = 1e-14
        sample_rate = sampleRate
        samples = np.frombuffer(audioBuffer, dtype='float32')
        assert not np.iscomplexobj(samples)
        hop_length = int(0.001 * step * sample_rate)
        fft_length = int(0.001 * w * sample_rate)
        window = np.hanning(fft_length)
        window_norm = np.sum(window ** 2)
        scale = window_norm * sample_rate
        trunc = (len(samples) - fft_length) % hop_length
        x = samples[:len(samples) - trunc]
        nshape = (fft_length, (len(x) - fft_length) // hop_length + 1)
        nstrides = (x.strides[0], x.strides[0] * hop_length)
        x = as_strided(x, shape=nshape, strides=nstrides)
        x = np.fft.rfft(x, axis=0)
        x = np.absolute(x)**2
        x[1:-1, :] *= (2.0 / scale)
        x[(0, -1), :] /= scale
        freqs = float(sample_rate) / fft_length * np.arange(x.shape[0])
        ind = np.where(freqs <= max_freq)[0][-1] + 1
        result = np.transpose(np.log(x[:ind, :] + eps))
        return result`
    }

    // http://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html
    _spectrogramFromAudioBuffer (audioBuffer, step, wind, sampleRate) {
        let spectrogram = this.pySpectrogram(audioBuffer, step, wind, sampleRate);
        return { spectrogram: spectrogram };
    }
    spectrogramFromFile (filePath, step, wind, sampleRate) {
        const self = this;
        let spec = null;
        return new Promise((resolve, reject) => {
            if(!this.cache[filePath]){
                this._soundFile(filePath).then((arrayBuffer) => {
                    this.context.decodeAudioData(arrayBuffer, (audioBuffer) => {
                        let buffer = audioBuffer.getChannelData(0);
                        this.cache[filePath] = buffer;
                        if(!this.numpyLoaded) reject({ message: "Numpy was not loaded yet, try again in a few seconds" });
                        spec = this._spectrogramFromAudioBuffer(buffer, step, wind, sampleRate);
                        console.log(spec);
                        resolve(spec);
                    });
                });
            } else {
                spec = this._spectrogramFromAudioBuffer(self.cache[filePath], step, wind, sampleRate);
                console.log(spec);
                resolve(spec);
            }
        });
    }
}
```

the language is being initialized on the index.html
```javascript
languagePluginLoader.then(() => {
   console.warn('Python initialized');
   let audioGen = new AudioGenerator();
   // ..... mess and more mess
});
```

Any tips are welcome, this library/webassembly is awesome, thanks

**Comment by gabrielfreire** [comment]
hi @mdboom 
`np.frombuffer(audioBuffer, dtype=float32)` returns the right audiobuffer but with a lot of nan values, would you know why is that?

**Comment by mdboom** [comment]
I'm not sure why there'd be a lot of NaNs, except if there were a data type mismatch here.  Are they there on the Javascript side before sending to Python?  Maybe try printing the first few values from Javascript and then from Python to make sure they match.  You're a bit in uncharted territory here, but it's helpful to hear about what you're doing.

**Comment by gabrielfreire** [comment]
Hey @mdboom , i'm using `np.nan_to_num()`  on my buffer, the NaNs are only on the python side after `np.frombuffer()`, javascript side looks ok.

I'm experimenting inside a small machine learning i implemented in javascript, so i created a new branch for my experimentations
https://github.com/gabrielfreire/neuralnet.js/tree/more_experimentation
you can take a look if you wish, all the client code is inside `www/`
if you wish to run the code, follow these steps:
`npm install` after cloning
`npm run tsc`  don't mind the errors/warning from typescript
`npm run start`
index.html will be available on `localhost:5000` with a button called `Generate Spectogram` that when pressed will run the python code using `www/data/example.wav`
python is loaded on `www/index.html` and the python code is all inside `www/lib/AudioGenerator.js`

**Comment by gabrielfreire** [comment]
I've tried to pass the buffer to python in some other ways and i found a good solution, not the fastest but the best i could so far, i'll list below what i've tried.

1 - i tried to figure out what was going on with `np.frombuffer()`, why was it returning so many nulls and wrong values when compared with the runPython parser `pyodide.runPython('np.array(${audioBuffer.toString()})')` which was returning the right values, the same as in native python. i couldn't find any reason and didn't manage to fix

2 - i tried to use this approad
```javascript
this.pySpectrogram(audioBuffer.toString(), step, wind, sampleRate)
```
```python
import ast
def spectrogram(audioBuffer, step, wind, sample_rate):
     max_freq = 8000
     eps = 1e-14
     samples = ast.literal_eval('[{}]'.format(audioBuffer))
```
It worked, but the whole process was taking between **2.5s** and **3s**, not good at all.

3 - I finally found a good solution, not as fast as using `np.frombuffer()` **(0.02s to 0.07s)** _(maybe because it wasn't converting the right way?)_, but it returns me all the right values and the whole process takes between **0.1s** to **0.7s** which is acceptable:
what i'm doing is, pass the audioBuffer to python as a string `audioBuffer.toString()`
in python
```python
samples = np.fromstring(audioBuffer, dtype='float32', sep=',')
```
this is the best solution i got so far to pass a float32array to a python method using `pyodide.pyimport` without the need to directly parse my variables with `pyodide.runPython`

I hope this is helpful.

Thanks

**Comment by mdboom** [comment]
I think you're running into a bug in how typed arrays are going from javascript to Python.  I'm looking into it now and will get back.

**Comment by mdboom** [comment]
I think you're running into a bug in how typed arrays are going from javascript to Python.  I'm looking into it now and will get back.

**Comment by mdboom** [comment]
See #63 for a fix.  Once this makes it through testing, I'll deploy and you should be good to go.  I made the following changes to your code to make this work:

```diff
diff --git a/www/lib/AudioGenerator.js b/www/lib/AudioGenerator.js
index f001d6c..504066f 100644
--- a/www/lib/AudioGenerator.js
+++ b/www/lib/AudioGenerator.js
@@ -39,8 +39,7 @@ class AudioGenerator {
         return `def spectrogram(audioBuffer, step, wind, sample_rate):
         max_freq = 8000
         eps = 1e-14
-        samples = np.fromstring(audioBuffer, dtype='float32', sep=',')
-
+        samples = np.frombuffer(audioBuffer, dtype='float32')
         assert not np.iscomplexobj(samples), "Must not pass in complex numbers"
 
         hop_length = int(0.001 * step * sample_rate)
@@ -69,8 +68,7 @@ class AudioGenerator {
 
     // http://haythamfayek.com/2016/04/21/speech-processing-for-machine-learning.html
     _spectrogramFromAudioBuffer (audioBuffer, step, wind, sampleRate) {
-        let buff = audioBuffer.toString();
-        let spectrogram = this.pySpectrogram(buff, step, wind, sampleRate);
+        let spectrogram = this.pySpectrogram(audioBuffer, step, wind, sampleRate);
         return { spectrogram: spectrogram };
     }
     spectrogramFromFile (filePath, step, wind) {
```

**Comment by gabrielfreire** [comment]
Nice, thanks for your help. looking forward to this deploy

**Comment by gabrielfreire** [comment]
i created a notebook that could be useful as an example for future users
https://github.com/gabrielfreire/neuralnet.js/blob/more_experimentation/spectrogram-feature-extraction.html

**Comment by mdboom** [comment]
Cool notebook.   If you're using Iodide like that, you can just put Python in a Python cell -- no need to use `runPython` at all! :)  When you're ready, we'd love to have a pull request over at https://github.com/iodide-project/iodide-examples where we are collecting a bunch of cool iodide examples like this.

**Comment by mdboom** [comment]
The fix in #64 is now merged and deployed.  You may need to clear your browser cache to take advantage of it.

**Comment by gabrielfreire** [comment]
cool, thanks.

Yes i wanted to focus on a javascript only project that makes use of python code on that notebook, you already have example notebooks with python cells, but it's confusing if an user(me) wants to write a full WebApp using python on the client i guess

**Comment by mdboom** [comment]
Have you played with using the Web Audio API to collect audio from the microphone and do real-time spectral analysis?  It seems this might be fast enough, and would make a really cool demo... :)

**Comment by gabrielfreire** [comment]
Hi @mdboom , yes i've played but i was sending the recorded blob to a nodejs server connected with python through zeroMQ and getting the spectrogram back to the client, 

this spectrogram is useful for neural network inference on a speech recognition model that was trained using spectrogram features, doing it this way is VERY fast, don't get me wrong, but if i could do everything on the client (offline), would be AWESOME to not depend on connection.

That's how i got here, i was looking for a way to use python/numpy/pandas on the client and make fast data transformations without the need for open internet connection which is a big use case for hospitals for example.

Maybe i could do all of this using javascript, probably with numjs, but i just like python too much for this kind of task, maybe i'm not doing the right thing on trying to use python on the client for this but with this WebAssembly hype i had to try.

A great win would be to decrease the start download/loading size and increase the start speed.

**Comment by gabrielfreire** [comment]
Done!
https://github.com/gabrielfreire/neuralnet.js/blob/more_experimentation/spectrogram-feature-extraction.html
