### ISSUE TITLE
run_docker fails with "cpuset.cpus.effective: no such file or directory"

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#592]
Hello.
I have compiled the latest pyodide on Fedora 31 (see issue #588 on how was it). The compilation process runs successfully. However, when I try to run docker I'm getting the following output:
```
$ ./run_docker 
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"open /sys/fs/cgroup/docker/cpuset.cpus.effective: no such file or directory\"": unknown.
```
Indeed, there's no such file:
```
$ ls /sys/fs/cgroup/docker/
cgroup.controllers  cgroup.max.descendants  cgroup.threads  cpu.stat         io.latency   memory.current       memory.low        memory.pressure      memory.swap.max
cgroup.events       cgroup.procs            cgroup.type     cpu.weight       io.max       memory.events        memory.max        memory.stat          pids.current
cgroup.freeze       cgroup.stat             cpu.max         cpu.weight.nice  io.pressure  memory.events.local  memory.min        memory.swap.current  pids.events
cgroup.max.depth    cgroup.subtree_control  cpu.pressure    io.bfq.weight    io.stat      memory.high          memory.oom.group  memory.swap.events   pids.max
```
I was able to run the precompiled binary on this same system with no issues. Still I would like this to be resolved.
Thanks for the great job you are doing and a happy new year!

**Comment by wlach** [comment]
@Hiisi5 this is almost certainly an issue with your docker installation / linux distribution, rather than pyodide. I'd try googling these errors and see what you come up with!

**Comment by wlach** [comment]
(I'm going to close for now, but feel free to re-open if it turns out I'm wrong)

**Comment by Hiisi5** [comment]
You are right!
[https://medium.com/nttlabs/cgroup-v2-596d035be4d7](https://medium.com/nttlabs/cgroup-v2-596d035be4d7)
