### ISSUE TITLE
Would it be feasible to use numba inside pyodide or make something similar?

### ISSUE THREAD

**Issue by neilwongtinpo** [iodide-project/pyodide#599]
The user's python script running in pyodide is still interpreted instead of compiled. The speed is extremely slow when running for loops of millions times. 
In desktop's python I use numba to just-in-time compile a specific loop-intensive function.
Would it be feasible to implement numba package for pyodide or native support of compiling user's code with a decorator similar to numba.njit?

**Comment by rth** [comment]
> Would it be feasible to implement numba package for pyodide or native support of compiling user's code with a decorator similar to numba.njit?

I would say it would be fairly difficult (if at all possible) to support numba, but then I haven't studied this question much. Closing as duplicate of https://github.com/iodide-project/pyodide/issues/621 to avoid parallel discussions.
