### ISSUE TITLE
importation order matters for js libs / python

### ISSUE THREAD

**Issue by hamilton** [iodide-project/pyodide#6]
I wanted to attempt to run d3 in python, just to see if it was as easy as I was expecting. If I import d3 after I import python, I get the following error:

<img width="1346" alt="screen shot 2018-02-23 at 2 58 16 pm" src="https://user-images.githubusercontent.com/95735/36626768-7a08d88c-18ed-11e8-9576-d2985f8a5199.png">

If I import d3 first (so it's in the global namespace) then python, the error does not occur.

Not sure if this is something to be filed in this repo or the other, but figured I'd put it here, since I believe pyodide grabs onto the js namespace. I'm also not sure if it is technically a bug - just wanted to put down some documentation that this is a thing.

**Comment by mdboom** [comment]
We should try again after #4 is implemented.  Moving to WASM necessarily changes how the resources are loaded, and that may have an impact on this.

**Comment by mdboom** [comment]
I think this is no longer a live issue.  A lot has changed about initialization of the WASM since then.  I'm going to close, but we should reopen any other issues we find related to interop with JS libraries.
