### ISSUE TITLE
Allow for selectively building packages

### ISSUE THREAD

**Issue by eulertour** [iodide-project/pyodide#605]
The [build instructions](https://github.com/iodide-project/pyodide#building-from-source) only specify how to build pyodide together with all of the packages it includes by default. As a result you have to build all of the packages even if you only intend to use a single one, or if you only intend to build a custom package without using any of the default ones.

Would it be difficult to add a way to only build the packages you intend to use?

**Comment by rth** [comment]
Yes, support for selectively building packages was recently added in https://pyodide.readthedocs.io/en/latest/building_from_sources.html#partial-builds
