### ISSUE TITLE
Compiling a package with libraries

### ISSUE THREAD

**Issue by Epse** [iodide-project/pyodide#614]
Is there a recommended way to compile a new package that uses external libraries that are not provided by emscripten or the ports (such as glib)?

I suppose I could compile these to bitcode separately and then pass a linker flag in the `meta.yaml` to link that along, but that seems like a hack.

**Comment by rth** [comment]
Yes, so far we are packaging them with a separate makefile e.g. in https://github.com/iodide-project/pyodide/tree/master/packages/zlib then linking from the python package that require it. This could evolve in the future with https://github.com/iodide-project/pyodide/issues/713 though.
