### ISSUE TITLE
Compared to pypy.js

### ISSUE THREAD

**Issue by arasouli91** [iodide-project/pyodide#62]
Would anyone happen to know about pypy.js and be able to compare pyodide and pypy.js? Which is a more complete, functioning implementation of Python?

At least Pyodide is alive, unlike pypy.js, but I want to know as of now which is more complete. And, if pypy.js is more complete, how quick is Pyodide coming up to speed, and, unassumingly, surpassing pypy.js?

**Comment by gabrielfreire** [comment]
IMHO, i think that pyodide is a more complete project in terms of what you can do and from what i can tell from the commits is alive.

You can use **numpy, matplotlib, dateutil, pytz and pandas** out of the box.
you can add your own packages: https://github.com/iodide-project/pyodide/blob/master/docs/new_packages.md

you can play with it on a notebook: https://github.com/iodide-project/pyodide/blob/master/docs/using_pyodide_from_javascript.md

The start download is smaller than on pypy.js and the tech stack is more modern, **Pypy.js uses asm.js** if i'm not mistaken, **Pyodide uses WebAssembly** which is faster

**Comment by jedie** [comment]
> The start download is smaller than on pypy.js

Yes, the biggest Problem with pypyjs is the large download size. e.g.: https://github.com/pypyjs/pypyjs/issues/196

I'd like to know how small we can get python as WebAssembly... Only the minimal requirements to get python core running and interact with the DOM tree...

**Comment by mdboom** [comment]
A lot of the differences also come from the basis on CPython vs. PyPy.  PyPy.js will be able to JIT "all the way down" to Python, whereas Pyodide is only able to optimize Python as well as CPython can.  For many applications that make heavy use of Numpy anyway, the performnce differences are likely small, and the advantages of using the "standard" Python stack outweigh the benefits of JIT'ting Python.

**Comment by arasouli91** [comment]
From what I am understanding they are both mostly complete ports of their respective implementations of Python. And, Cpython and PyPy their own pros and cons.

**Comment by arasouli91** [comment]
I suppose that was a sufficient amount of information for me, thanks all.
