### ISSUE TITLE
from collections.abc import MutableMapping supported?

### ISSUE THREAD

**Issue by despiegk** [iodide-project/pyodide#620]
```python
%% py
from collections.abc import MutableMapping

class JSDict(MutableMapping):
    def __init__(self, data=(), name=None, prefix=None):
        self._name = name
d=JSDict()
```

**Comment by rth** [comment]
Thanks for the report. For the record the error is,
```
TypeError: Can't instantiate abstract class JSDict with abstract methods
__delitem__, __getitem__, __iter__, __len__, __setitem__
```
but I also get the same error with CPython outside of pyodide.

MutableMapping is an abstact class that requires to implement those methods, which is not the case in the above example https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes

 So the error is expected, closing. Please comment if you disagree.
