### ISSUE TITLE
error: Unknown CPU, please report this to numpy maintainers with information about your platform (OS, CPU and compiler)

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#639]
Hello. Trying to play with pyodide a little bit I have cloned a git image of git. After executing ./run_docker script I run make and the compilation fails with the following error:
error: Unknown CPU, please report this to numpy maintainers with information about your platform (OS, CPU and compiler)
How do I fix it? The operating system is Ubuntu 18.04.4 LTS
Here's the output from lshw:

> lshw -C processor
> WARNING: you should run this program as super-user.
>   *-cpu:0                   
>        product: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
>        vendor: Intel Corp.
>        physical id: 1
>        bus info: cpu@0
>        size: 1197MHz
>        capacity: 3300MHz
>        width: 64 bits
>        capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d cpufreq
>   *-cpu:1
>        product: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
>        vendor: Intel Corp.
>        physical id: 2
>        bus info: cpu@1
>        size: 1197MHz
>        capacity: 3300MHz
>        width: 64 bits
>        capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d cpufreq
>

**Comment by jcaesar** [comment]
Your actual hardware and your distribution are probably irrelevant to this problem. Could you make sure that `iodide/pyodide-env:0.3.1` is running in `docker ps`? Running `git clean -dfx .` and `git checkout .` and retrying the `make` may also be prudent. Lastly, could you attach the build log as a test file here?

Note: I'm not a maintainer nor very experienced with this project. Just nosy.

**Comment by Hiisi5** [comment]
> Your actual hardware and your distribution are probably irrelevant to this problem as make is executed in docker and the target "hardware" is wasm. Could you make sure that `iodide/pyodide-env:0.3.1` is running in `docker ps`? Running `git clean -dfx .` and `git checkout .` and retrying the `make` may also be prudent. Lastly, could you attach the build log as a test file here?
> 
> Note: I'm not a maintainer nor very experienced with this project. Just nosy.

Thank you! git clean resolved the issue.
