### ISSUE TITLE
Getting error while running Pyodide in local

### ISSUE THREAD

**Issue by BhavikaSehgal888** [iodide-project/pyodide#640]
I have created index.html file (please find below). I have downloaded latest Pyodide.js file.
I don't know how to use it or how to specify the path of pyodide in local.
I am getting following error while running pyodide file in local.

**Failed to load resource: net::ERR_FILE_NOT_FOUND                   pyodide.js:1 
index.html:14 Uncaught ReferenceError: languagePluginLoader is not defined
 at index.html:14**

index.html
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript">
// set the pyodide files URL (packages.json, pyodide.asm.data etc)
window.languagePluginUrl = 'https://github.com/iodide-project/pyodide/blob/master/src/pyodide.js';
</script>
<script src="pyodide.js"></script>
</head>
<body>
Pyodide test page <br>
Open your browser console to see pyodide output
<script type="text/javascript">
languagePluginLoader.then(function () {
console.log(pyodide.runPython('import sys\nsys.version'));
console.log(pyodide.runPython('print(1 + 2)'));
});
</script>
</body>

**Comment by rth** [comment]
> I don't know how to use it or how to specify the path of pyodide in local.

You need to start a webserver locally to serve these files with correct MIME types, see https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html#complete-example for more details.
