### ISSUE TITLE
Release 0.15.0

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#644]
There have been a few improvements on master since 0.14.3 last December and it would be nice to make a new release with it. Since we changed CPython version 3.7.0 to 3.7.4 we can increment the minor version to 0.15.0 (or otherwise make it 0.14.4). 

@mdboom To make a new release is 
 - updating the [changelog](https://github.com/iodide-project/pyodide/blob/master/CHANGELOG.md)
 - creating a tag on master to deploy to netlify
 - updating `__version__` in `src/pyodide.py`

sufficient? Or are there other manual steps I missed? 

WDYT about making this release in general?

**Comment by mdboom** [comment]
LGTM.  I think those steps are correct.

**Comment by rth** [comment]
Version 0.15 is released, see release notes in https://pyodide.readthedocs.io/en/latest/changelog.html#version-0-15-0
