### ISSUE TITLE
pyodide.cdn.iodide.io is quite slow

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#651]
The current hosting of packages is at https://pyodide.cdn.iodide.io seems to capped at ~600kB/s¹ which means that 15MB of pandas takes 25s to download. That's a very long time. 

```
curl -X GET https://pyodide.cdn.iodide.io/pandas.data -o out.whl 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.8M  100 14.8M    0     0   564k      0  0:00:26  0:00:26 --:--:--  602k
```

The hostname  pyodide.cdn.iodide.io  maps via a CNAME entry to `pyodide.netlify.com.`, so it sounds like the limitation is Netlify's end. Could it be because we have used the allotted 100GB of traffic per month or is it just their default limitation for free accounts?

¹at least for me in France with a 60+ MB/s wired connection

**Edit:** I also get similar speeds in a browser in case they are filtering by User-Agent.

**Comment by wlach** [comment]
We've talked about moving away from netlify a few times; I think we're probably outside their intended use case. I think a better approach would be a GCS/S3/whatever bucket fronted by cloudflare or similar, this would also make it easier to serve legacy versions of pyodide. Unfortunately I don't think I can commit the time or resources to set this up from Mozilla's end, but it should be relatively inexpensive to host once it's up.

**Comment by rth** [comment]
Yeah, we are probably an atypical use case for Netlify. 

Here is an S3 bucket + cloudflare with the latest pyodide release at `https://pyodide.r0h.eu/0.14.3/`

The download speed is indeed a factor of 10 faster,
```
 curl -X GET https://pyodide.r0h.eu/0.14.3/pandas.data -o out.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.8M  100 14.8M    0     0  8411k      0  0:00:01  0:00:01 --:--:-- 8406k
```
the only thing is that caching related headers need to be manually configured. I can share API keys to this bucket with all pyodide maintainers (assuming it's not going to cost too much in download bandwidth).

One problem is that's I'm not sure that putting a CNAME of say `pyodide.cdn2.iodide.io` to `pyodide.r0h.eu` would be enough to make it work. That would probably need more investigation.

**Comment by rth** [comment]
So I tagged 0.15.0 but we may potentially have a problem with the new CDN a bit similar to what we had before with Netlify. According to Cloudflare TOS, they also don't allow too much of non HTML content either,
> 2.8 Limitation on Serving Non-HTML Content

> The Service is offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as a part of a Paid Service purchased by you, you agree to use the Service solely for the purpose of serving web pages as viewed through a web browser or other functionally equivalent applications and rendering Hypertext Markup Language (HTML) or other functional equivalents. Use of the Service for serving video (unless purchased separately as a Paid Service) or a disproportionate percentage of pictures, audio files, or other non-HTML content, is prohibited.

What is ["disproportionate percentage" is a bit fuzzy](https://community.cloudflare.com/t/mp4-large-files-cdn/550), bit potentially they may decide one day that we have reached that limit and either stop serving files or stop caching them. I should have checked this in more details.

So I think it would be safer to either,
 - ask them for an [OSS sponshorship](https://developers.cloudflare.com/sponsorships/#apply-for-sponsorship) (which would mean keeping exactly the current setup)
 - or ask one from fastly (which would require a change in our setup, but hopefully transparent to users).

Any preferences @wlach? BTW, do you have access to [Netlify logs](https://app.netlify.com/sites/pyodide/) ? It would be useful to know how much volume we are talking about. Is it a few GB, 10s or 100s: that would be good to know when applying, and I'm wondering if Netlify has some stats.
