### ISSUE TITLE
Pre-built docker container

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#656]
Currently we have a docker container with all the dependencies in `https://github.com/iodide-project/pyodide/blob/master/Dockerfile`.

I think it could be useful to distribute one with a pre-build version of packages, so that to build a new package one would only,
 1. Create a folder `<package_dir>` with `meta.yaml` and necessary patches
 2. Run something like,
    ```
    docker run -v <package_dir>:/pkg/ pyodide-build
    ```
    to mount this folder inside docker, build the package and store the output without having to build the full pyodide distribution.

I might take some work though to automate the building of this image in CI on new tags (and update build scripts to make it possible).

**Comment by rth** [comment]
So this could still be useful but there are several points that should made building faster  even without a pre-built image,
 - it's now possible to compile libraries (including cpython) in parallel with the `PYODIDE_JOBS` env variable https://pyodide.readthedocs.io/en/latest/building_from_sources.html#environement-variables 
 - updating to emscripten 1.38.33+ (https://github.com/iodide-project/pyodide/pull/480) would remove the need to build clang from sources which takes a long time
 - migrating C libraries to the Python build system (https://github.com/iodide-project/pyodide/issues/713) would allow only build only libraries that are needed by a particular package.

**Comment by MischaPanch** [comment]
Here a PR with an initial proposal
https://github.com/iodide-project/pyodide/pull/787

**Comment by rth** [comment]
Resolved in https://github.com/iodide-project/pyodide/pull/787.
