### ISSUE TITLE
how to  get the api which given xml data using pyodide 

### ISSUE THREAD

**Issue by preetiverma525** [iodide-project/pyodide#662]
when i use the the below code its given me an error 

response = requests.request("GET", url)

how can i use the requests in pyodide

**Comment by preetiverma525** [comment]
but i am getting issue when i used to
https://github.com/dota2tools/chat/blob/2bc2d1c96f16f22c8b34f7099733486015b2a9dc/main.js#L15
code

 i am not able to read the csv file using the open_url

[image: image.png]

**Comment by HQupgradeHQ** [comment]
@preetiverma525 , Image not working. Try using official [pyodide REPL](https://pyodide.cdn.iodide.io/console.html)

**Comment by preetiverma525** [comment]
still not working, any idea how can i troubleshoot it

**Comment by preetiverma525** [comment]
issue has been resolved. could you please let me know how can i install
the seaborn package in pyodide

**Comment by HQupgradeHQ** [comment]
@preetiverma525 with [`micropip`](https://pyodide.readthedocs.io/en/latest/pypi.html),also consider searching issues , there is already one for [`seaborn`](https://github.com/iodide-project/pyodide/issues/399#issuecomment-626020866)

**Comment by rth** [comment]
Closing as the previous comments answers the question(s). Thanks @HQupgradeHQ!
