### ISSUE TITLE
Add better linting: black, mypy

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#663]
I think it could be useful to add to CI,
 - https://github.com/psf/black for auto-formatting python code (with a 79 line length limit). The only issue is that the diff will be large when migrating.
 - [mypy](http://mypy-lang.org/) for static checking of python code. Anything that could be checked outside of the WASM env is a win time wise.
 - relax flake8 to only check syntax errors, unused variables and imports.

These can also run locally with a pre-commit setup.

**Comment by wlach** [comment]
I've found this helpful for the projects I've been maintaining. For iodide we used [flake8-black](https://pypi.org/project/flake8-black/), and it seems to work pretty well.
