### ISSUE TITLE
issue with xmltodict 

### ISSUE THREAD

**Issue by preetiverma525** [iodide-project/pyodide#670]
i am not able to install the xmltodict  in pyodide

**Comment by rth** [comment]
Please provide the logs from the JS console. What error are you getting?

**Comment by rth** [comment]
Seems to work for me,
```
>>> import micropip
>>> micropip.install('xmltodict')
Installed xmltodict
>>> import xmltodict
>>> xmltodict.__version__
0.12.0
```
one just need to wait a bit for packages to load due to https://github.com/iodide-project/pyodide/issues/695. Closing. Please comment if you still run into issues.
