### ISSUE TITLE
pyodide .data files not compressed on cloudflare

### ISSUE THREAD

**Issue by wlach** [iodide-project/pyodide#671]
It looks like pyodide `.data` files are not being compressed on the new cloudflare cdn, due to them not being a cloudflare supported type:

![image](https://user-images.githubusercontent.com/20569/82674569-805a4c80-9c11-11ea-939d-586f6133c288.png)

@rth -- any chance you could set the mimetype to `application/wasm`? I know it's not *technically* true, but I don't think it does any harm and will give cloudflare the hint to compress them. Should help download times enormously, esp. on slower connections:

https://community.cloudflare.com/t/how-to-enable-brotli-compression-on-a-different-file-type/142742/4

**Comment by rth** [comment]
Yes, we can set the content-type to wasm. It should indeed help with download sizes,
```
6,6M pyodide.asm.data
4,3M pyodide.asm.data.gz
3,7M pyodide.asm.data.br
```
For instance for the `console.html` example, the download size is,
 - pyodide.cdn: 23.99 MB / 8.62 MB transferred
 - pyodide-cdn2: 22.62 MB / 9.98 MB transferred

so this is indeed a regression (slightly compensated by https://github.com/iodide-project/pyodide/pull/647). 

Thanks for identifying this, I'll look into it.

**Comment by rth** [comment]
#672 should fix it, the only thing that with current caching options
```bash
  cache-control: max-age=30758400  # 1 year
```
we would need to make a new patch release to apply it. While we are at it we might want to re-evaluate if that 'cache-control' option is optimal.

For instance, other projects use the following `cache-control` options,
- `cdn.jsdelivr.net: `public, max-age=604800, s-maxage=43200` (7 days)
- `pyodide.cdn` (Netlify): `public, max-age=0, must-revalidate` (is cached but need an HTTP request to re-validate for each object)
- `cdnjs.cloudflare.com`: `public, max-age=30672000` (1 year)
- `files.pythonhosted.org` (PyPi storage): `max-age=365000000, immutable, public` (11 years)

So I think I'll also add,
 - `public`: for dev deployments from `master`
 - `immutable, public`: for releases.

**Comment by rth** [comment]
> For instance for the console.html example, the download size is,
>    pyodide.cdn: 23.99 MB / 8.62 MB transferred
>    pyodide-cdn2: 22.62 MB / 9.98 MB transferred

Loading `console.html` from `/dev/full/` or `/v0.15.0/full/` should now take,
  - 22.62 MB / 7.42 MB transferred  -- a 14 % improvement in download size with respect to 0.14.3 for the core pyodide download.
 
Changing the content-type metadata for the files in the last release also seems to work. I'm not sure how exactly cloudflare caching works, I guess it also depends on the edge locations and they might not respect `cache-control` to the letter. Maybe we don't need to make a new patch release for this after all.
