### ISSUE TITLE
CORS problem with 'https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.wasm'

### ISSUE THREAD

**Issue by josephernest** [iodide-project/pyodide#678]
I'd like to do a pyodide "Hello world" from `http://myserver.com/index.html` (see below), but I get this error:

> (index):1 Access to fetch at 'https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.asm.wasm' from origin 'http://<myiphere>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**How can we use your CDN from our own websites to sandbox with pyodide?**

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript">
        window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';
    </script>
    <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
</head>
<body>
  Pyodide test page <br>
  Open your browser console to see pyodide output
  <script type="text/javascript">
        languagePluginLoader.then(function () {
            console.log(pyodide.runPython('import sys\nsys.version'));
            console.log(pyodide.runPython('print(1 + 2)'));
        });
  </script>
</body>
```

**Comment by rth** [comment]
@josephernest I copy pasted this snippet to https://rth.github.io/pyodide.html and it does work for me both in Firefox and Chrome. CORS headers are only sent if the request contains the `Origin` which should be done in any standard browser see https://github.com/iodide-project/pyodide/issues/669 for related discussion.

**Comment by josephernest** [comment]
@rth I have this even on https://rth.github.io/pyodide.html, with Chrome 83 (I retried with uBlock disabled, it's the same):

![image](https://user-images.githubusercontent.com/6168083/83515326-779d2c80-a4d5-11ea-86ca-8d156ef9a894.png)

**Comment by josephernest** [comment]
Solved with CTRL+F5! It was probably a cache problem (?!) since I initially wanted to load it from a `file://.../index.html` location?

**Comment by josephernest** [comment]
PS @rth how is it possible that it only takes:

* 3.1MB for `pyodide.asm.wasm`
* 4.2MB for `pyodide.asm.data`

?

It seems very small, in comparison to 50MB or 180MB I read for similar other projects.

How can a full Python interpreter and its modules be packed in 3.1MB + 4.2 MB?

**Comment by rth** [comment]
> Solved with CTRL+F5! It was probably a cache problem (?!) since I initially wanted to load it from a file://.../index.html location?

Yes, likely a cache issue. https://stackoverflow.com/a/34496683/1791279 describes a similar problem.

> How can a full Python interpreter and its modules be packed in 3.1MB + 4.2 MB?

Well it's around 20MB uncompressed, but it does indeed only takes ~7MB to download with the Brotli compression from the CDN. Once you start loading additional packages those are larger (e.g. pandas is an additional 7.5MB to download). There are some ideas for reducing the size further in https://github.com/iodide-project/pyodide/issues/646

**Comment by josephernest** [comment]
@rth Amazing! It's really a wonderful project with a bright future, I think.

I did not know pandas is even available, great!

PS: is there complicated to make a module that can modify PDF (such as excellent [pdfrw](https://pypi.org/project/pdfrw/)) available for `pyodide`?

**Comment by rth** [comment]
> PS: is it complicated to make a module that can modify PDF (such as the excellent pdfrw) available for pyodide?

You should be able to install it with micropip from PyPi. I'm not sure if everything works but at least the import does,
```
>>> import micropip
>>> micropip.install("pdfrw")
Installed pdfrw
>>> import pdfrw
>>> pdfrw.__version__
0.4
```
see https://pyodide.readthedocs.io/en/latest/pypi.html for more information.

**Comment by josephernest** [comment]
Nice idea @rth.

I tried:

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript">
        // set the pyodide files URL (packages.json, pyodide.asm.data etc)
        window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';
    </script>
    <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
</head>
<body>
  Pyodide test page <br>
  Open your browser console to see pyodide output
  <script type="text/javascript">
        languagePluginLoader.then(function () {
            console.log(pyodide.runPython('import micropip'));
            console.log(pyodide.runPython('micropip.install("pdfrw")'));
        });
  </script>
</body>
```

but I get: 

> ModuleNotFoundError: No module named 'micropip'

How to enable it?

PS @rth: is there a way to support multiline Python code inside `pyodide.runPython`? Because using `pyodide.runPython('import this\nprint("hello")')` with `\n` is not very handy.

**Comment by rth** [comment]
> How to enable it?

You need to first load the micropip package see, https://pyodide.readthedocs.io/en/latest/pypi.html#complete-example

> is there a way to support multiline Python code inside pyodide.runPython

Yes, it will call `textwrap.dedent` on string input, so it would work with multi-line strings even if they are additionally indented by some amount. The above linked example illustrates multiline strings as well.

**Comment by rth** [comment]
Closing this one. If you have other questions/comments don't hesitate opening new issues.

**Comment by josephernest** [comment]
Thanks @rth! Oh if you use `textwrap.dedent` under the hood, it's perfect then!
