### ISSUE TITLE
File input/output with pyodide? (input: filepicker/drag'n'drop,  output: as download)

### ISSUE THREAD

**Issue by josephernest** [iodide-project/pyodide#679]
**Is there a canonical example showing how to import/export a file with `pyodide`?**

Example input/output workflow:

* Drag/drop a file from the desktop to the browser page
* JS classically handles the drag'n'drop (like when uploading on imgur.com for example)
* => then how can we pass this "dropped" file to Pyodide: which Python code can be used to access the file content?
* (Do some processing with Python...)
* How can Python export a file? i.e. it will appear as a "download" in the browser

**Comment by rth** [comment]
The short answer there is currently no such example, but I think it would be extremely useful. 

For instance https://github.com/iodide-project/pyodide/issues/675 essentially the same question. There was also https://github.com/iodide-project/pyodide/pull/489 that's somewhat related. 

> => then how can we pass this "dropped" file to Pyodide: which Python code can be used to access the file content?
> How can Python export a file? i.e. it will appear as a "download" in the browser

If you have this file as a string object in JS and save it to a variable, you can access it from python, with `from js import <variable_name>`. Then you can write it to the virtual file system inside WASM machine using standard python tools,
```py
with open('/example.py', 'wt') as fh:
    fh.write(contents)
```
and then import it using standard python mechanisms by adding e.g. `/` to `sys.path` if necessary.

For export, you would basically do,
```js
let x = pyodide.runPython("open('/example.py', 'rt').read()");
```
to get it as a variable in JS, and then trigger the download action from JS (I imagine it's possible?).

See https://pyodide.readthedocs.io/en/latest/type_conversions.html#type-conversions for more details.

There is a more complete example of an applications doing some of it in https://github.com/pymedphys/pymedphys/issues/838#issuecomment-631208519 but I think it would be very useful to to have a simple example in pyodide without using too much external JS libraries.

**Comment by josephernest** [comment]
Thanks a lot! This example works for binary input files (it would be even easier for text UTF8 input)

```
<!DOCTYPE html>
<html>
<head>
<script type="text/javascript">window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';</script>
<script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
</head>
<body>
<input type="file" onchange="doit();" id="file">
<script type="text/javascript">
var content = null;

function doit() {
    var file = document.getElementById("file").files[0];
    var reader = new FileReader();
    reader.readAsBinaryString(file);
    reader.onload = evt => { 
        content = evt.target.result; 
        var output = pyodide.runPython('from js import content\ncontent');
        var l = output.length;
        var array = new Uint8Array(l);
        for (var i = 0; i < l; i++) {
            array[i] = output.charCodeAt(i);
        }
        var blob = new Blob([array], {type: 'application/octet-stream'});
        var elem = window.document.createElement('a');
        elem.href = window.URL.createObjectURL(blob);
        elem.download = 'output.pdf';
        document.body.appendChild(elem);
        elem.click();        
        document.body.removeChild(elem);
    }
}

languagePluginLoader.then(function () {
    console.log('Ready');
});
</script>
</body>
```

**Comment by NishiPhalke** [comment]
> Thanks a lot @rth! This example works for binary input files (it would be even easier for text UTF8 input). Feel free to re-use it as an example for input/output of files in the browser.
> 
> ```
> <!DOCTYPE html>
> <html>
> <head>
> <script type="text/javascript">window.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';</script>
> <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>
> </head>
> <body>
> <input type="file" onchange="doit();" id="file">
> <script type="text/javascript">
> var content = null;
> 
> function doit() {
>     var file = document.getElementById("file").files[0];
>     var reader = new FileReader();
>     reader.readAsBinaryString(file);
>     reader.onload = evt => { 
>         content = evt.target.result; 
>         var output = pyodide.runPython('from js import content\ncontent');
>         var l = output.length;
>         var array = new Uint8Array(l);
>         for (var i = 0; i < l; i++) {
>             array[i] = output.charCodeAt(i);
>         }
>         var blob = new Blob([array], {type: 'application/octet-stream'});
>         var elem = window.document.createElement('a');
>         elem.href = window.URL.createObjectURL(blob);
>         elem.download = 'output.pdf';
>         document.body.appendChild(elem);
>         elem.click();        
>         document.body.removeChild(elem);
>     }
> }
> 
> languagePluginLoader.then(function () {
>     console.log('Ready');
> });
> </script>
> </body>
> ```

Hi @josephernest, @rth, How can upload *.tar.gz file from browser and write it to VFS inside WASM in python ?
