### ISSUE TITLE
Return a value to a Javascript variable after a micropip.install(...).then(main)

### ISSUE THREAD

**Issue by josephernest** [iodide-project/pyodide#680]
In this code:

```
var output = pyodide.runPython(`
            def main(*args):
                import anypackage
                from js import content
                # do something here on content
                return content

            import micropip
            micropip.install("anypackage").then(main)
        `);
```
the return value `content` is not passed to Javasript: `output` is empty.

**What's the proper way to return `content` to the Javascript variable `output`?**

**Comment by rth** [comment]
I think the fundamental issue is that `micropip.install` returns a Promise, https://github.com/iodide-project/pyodide/blob/4ee8dedeedcb7b77f683470cf83b2a9985e58801/packages/micropip/micropip/micropip.py#L287 and so the above would generally not work in JS as far as I understand.

I wonder if it's possible to pass the response to JS, and call `then` there.
```py
pyodide.runPython('micropip.install("anypackage")').then(
            var output = pyodide.runPython(`
            def main(*args):
                import anypackage
                from js import content
                # do something here on content
                return content
           `);
```
or something along those lines?

**Comment by josephernest** [comment]
Thanks @rth but it seems the callback inside then is never executed:

```
pyodide.runPython('micropip.install("pdfrw")').then(function() {
            console.log('hello');
});
```

(nothing is logged).

**Comment by josephernest** [comment]
Working (with a function inside then)!
