### ISSUE TITLE
omp.h not found

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#683]
Hello. Following #682 I have checked out pyodide from git again and trying to build MDAnalysis. However, when I run make the following occurs:
```
In file included from MDAnalysis/lib/c_distances_openmp.c:642:
MDAnalysis/lib/include/calc_distances.h:28:12: fatal error: 'omp.h' file not found
  #include <omp.h>
           ^~~~~~~
1 warning and 1 error generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting

```
If I symlink the docker-image omp.h (which is /usr/lib/gcc/x86_64-linux-gnu/8/include/omp.h) under /src/emsdk/emsdk/emscripten/tag-1.38.31/system/include/
the error disappears and a new one appears:
```
emcc -pthread -shared build/temp.linux-x86_64-3.7/MDAnalysis/lib/c_distances_openmp.bc -lm -lgomp -o build/lib.linux-x86_64-3.7/MDAnalysis/lib/c_distances_openmp.cpython-37m-x86_64-linux-gnu.wasm -fopenmp
shared:ERROR: emcc: cannot find library "gomp" (`-s ERROR_ON_MISSING_LIBRARIES=0` to disable this error)
```
How do I overcome this issue? I know that openmp library can be and in fact, was compiled for wasm.

**Comment by rth** [comment]
> How do I overcome this issue? I know that openmp library can be and in fact, was compiled for wasm.

At the moment pyodide doesn't support threading see (#237), so the only workaround could be to patch the setup.py to build the corresponding files without `openmp`. 


> Following #682

Does it mean that the linked issue can be closed?

**Comment by Hiisi5** [comment]
Thank you! I have disabled openmp and it works now. I will also close the other issue now.
Spasibo, Roman!

**Comment by genderev** [comment]
I don't mind the compatibility issues. Atomics are supported in Chrome and Firefox now. 

I tried to compile Pyodide from source and then use `wasm-opt` to take the resulting Pyodide `.wasm` binary and add threading support, but this effort failed because the binary used dynamic linking.

**Comment by oh-wo** [comment]
Hi @Hiisi5 I'm trying to build a pyodide package of mdanalysis currently. Did you ever get it working? I was wondering if I could ask for some advice.

**Comment by Hiisi5** [comment]
> Hi @Hiisi5 I'm trying to build a pyodide package of mdanalysis currently. Did you ever get it working? I was wondering if I could ask for some advice.
Well, it's all about dependencies. I remember I had it working - the main package itself was compiled and I could import it in python pyodide env. However, any submodules required additional porting and I abandoned the idea back then. Many things have changed since and the compatibility must have improved. What's the immediate first issue you have building mdanalysis?

**Comment by oh-wo** [comment]
> Well, it's all about dependencies. I remember I had it working - the main package itself was compiled and I could import it in python pyodide env. However, any submodules required additional porting and I abandoned the idea back then. Many things have changed since and the compatibility must have improved. What's the immediate first issue you have building mdanalysis?

Thanks very much for your reply. Makes sense. I can't tell how big a lift it could be so was really just looking for any general comments you had. So far I'm having issues loading numpy which is required (in the current version) for packaging (e.g. in setup.py). I'm not sure whether I should be trying to load regular numpy or if I would somehow have to load the pyodide version of numpy rather than the regular non-pyodide version. 
Is that the kind of thing you tried in your previous attempt? 

Thanks again.

**Comment by Hiisi5** [comment]
Numpy is easy. It's distributed with pyodide. You just have to load it to be able to use (import) it in your Python code. Check the [documentation](https://pyodide.org/en/stable/usage/loading-packages.html).

**Comment by oh-wo** [comment]
Sorry if I miscommunicated; I meant it's required as a dependency of `mdanalysis` - the existing python package I'm trying to convert to a pyodide package. I get the feeling I should import the pyodide version when building `mdanalysis` so I'll try that next. Anyway, thanks for the help.
