### ISSUE TITLE
python runtime lib2to3: how do I get in in pyodide?

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#686]
Hello. My package needs lib2to3. I.e.:
```
import lib2to3
```
On my PC it is provided by python runtime libraries:
```
Filename    : /usr/lib64/python3.8/lib2to3/__init__.py

python3-libs-3.8.3-1.fc32.x86_64 : Python runtime libraries
```
It seems that pyodide doesn't distribute that. Any chance of still getting it?

**Comment by rth** [comment]
Yes, `lib2to3` module is explicitly removed in pyodide https://github.com/iodide-project/pyodide/blob/d7c0879cc32f500e14d5eee24274424ddba20073/remove_modules.txt#L7 because we assume packages are written in Python 3 not 2. You could try removing that line, rebuilding (after a `make clean -C cpython`), and see if it helps, but generally for this and https://github.com/iodide-project/pyodide/issues/686 it's probably easier to help upstream packages to properly migrate to Python 3. Python 2 _is_ deprecated now..

**Comment by Hiisi5** [comment]
I understand. However, the package that I'm trying to build just recently migrated from python 2 to 3. It seems they use 2to3 and have not ported the code completely (the project is MDAnalysis).
I was able to recompile cpython after removing the line. Noob question: how do I serve http from the docker image?

**Comment by Hiisi5** [comment]
It did not help:
```
pyodide.runPython('import lib2to3')
pyodide.asm.js:8 Python exception:
pyodide.asm.js:8 Traceback (most recent call last):
pyodide.asm.js:8   File "/lib/python3.7/site-packages/pyodide.py", line 43, in eval_code
pyodide.asm.js:8     exec(compile(mod, '<exec>', mode='exec'), ns, ns)
pyodide.asm.js:8   File "<exec>", line 1, in <module>
pyodide.asm.js:8 ModuleNotFoundError: No module named 'lib2to3'
```

**Comment by rth** [comment]
> However, the package that I'm trying to build just recently migrated from python 2 to 3. It seems they use 2to3 and have not ported the code completely (the project is MDAnalysis).

I can't find any mentions of lib2to3 in their source code. Why is it needed?

**Comment by Hiisi5** [comment]
I was actually able to remove those parts of code and MDAnalysis seems to be working in pyodide. I have to figure out now how to deal with filesystem in pyodide. As for lib2to3, it never showed up in the list of available packages (i.e. pyodide.runPython('help(\'modules\')')), despite the fact that I have recompiled cpython as suggested.
Roman, should the issue be closed since there's no need/incentive to deal with it from the project maintainers?

**Comment by rth** [comment]
Thanks for the feedback. Yes, let's close it then.
