### ISSUE TITLE
FS.stat: where's ifFile() isDirectory() methods?

### ISSUE THREAD

**Issue by Hiisi5** [iodide-project/pyodide#694]
Hello.
Is there a way of knowing whether a path is a file or directory? I know that emscripten nodefs provides isFile() and isDirectory() methods exactly for that:
[emscripten file API](https://emscripten.org/docs/api_reference/Filesystem-API.html#file-types)
However, if I obtain file stats using `pyodide._module.FS.stat(path)` it does not contain those methods. So, how do I know whether a path is a file or directory?

**Comment by rth** [comment]
> if I obtain file stats using pyodide._module.FS.stat(path) it does not contain those methods.

Wouldn't explicitly calling `pyodide._module.FS.isDir(path)` or `pyodide._module.FS.isDir(path)` work? It doesn't look like the response of `stat` should contain those methods?
 
Otherwise via Python `pyodide.pyimport('pathlib').Path(<path>).is_dir()`

**Comment by Hiisi5** [comment]
It does. Sorry for the noise. The issue is closed.
