### ISSUE TITLE
/emsdk install --build=Release sdk-fastcomp-tag-1.38.31-64bit Installing SDK 'sdk-fastcomp-tag-1.38.31-64bit'.. Installing tool 'fastcomp-clang-tag-e1.38.31-64bit'.

### ISSUE THREAD

**Issue by lgyStoic** [iodide-project/pyodide#719]
I am building from docker,but  when makefile the emsdk, it will show 

![image](https://user-images.githubusercontent.com/4526646/87215363-82669f00-c368-11ea-88df-ebe5c2dee72d.png)

Downloading no progress.....
But I can using wget from terminal ...

**Comment by rth** [comment]
Hi @lgyStoic, thanks for the report. It's very likely some connection issues. That download is run in emsdk [here](https://github.com/emscripten-core/emsdk/blob/751355a267e6fed6b6be57c514c6391e6520f1ca/emsdk#L1481) which download using [urllib](https://github.com/emscripten-core/emsdk/blob/751355a267e6fed6b6be57c514c6391e6520f1ca/emsdk#L534). I can confirm that running it in a Docker container works fine for me. Maybe re-trying at a later time would help?

If that still doesn't work, you could try running commands from [emsdk/Makefile](https://github.com/iodide-project/pyodide/blob/bc3ffaae427e35b9ecd9a6216fadad031a363a47/emsdk/Makefile#L8) one by one, then starting `python -m pdb ./emsdk` with a debugger to investigate what is happening there.

**Comment by rth** [comment]
Closing following the above comment. Don't hesitate to comment if you run into other issues.
