### ISSUE TITLE
Port Scipy

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#72]
We should port the Scipy package, since it's the basis of a number of other important packages, scikit-learn, scikit-image, etc.

**Comment by rngadam** [comment]
Thank you! Will look at this if nobody else is planning to work on it. What would be your estimate of time needed, based on your experience @mdboom ?

**Comment by mdboom** [comment]
See #75.

My best advice is to get pyodide master compiling locally for you first (if you haven't already), and then try the `scipy` branch (which won't finish).

You can find me on gitter in `iodide-project/iodide` if you have any questions.  Welcome aboard!

**Comment by rngadam** [comment]
@mdboom thank you so much for your guidance! Will follow up tomorrow my time and get started!

**Comment by mdboom** [comment]
We may also run into limits of our current monolithic test script when we add Scipy, and may want to somehow separate out the building of packages into separate repos or at least separate Circle-CI runs.  See https://github.com/iodide-project/pyodide/issues/38#issuecomment-403028758 and #76 for related discussion.

**Comment by mdboom** [comment]
Great you're trying this on MacOS X.  Hopefully it's similar enough.

You plan looks good.  I might change the order of your last two points.  If you build the whole thing, you'll be able to determine if it's too big to work and whether splitting it up is even necessary.  I also wouldn't suggest entirely separate Python packages, just that each subdirectory under the scipy root is built into a separate `.dat`/`.js` file.  That will require a little tweaking of the Pyodide build tools to make that happen.

**Comment by mdboom** [comment]
Also: I think github only lets users with commit rights assign issues.

**Comment by jakirkham** [comment]
FWIW there was some work done to build [`flang`]( https://github.com/conda-forge/flang-feedstock/ ). So that might be worth giving a try. We don't currently have a build of it for macOS (likely requires some more patching), but Linux support should be pretty good (that's their primary target platform). Using a Docker container with `flang` and `emscripten` could be a reasonable option.

**Comment by rth** [comment]
> Using a Docker container with flang and emscripten could be a reasonable option.

There is also some useful related discussion in https://github.com/kripken/emscripten/issues/998 and https://github.com/kripken/emscripten/issues/5553

**Comment by rth** [comment]
In other scipy/Fortran related news from https://mail.python.org/pipermail/scipy-dev/2019-June/023584.html

> Apparently there is a common situation where C code calling into
Fortran violates the Fortran ABI, and has been accidentally getting
away with it for years, but in the near future it will start causing
mysterious crashes:

> https://lwn.net/SubscriberLink/791393/d04954027a732415/
> https://developer.r-project.org/Blog/public/2019/05/15/gfortran-issues-with-lapack/

> Both CBLAS and LAPACKE are specifically called out as including broken
code, so I guess this is pretty widespread.

Not sure this affects pyodide, but worth keeping in mind.

**Comment by dalcde** [comment]
Should this be closed now that scipy is packaged?

**Comment by rth** [comment]
Yes, let's open more specific issues on remaining scipy issues.
