### ISSUE TITLE
[Feature] Add alternative like PyPy

### ISSUE THREAD

**Issue by redradist** [iodide-project/pyodide#739]
I think it also should be considered to bring PyPy to the WebAssembly using emscripten toolchain like faster alternative to CPython 3.8

Issue would be only to provide custom JIT-er in RPython that is used under PyPy

Discussion also started in repo of PyPy https://foss.heptapod.net/pypy/pypy/-/issues/3261

**Comment by redradist** [comment]
As base could be taken work done in https://github.com/pypyjs/pypyjs

**Comment by phorward** [comment]
Hello @redradist,
thank you for your issue. I think that a port of Pyodide to use PyPy could be useful and challanging. But it doesn't focus the current goal of the Pyodide-project, which is "bringing the Python scientific stack to the browser", which obviously requires for the C-bindings of some packages.

Honestly, I'm also thinking about giving RustPython a try, as it can also compile into WebAssembly and uses a Python-native standard library, but this would also not be in the focus of Pyodide's project goal.

Feel free to make a fork of Pyodide and integrate PyPy by yourself. We currently don't have capacities and intentions to do so here for now.

**Comment by rth** [comment]
Thanks for the proposal @redradist ! Yes, PyPy is getting better and better for scientific computing, but it still has performance concerns with C extensions as compared to CPython. Hopefully https://github.com/pyhandle/hpy would address that in the future, but for now CPython for pyodide is still the easiest choice.

Closing for now as we don't have the resources to work on it, as mentioned above, however if you experiment with PyPy and emscripten don't hesitate to comment here.
