### ISSUE TITLE
Calling Python functions via a proxy

### ISSUE THREAD

**Issue by jarble** [iodide-project/pyodide#750]
It's possible to invoke Python functions by passing a string to the Python interpreter:
```
pyodide.runPython(`
print("Hello, Python!")
`);
```
but I'd prefer to call the functions using a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), like this:
`pyodide.runPython.print("Hello, Python!");`

Does Pyodide have a feature like this? It seems that it would be easy to implement, since Pyodide is already able to convert JavaScript objects to Python objects and vice-versa.

**Comment by jarble** [comment]
For example, it could be implemented using a handler:

```
var handler = {
    get: function(target, name) {
        return function(){
          return pyodide.run(name+"("+Array.prototype.slice.call(arguments).map(JSON.stringify).join(",")+")");
        };
    }
};
var proxy = new Proxy({}, handler);

proxy.print(''Hello, Python!'); 
```

**Comment by rth** [comment]
Hi, have you tried using the [`pyodide.pyimport` API](https://pyodide.readthedocs.io/en/latest/api_reference.html#pyodide-pyimport-name) or `pyodide.globals` (from JS) for this?

**Comment by jarble** [comment]
@rth This is probably the feature that I was looking for, but [documentation](https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html) doesn't describe it yet.

**Comment by rth** [comment]
It's documented in https://pyodide.readthedocs.io/en/latest/type_conversions.html#type-conversions but maybe we should move it from the "Developpment" to "Usage" section indeed. Also a link from the "using_pyodide_from_javascript" page might help. Would you like to make a PR to improve the documentation?

> Is it possible to import and call Python functions using pyodide.pyimport?

yes, for instance `copyodide.pyimport('print')('some messsage')` works.
