### ISSUE TITLE
Speed up build and tests

### ISSUE THREAD

**Issue by mdboom** [iodide-project/pyodide#76]
We currently don't run the CPython tests on Circle-CI because we run out of the allotted time.  Clever use of parallelization and/or caching might be able to get us over the hump.

A Circle-CI expert could probably make faster progress on this than I can.

**Comment by rth** [comment]
As far as I understand, currently caching is only based on the checksum of `emsdk/Makefile`. Circle CI does support [several caching strategies](https://circleci.com/docs/2.0/caching/#using-keys-and-templates), but I'm not yet sure how this could be applied.

When building e.g. scipy, it would be nice if numpy didn't have to be rebuilt if nothing changed in it's configuration. For instance, one could cache the generated numpy, with the checksum of the config under `packages/numpy/` (assuming all the numpy related config is located there, which might not be case) then re-use it and skip the numpy build if the checksum didn't changed. Though in general this would mean some form of dependency resolution to know which packages would need to be rebuild if a config changes.   

This also could apply to tests -- it would be useful to be able to run the full test suite in CI (https://github.com/iodide-project/pyodide/issues/69) but we wouldn't want to run the test suite of all the dependencies when building a package.

Maybe https://github.com/iodide-project/pyodide/issues/52 could help a bit as well. Also pytest-xdist is currently installed in circle-ci but not used in the `Makefile` (with the current amount of tests it shouldn't matter).

In the long run though, I'm not sure what is the desired packaging setup. I am familiar e.g. with the conda-forge approach where when we rebuild a package, all it's dependencies are assumed to be fixed. Not sure how things work in the JS ecosystem and if some tools from it would be useful. Here we would be rebuilding everything if one of the core elements changes. It is better for quick iterations but won't probably scale so well, as new packages are added. 

Will try to investigate this.

**Comment by mdboom** [comment]
This all makes great sense as things to investigate.  We do have the dependency graph in `build/packages.json`.  If that were available to the CircleCI script (would probably have to check it into git), it could probably be leveraged for some of what you describe.  Or, maybe it is easier to take the conda-forge approach and move everything to separate repos.

I experimented with pytest-xdist on Circle CI, but it quickly ran out of the available RAM there when running in parallel (since the tests run in Selenium), so I backed it out.  Maybe grouping some of the tests to run in the same Selenium instance would help...

**Comment by mdboom** [comment]
As a low-hanging-fruit short term solution, I'm enabling `ccache` on Circle-CI over in #88.  This should at least take the most time-intensive part of rebuilding out of the equation.  And it's nice because we don't have to change how things work too much and reason too much about what might need to be rebuilt.

**Comment by rth** [comment]
Proposed PR to address this issue in #118 and #116. If the first one is accepted, the second might no longer be necessary (though it's still useful to separate chrome and firefox tests IMO).

**Comment by hexagon6** [comment]
I would try to setup a headless chrome instead of selenium, which might speed things up (at least for chrome testing).

**Comment by rth** [comment]
A lot of work on speeding up CI has been done since 2018. Remaining things could be
 - building python packages in parallel (https://github.com/iodide-project/pyodide/issues/52)
 - running tests with pytest-xdist.

**Comment by dalcde** [comment]
Another option is to run the `src/tests/*` tests on top of `build-minimal`. Most of the build time is used to build the libraries, and we can start testing core python before that. This is especially useful if we get failures on core python so that we can know it early on.

**Comment by rth** [comment]
Yes, it would be a good idea. Currently the CI workflow looks as follows
![image](https://user-images.githubusercontent.com/630936/101007244-ab7b0c80-3561-11eb-9556-8b039fb694ee.png)
with a total run time of ~70min.

and so if we start pyodide tests just after the minimal version is built, and in parallel build packages (and then test them), we can probably save 20min on so on the total run time. This would provide also a better separation between the core pyodide package and other packages.  

In https://github.com/iodide-project/pyodide/pull/658 I tried to start using other comilation flags for the minimal build which would be not compatible with this apporach. But I think for now keeping the same compilation flags would be easier to maintain and iterate on.

**Comment by dalcde** [comment]
On the topic of build speed, why do we build a copy of the host's python? Especially in CI where we have exactly the right version of python.

**Comment by rth** [comment]
> On the topic of build speed, why do we build a copy of the host's python? Especially in CI where we have exactly the right version of python.

We currently need both host and target python to build packages (see https://github.com/iodide-project/pyodide/issues/819). With docker we could probably indeed just use the provided system Python (assuming that the fact that we patch CPython is not an issue), however that would mean users without Docker will not be able to build pyodide. For instance, MacOS users where Docker in a VM is very slow apparently¹.

¹compilation on MacOS is currently not fully working https://github.com/iodide-project/pyodide/issues/572 but there is hope it would be eventually fixed.

**Comment by dalcde** [comment]
We could check if the system python is the same minor version and skip
building host python if so.

**Comment by rth** [comment]
Lots of work has been done on speeding up build and tests. So I'm closing this issue. Though of course further improvements are always possible.

> with a total run time of ~70min.

Total run time is now ~35min assuming an existing ccache cache.
