### ISSUE TITLE
No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by akirakotsugai** [iodide-project/pyodide#762]
This is how I set  window.languagePluginUrl = "https://pyodide-cdn2.iodide.io/v0.15.0/full/"

and this is how I import pyodide.js: <script src="https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js"></script>

On the console I get "Python initialization complete" but then I get the following error:
Access to fetch at 'https://pyodide-cdn2.iodide.io/v0.15.0/full/packages.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

it seems to be a great lib and I would like to use it on my react project but I havent been able to try it yet.

Thanks a lot

**Comment by smkm** [comment]
Looks like a duplicate to #751.

**Comment by rth** [comment]
@akirakotsugai Does the Python REPL (see [readme](https://github.com/iodide-project/pyodide#try-pyodide-no-installation-needed)) work for you?

Are you using a webserver to serve your HTML file? If you are not that can result in CORS errors.

**Comment by akirakotsugai** [comment]
> @akirakotsugai Does the Python REPL (see [readme](https://github.com/iodide-project/pyodide#try-pyodide-no-installation-needed)) work for you?
> 
> Are you using a webserver to serve your HTML file? If you are not that can result in CORS errors.

no, I just created an html file to get started with it. But I also tried that from a web worker of a local react app. Could be that web workers run on a thread so there is no CORS?

**Comment by rth** [comment]
Loading a local HTML file directly won't work I think. You need to start a [web server which allows CORS](https://pyodide.readthedocs.io/en/latest/using_pyodide_from_javascript.html#serving-pyodide-files). About the webworker situation I'm not sure.
