### ISSUE TITLE
Pyodide maintanence

### ISSUE THREAD

**Issue by JanMatas** [iodide-project/pyodide#766]
Hi,

we have read [end of project development notice](https://github.com/iodide-project/iodide/commit/d0d89c11214e5ee7935164dcf31358ceaac0cd3d) for Iodide. Thanks for the awesome work on this project! 

I am just wondering whether this notice extends to pyodide as well? Do you still have plans to continue work on (or at least maintain) this repository?

Best,
Jan

**Comment by bcolloran** [comment]
Hi Jan, the EOL notice is only meant to cover the Iodide notebook IDE. While Mozilla is no longer sponsoring development of either project, Pyodide is largely self sufficient and community led at this point (And largely due to the great work of @rth!)

**Comment by ehfd** [comment]
Both Iodide and Pyodide are gaining BIG traction in academia to its applications. I am sad to hear Iodide is heading to EOL, but the burst of usages for Pyodide just started.

**Comment by rth** [comment]
Closing this as answered in https://github.com/iodide-project/pyodide/issues/766#issuecomment-701456373. Don't hesitate to contribute!
