### ISSUE TITLE
Confusing documentation

### ISSUE THREAD

**Issue by JaktensTid** [iodide-project/pyodide#773]
Documentation says 

```
If the package is pure Python:
Run the setup.py script to get the built package
Package the results into an emscripten virtual filesystem package, which comprises:
A .data file containing the file contents of the whole package, concatenated together
A .js file which contains metadata about the files and installs them into the virtual filesystem.
```

But you can only package c\cpp files using emcc. How can you package result of setup.py?

**Comment by rth** [comment]
The confusion may be due to the not included "We automate the following steps:" sentence at the top.

So all of this is automated (including copying of pure python files). You just need to create a `meta.yaml` folder in the appropriate folder and start the build (cf docs).

**Comment by JaktensTid** [comment]
@rth thank you for the response

Yes, I got it. Just was trying to build library for entire day :)

Maybe I am wrong, but looks like documentation is missing explanation of how pyodide binary works. I mean especially for buildpkg, buildall arguments. I was lucky that I've found that you can use this binary to build packages at all somewhere in the internet. Before that I was trying to do everything manually (i.e compile python into c\c++ using cython, reading numerous pages of emscripten docs, a lot of uneccessary steps, before I found how you can automate everything).

If I will create step-by-step tutorial on medium of how to build packages will you include link into the project or doc?

**Comment by rth** [comment]
> but looks like documentation is missing explanation of how pyodide binary works. I mean especially for buildpkg, buildall arguments

Yes, I agree we need to add a section or page explaining better how the pyodide build system works.

> If I will create step-by-step tutorial on medium of how to build packages will you include link into the project or doc?

For open-source projets it's typically better not to rely on instructions on third party party platforms too much, as over time things will tend to get outdated and we will have no way to update that tutorial then.

We would be very happy to include such a tutorial in the documentation (or generally any improvements to the documentation) though :)
