### ISSUE TITLE
Building pyodide.js from master

### ISSUE THREAD

**Issue by JaktensTid** [iodide-project/pyodide#775]
Hi,

I need to update emsdk to 1.38.31 version since I am encountering an issue related to emsdk 1.38.30. I tried to install this version standalone, but have more errors while running emcc. I noticed, that master branch is updated to the 1.38.31 version, but looks like that pyodide.js is taken from the latest release. How can I build it by myself? Do you have scripts for this somewhere in the project?

**Comment by rth** [comment]
You can use replace the `v0.15.0` with `dev` in the download CDNs to get the version from master with emsdk 1.38.31.

> How can I build it by myself? Do you have scripts for this somewhere in the project?

Well yes, see https://pyodide.readthedocs.io/en/latest/building_from_sources.html#using-docker. Building inside Docker is preferable when possible.

**Comment by JaktensTid** [comment]
>Well yes, see https://pyodide.readthedocs.io/en/latest/building_from_sources.html#using-docker.

Yes, I tried to do this. But looks like that pyodide.js inside build folder is still python 3.7.4 version.

**Comment by rth** [comment]
> But looks like that pyodide.js inside build folder is still python 3.7.4 version.

The [docker image](https://github.com/iodide-project/pyodide/blob/master/Dockerfile) itself doesn't include pyodide. It only [mounts the local folder](https://github.com/iodide-project/pyodide/blob/49dc822acb83b276ecfac50470324db53c9c28de/run_docker#L10) inside the container. So if you run the build from pyodide master, the same version will also be in the container (including Python 3.8)...

**Comment by JaktensTid** [comment]
Arghh, got a new issue

Is there any fix for 
`Uncaught (in promise) TypeError: resolveSymbol(...) is undefined`
error?

**Comment by JaktensTid** [comment]
Ok, I am sure that it's happening because of linking. 
Due to emscripten code `function resolveSymbol(sym, type, legalized) {` will be initialized only if you're building module with MAIN_MODULE>0, but as I see in the Makefile we're already doing this for libpython.a, so you cannot build your package with this argument (SIDE_MODULE=1 is used)

**Due to official docs** 
>you can build the main module with EMCC_FORCE_STDLIBS=1 in the environment to force inclusion of all standard libs. A more refined approach is to build the side module with -v in order to see which system libs are actually needed - look for including lib[...] messages - and then building the main module with something like EMCC_FORCE_STDLIBS=libcxx,libcxxabi (if you need those two libs).

So I will try to include my library to the lflags with EMCC_FORCE_STDLIBS=... . But I am still not sure how to build pyodide.js with most recent python... When I said that 'I've dealt with python versions' I mean that I tried to use https://pyodide-cdn2.iodide.io/dev/full/pyodide.js from CDN instead of https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js and it worked basically. But when I run following

./run_docker
make

pyodide.js, pyodide_dev.js that appearing in my /build folder are targeting python 3.7.
**Can someone lead me through the steps how can I generate pyodide.js by myself?**

**Comment by rth** [comment]
> Due to official docs

It should be noted that we currently use emscripten from >1 year ago (https://github.com/iodide-project/pyodide/issues/476) so the documentation currently on the emscripten website might not fully reflect the version we are using.

> Uncaught (in promise) TypeError: resolveSymbol(...) is undefined

Does it happen during build? At runtime, yes it's a known issue that's still unresolved https://github.com/iodide-project/pyodide/issues/677  At build I never saw it.

> so you cannot build your package with this argument (SIDE_MODULE=1 is used)

The current setup should work, the build happens successfully (inside Docker) each time there is a PR or a commit to master. I don't think you would need to change anything in the setup to make it work. However I agree that more investigation of how to deal with the `resolveSymbol` error would be useful in any case.

Are you sure there are no temporary files from previous builds (which would explain versions mismatch)? You could try `make clean-all` first.

**Comment by JaktensTid** [comment]
>It should be noted that we currently use emscripten from >1 year ago (#476) so the documentation currently on the emscripten website might not fully reflect the version we are using.
I checked - this flag was included a long time ago. You can use it even in 1.38.30

>At runtime
Yes, at runtime

Could you help me a little bit? Still cannot make my package work. Looks like I am missing something simple
Assuming I have a python package that depends on C library

- I am downloading library sources
- Executing ./configure, make, make install, everything as usual
- Package's code is linking this library, so I am executing pyodide mkpkg with ldflags as '-L/usr/local/lib -llib_name'
- Everything builds correctly, but there are some warnings and in the result when I am running everything in browser it writes me this resolveSymbol error (which is related to dynamic linking)

Maybe I don't understand something? Can we link /usr/local/lib library that was built with normal compilers (not emcc) at all?
Stucked with it for 3 days already

**Comment by rth** [comment]
> Maybe I don't understand something? Can we link /usr/local/lib library that was built with normal compilers (not emcc) at all?

Aww, yes, that won't work. You can only link objects compiled with emsdk, not system libraries compiled for x86_64 architectures.

For instance see how it's done for [lxml](https://github.com/iodide-project/pyodide/blob/49dc822acb83b276ecfac50470324db53c9c28de/packages/lxml/meta.yaml). There we need to link lxml and zlib libraries. Which in turns means [we have compile them with emsdk](https://github.com/iodide-project/pyodide/blob/49dc822acb83b276ecfac50470324db53c9c28de/packages/zlib/Makefile#L35), using something like,
```
emconfigure ./configure ...
emmake make ...
```
(in a separate Makefile).

> If I am executing it without linking to /usr/local/lib in ldflags where my third-party c library resides it shows me error like 'cannot find library_name.h'.

I meant that that master version without changes should build fine. If you are additionally building your C library, then you may have to make changes, but I would think compilation setup specific to that library should be enough.

Have a look at how it's done in `packages/` where typically folders with  `meta.yaml` are python packages, while folders with Makefiles are C libraries.

We do need to improve documentation to make it easier to find this information..

**Comment by JaktensTid** [comment]
Thanks, I was able to built c library. But python package shows me errors anyway
./bin/pyodide buildpkg /src/packages/talib/meta.yaml --package_abi=1

`src/cpython/build/3.8.2/host/include/python3.8/pyport.h:726:2: error: "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
 ^
talib/_ta_lib.c:201:39: error: expression is not an integer constant expression
    enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
talib/_ta_lib.c:201:41: note: division by zero
    enum { __pyx_check_sizeof_voidp = 1 / (int)(SIZEOF_VOID_P == sizeof(void*)) };`

When I am adding -I/src/cpython/installs/python-3.8.2/include/python3.8 to cflags it works smoothly, but there are these warnings about .o files anyway, and runtime is not working. As I understand my library is not linking correctly (on this step I am not sure does it actually comes from third-party library or from some c code from the package, so see my modifications to setup.py below). 

I see that setup.py of package is probably trying to build .c files inside this package with gcc, so I changed setup.py to 
`os.environ["CC"]="emcc"
os.environ["CXX"]="em++"`

In this case there is another error while building

In file included from /src/cpython/build/3.8.2/host/include/python3.8/Python.h:11:
```
/usr/include/limits.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
#include <bits/libc-header-start.h>
```

**Comment by JaktensTid** [comment]
Ok, actually something happened! did make clean all 
Now the resolveSymbol error gone, but a new appeared)

`Uncaught (in promise) Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide.py", line 43, in eval_code
    exec(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 4, in <module>
  File "/lib/python3.8/site-packages/talib/__init__.py", line 52, in <module>
    from ._ta_lib import (
ImportError: dynamic module does not define module export function (PyInit__ta_lib)`
Suspecting that's because I am changing -I with python path to cflags, let me investigate this... Maybe something quick

**Comment by JaktensTid** [comment]
Hurray! It worked.

What I did - 
PYODIDE_PACKAGES="my_packages" make _inside packages folder_
previously I was trying to execute binary file manually.
Again - documentation does not mention, that you have to run it from packages folder...

**Comment by rth** [comment]
Congrats! Great that it worked. 

> PYODIDE_PACKAGES="my_packages" make inside packages folder
> previously I was trying to execute pyodide buildpkg manually.

Aww, yes. Running that even outside of the package folder should work, though indeed I forgot to mention, that in that case you also need to add a corresponding command to the main Makefile (e.g. [here](https://github.com/iodide-project/pyodide/blob/49dc822acb83b276ecfac50470324db53c9c28de/Makefile#L270)).

I'm going to close this issue, but don't hesitate making PRs to improve the documentation or open other issue if you run into any.
