### ISSUE TITLE
The worker example in the documentation is a bit hard to read/understand

### ISSUE THREAD

**Issue by cglacet** [iodide-project/pyodide#793]
I think the documentation should be improved on the worker example. The provided example also loads the packages several time which sounds a bit weird. I think it would be simpler to avoid callbacks and use async/await syntax (especially because this targets python users who already "all" know this syntax). 

Here are some suggestions.

## Running python tasks asynchronously

In this process we will have three parties involved: 

* The **consumer**s want to run some scripts outside the main thread so they don't block the main thread.
* The **service worker** is responsible for running scripts in its own thread separate thread.
* The **worker API** exposes a consumer-to-provider communication interface.

### Consumers

Here is an example of consumer that will exchange via the worker 
API `py-worker.js` to run the following python `script` using the provided `context`.

```js
import { asyncRun } from './py-worker';

const script = `
    import statistics
    from js import A_rank
    statistics.stdev(A_rank)
`;

const context = {
    A_rank: [0.8, 0.4, 1.2, 3.7, 2.6, 5.8],
}

async function main(){
    try {
        const {results, error} = await asyncRun(script, context);
        if (results) {
            console.log('pyodideWorker return results: ', results);
        } else if (error) {
            console.log('pyodideWorker error: ', error);
        }
    }
    catch (e){
        console.log(`Error in pyodideWorker at ${e.filename}, Line: ${e.lineno}, ${e.message}`)
    }
}

main();
```

**Note** that the context is important because the worker thread and the main thread cannot
share data directly (they need to exchange them via `messages`).

### Service worker

[Workers][worker API] are ... 

> A worker is an object created using a constructor (e.g. [Worker()][Worker constructor])  that runs a named JavaScript file — this file contains the code that will run in the worker thread; workers run in another global context that is different from the current window. This context is represented by either a DedicatedWorkerGlobalScope object (in the case of dedicated workers - workers that are utilized by a single script), or a SharedWorkerGlobalScope (in the case of shared workers - workers that are shared between multiple scripts).

In our case we use one only to execute some python code without interfering with rendering.

```js 
// I think using the **cdn** is more straightforward for newcomers like me, 
// more experienced people will now how to modify the script anyway.
self.languagePluginUrl = 'https://pyodide-cdn2.iodide.io/v0.15.0/full/';
importScripts('https://pyodide-cdn2.iodide.io/v0.15.0/full/pyodide.js');

let pythonLoading;
async function loadPythonPackages(){
    await languagePluginLoader;
    pythonLoading = self.pyodide.loadPackage(['numpy', 'pytz']);
}

var onmessage = async(event) => { 
    await languagePluginLoader;
    await pythonLoading;
    const {python, ...args} = event.data;
    for (const key of Object.keys(args)){
        self[key] = args[key];
    }
    try {
        self.postMessage({
            results: await self.pyodide.runPythonAsync(python)
        });
    }
    catch (error){
        self.postMessage(
            {error : error.message}
        );
    }
}
```

### The worker API

Now that we established what the two sides need, lets connect them using this simple API (`py-worker.js`):

```js
const pyodideWorker = new Worker('./build/worker.js')

export function run(script, context, onSuccess, onError){ 
    pyodideWorker.onerror = onError;
    pyodideWorker.onmessage = (e) => onSuccess(e.data);
    pyodideWorker.postMessage({
        ...context,
        python: script,
    });
}

// Transform the run (callback) form to a more modern async form:
export function asyncRun(script, context) {
    return new Promise(function(onSuccess, onError) {
        run(script, context, onSuccess, onError);
    });
}
```

[worker API]: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API
[Worker constructor]: https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker

**Comment by cglacet** [comment]
I think this could be greatly improved as this is still a bit long for such a simple thing, but I hope its clear at least :)

**Comment by rth** [comment]
@cglacet Yes, the documentation can absolutely be improved! Thank you for suggesting it. Would you be interested in making a PR with your suggestions to `docs/using_pyodide_from_webworker.md` ?

**Comment by cglacet** [comment]
Sure thing, here is a [first draft](https://github.com/iodide-project/pyodide/pull/798).
