### ISSUE TITLE
getting memory access out of bounds

### ISSUE THREAD

**Issue by preetiverma525** [iodide-project/pyodide#794]
I am using only cousine similarity module of machine learning

![image](https://user-images.githubusercontent.com/59359938/98512738-cae98700-228c-11eb-8c62-9eecbcef7286.png)

**Comment by rth** [comment]
Yes, it's a know issue likely due to scipy.

Closing as a duplicate of https://github.com/iodide-project/pyodide/issues/729, let's continue this discussion there.
