### ISSUE TITLE
Importing scikit-learn or sklearn gives error 

### ISSUE THREAD

**Issue by rishik26** [iodide-project/pyodide#799]
![Screenshot from 2020-11-12 11-24-09](https://user-images.githubusercontent.com/25416841/98901318-9c142080-24d9-11eb-9ede-0c20096dbd1f.png)

ive tried sklearn too

**Comment by gzuidhof** [comment]
I was not able to reproduce it, can you try this?

![image](https://user-images.githubusercontent.com/1039510/98993429-5af62d80-2526-11eb-819f-b759e1d0fb48.png)

**Comment by rth** [comment]
Yes, the import name was incorrect. Thanks!
