### ISSUE TITLE
Separate CI and build Docker images

### ISSUE THREAD

**Issue by dalcde** [iodide-project/pyodide#810]
It appears that the Docker image is intended for use by CI, but happens to be useful for developers compiling locally, and a lot of the setup is not useful for compilation, e.g. firefox and chrome. It would be helpful to have a simpler (and smaller!) Docker image that one can use for compiling.

**Comment by rth** [comment]
Thanks for the suggestion. I would be in favor of moving the  `xvfb` from Docker to the CI setup, and if possible use a plain Debian image instead of `circleci/python` which would likely reduce the image size.

As to including chrome and firefox, even if you build packages outside of CI it's strongly recommended to run some tests, at least to check that the package is importable, which requires selenium and a browser. So I would rather keep them inside the image at the cost of a small increase in size (they are <100MB each, compressed).

**Comment by dalcde** [comment]
Do the CircleCI images do anything Circle(CI) specific? A cursory look at the docs suggest not.

I could also look into the using an alpine base image, though we might end up installing most of the debian packages anyway.

**Comment by dalcde** [comment]
I think starting with a debian base image could reduce the final image from 2.23 GB to 1.33GB, but I might be missing some packages.

**Comment by rth** [comment]
> Do the CircleCI images do anything Circle(CI) specific? A cursory look at the docs suggest not.

Not as far as I'm aware. We mostly used it for convenience looking at https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/python/images/3.8.2/Dockerfile there is indeed quite a few things that we wouldn't need.

> I could also look into the using an alpine base image,

I would prefer to keep debian based images, I'm not too familiar with alpine, and when we get some obscure error it's easier to debug with more mainstream distributions. IMO that's worth the extra couple 100MB.

**Comment by dalcde** [comment]
Here is something I put together for a debian-based docker file:
```Dockerfile
FROM debian:buster

RUN apt-get update \
                  # python packages
  && apt-get install -y --no-install-recommends python3 python3-pip python3-setuptools python3-wheel \
                  # testing packages: libgconf-2-4 is necessary for running chrome
                  wget unzip libgconf-2-4 chromium firefox-esr \
                  # building packages
                  node-less cmake make g++-8 gcc-8 libc6-dev pkg-config clang-format-6.0 \
                  uglifyjs ccache libncurses6 gfortran f2c swig libtinfo5 \
  && rm -rf /var/lib/apt/lists/* \
  && test "Comment: Hardcode nodejs path for uglifyjs, so it doesn't conflict with emcc's nodejs" \
  && test $(which node) = /usr/bin/node && test $(which uglifyjs) = /usr/bin/uglifyjs \
  && echo '#!/bin/sh -e\nexec /usr/bin/node /usr/bin/uglifyjs "$@"' >/tmp/uglifyjs \
  && chmod a+x /tmp/uglifyjs && mv -t /usr/local/bin /tmp/uglifyjs

RUN pip3 --no-cache-dir install pytest pytest-xdist pytest-instafail pytest-rerunfailures selenium PyYAML flake8

# Get recent version of geckodriver
RUN wget -qO- https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz | tar zxC /usr/local/bin/

# Get recent version of chromedriver
RUN wget --quiet https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip \
  && unzip chromedriver_linux64.zip \
  && mv $PWD/chromedriver /usr/local/bin \
  && rm -f chromedriver_linux64.zip

CMD ["/bin/sh"]
WORKDIR /src
```
Changes made:
 - Use debian as the base image, and install python via apt
 - Install firefox via apt --- the version in the repositories is newer than what we manually insalled
 - Removed the entrypoint business; you expressed interest in moving it back to circle.yml
 - Minor scripting tweaks

This reduces the final image size by almost 1GB. Further, in practice, it appears to take much less disk space after pulling, possibly due to there being fewer layers.
