### ISSUE TITLE
firefox-lxml test fails consistently

### ISSUE THREAD

**Issue by dalcde** [iodide-project/pyodide#825]
This appears to happen after https://github.com/iodide-project/pyodide/commit/bd7d397a8c46eaad14f46205b3c55616a46b4356 is merged, but from what I can tell, the commit doesn't actually change how pyodide builds its packages.

**Comment by rth** [comment]
No, it's still non deterministic as for instance first two commits on master on Dec 6, 2020 (after https://github.com/iodide-project/pyodide/commit/bd7d397a8c46eaad14f46205b3c55616a46b4356 was merged) passed fine for Firefox. Though yes, sometimes it will fail many times in a row.
