### ISSUE TITLE
Release v0.16.0

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#831]
I think we could make the v0.16.0 release  in the next few days.

Remaining thing that we would need to merge IMO are,
 - [x] Smaller docker image (https://github.com/iodide-project/pyodide/pull/815)
 - [x] make sure `console.html` downloads packages from jsdelivr when deployed inside CI (https://github.com/iodide-project/pyodide/pull/855)
 - [ ] update packages to avoid warnings with Python 3.8 (https://github.com/iodide-project/pyodide/issues/877)
 - [x] update release notes (https://github.com/iodide-project/pyodide/pull/813)

Please comment if you think something else should be included as well.

**Comment by dalcde** [comment]
I would be interested in streamlining the process of building
third-party C-based libraries for pyodide. I believe this involves
publishing our patched `wasm-opt` binary and python headers, as well as
some helper scripts to glue things together.

**Comment by rth** [comment]
> I believe this involves
publishing our patched `wasm-opt` binary and python headers, as well as
some helper scripts to glue things together.

A pre-built docker image https://github.com/iodide-project/pyodide/issues/656 wouldn't be sufficient for that use case?

**Comment by dalcde** [comment]
A pre-built docker image contains much more than that, and in particular
is much larger.

**Comment by rth** [comment]
Responded in more detail in https://github.com/iodide-project/pyodide/issues/814

We can certainly wait a bit more, but I think there have been a lot of changes since the last release in May and we should make a release soon. There is nothing that prevents us of doing another release not too long after if need be.

**Comment by rth** [comment]
The plan for now is to make a release tomorrow evening. I'll take a week off from contributing after that.

**Comment by ehfd** [comment]
@rth could you enable discussions in the repository?

**Comment by rth** [comment]
@ehfd I have experimentally enabled Github Discussions. Let's see if it could help discussion with the community. For me the separation between Github Issues, Discussion posts and StackOverflow questions is still not very clear in the case of pyodide.
