### ISSUE TITLE
emsdk make fails on return of subprocess.check_output

### ISSUE THREAD

**Issue by rngadam** [iodide-project/pyodide#84]
macOS X High Sierra 10.13.5

```
cd emsdk
make
git clone https://github.com/juj/emsdk.git
Cloning into 'emsdk'...
[...]
Traceback (most recent call last):
  File "./emsdk", line 789, in xcode_sdk_version
    return subprocess.check_output(['xcrun', '--show-sdk-version']).strip().split('.')
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./emsdk", line 2349, in <module>
    sys.exit(main())
  File "./emsdk", line 2332, in main
    success = tool.install()
  File "./emsdk", line 1336, in install
    success = tool.install()
  File "./emsdk", line 1346, in install
    success = build_llvm_tool(self)
  File "./emsdk", line 842, in build_llvm_tool
    if OSX and (not os.environ.get('LLVM_CMAKE_ARGS') or not 'HAVE_FUTIMENS' in os.environ.get('LLVM_CMAKE_ARGS')) and xcode_sdk_version() < [10,13]:
  File "./emsdk", line 791, in xcode_sdk_version
    return subprocess.checkplatform.mac_ver()[0].split('.')
AttributeError: module 'subprocess' has no attribute 'checkplatform'
```

## problem?

```
> python
Python 3.6.3 (default, Dec  2 2017, 14:57:51) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)] on darwin
>>> subprocess.check_output(['xcrun', '--show-sdk-version'])
b'10.13\n'
>>> subprocess.check_output(['xcrun', '--show-sdk-version']).strip().split('.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'str'
```

## fix?

workaround would be to conditionally ```decode('ascii')```? 

```
subprocess.check_output(['xcrun', '--show-sdk-version']).strip().decode('ascii').split('.')
['10', '13']
```

**Comment by mdboom** [comment]
Looks like a bug in `emsdk`.  (And it's OSX-specific, so I haven't run into it).  Maybe file an issue/PR here?  juj/emsdk

In the meantime, we could probably create a patch to fix the problem, but we should also submit upstream.

**Comment by mdboom** [comment]
This also looks like potentially a Python 2 vs. 3 problem.  What's your default python on your path?

You could try replacing the lines in pyodide's `emsdk/Makefile` that call `./emsdk` with `python2 emsdk` to see if that helps.

**Comment by mdboom** [comment]
It looks like `emsdk` is supposed to support both Python 2 and 3 (there's some if statements near the top of the file), but it's definitely broken for Python 3 here -- I assume the test coverage isn't great here, especially since emscripten is Python 2 only.  This looks like a bug in `emsdk` that probably should be reported there.

In the meantime, we might be able to work around this by changing all occurrences of `./emsdk` to `python2 emsdk` in `emsdk/Makefile`.  Would you mind trying that and seeing if it works for you?  You'll need to have *some* `python2` on your `PATH` for that to work, but you'll need it further down the line when calling into `emscripten` anyway.

**Comment by rth** [comment]
Wouldn't manually editing `emsdk/emsdk/emsdk` to convert bytes to str in the output of `check_output`, as suggested in the original post, be an easier temporary workaround?

Generally this was introduced in https://github.com/juj/emsdk/commit/f3ac553081e6b717afaa96632a87ecdc22cd4b92 and besides this issue, `subprocess.checkplatform` does not exist in Python 2 nor 3 as far as I can tell. We should definitely open an issue at `emsdk` about it..

**Comment by rth** [comment]
Closing as resolved in https://github.com/emscripten-core/emsdk/pull/327
