### ISSUE TITLE
libtinfo5 is missing from pre-built docker image

### ISSUE THREAD

**Issue by Stvad** [iodide-project/pyodide#853]
Hi there, I'm trying to add a packages (orjson and anki ) to pyodide using the pre-built docker image.  
I run mkpgk and then tried to do `make` (I'm not entirely sure from https://pyodide.readthedocs.io/en/latest/new_packages.html but I operate under a guess that this should result in a js file that would include the new package?)  
When I run make I see the following error:
`clang++: error while loading shared libraries: libtinfo.so.5: cannot open shared object file`  

Manually installing the library seems to have helped (`sudo apt update && sudo apt install -y libtinfo5`)

**Comment by dalcde** [comment]
This is fixed in the build docker image. I suppose the pre-built one has
to be updated too.

**Comment by dalcde** [comment]
I should add that I don't think Rust-based python libraries work with pyodide, but it's definitely something I would be interested in (that is, I need it for my use case). I think that will wait until we upgrade to a modern emscripten toolchain backed by llvm.

**Comment by Stvad** [comment]
I see, thanks for the heads-up!
