### ISSUE TITLE
Better linking with ports static libraries in packages

### ISSUE THREAD

**Issue by nopid** [iodide-project/pyodide#864]
Both packages matplotlib and pillow rely on `ldflags` to link with `.bc` static libraries from ports. 
https://github.com/iodide-project/pyodide/blob/3a06f5dfcb9b536e9ece1f68f6963717acf82486/packages/matplotlib/meta.yaml#L25-L27
https://github.com/iodide-project/pyodide/blob/3a06f5dfcb9b536e9ece1f68f6963717acf82486/packages/pillow/meta.yaml#L14-L16

The pillow package use several ports, some of them provide `.a` static libraries that are linked by `setup.py` using `-lpackage` and searched using `-L paths`. This mechanism cannot be used for `.bc` static libraries.

I opened an issue upstream https://github.com/emscripten-core/emscripten/issues/13044 to discuss this.

It remains unclear to me if this is the proper way to handle ports. Shouldn't `-s USE_JPEG=1`  be enough for proper linking? If so, how should package insert it properly into `Extension`?

**Comment by nopid** [comment]
It turns out emscripten moved away from `.bc` libraries since e81d3bb2dc93f7014ca6496966fb12d479f5fc53 to use `.a` libraries for static libraries. Everything is ok upstream.

**Comment by rth** [comment]
But then https://github.com/emscripten-core/emscripten/commit/e81d3bb2dc93f7014ca6496966fb12d479f5fc53 is included since emscripten 1.38.29 while we use 1.38.41, so the question remains why we are still getting those .bc files when using ports? Unless there are .a files in some other emscripten cache folder?

**Comment by nopid** [comment]
The settings are set to WASM_BACKEND=0 and WASM_OBJECT_FILES=1 in settings.js according to
https://github.com/emscripten-core/emscripten/blob/33c9d38d0dd4c27778e9f09428276fb5b0554263/src/settings.js#L1066-L1075

(this is the exact same file we get Inside emsdk/emsdk/fastcomp/emscripten/src/settings.js in pyodide.)

Alas, `emcc.py` changes the WASM_OBJECT_FILES flag here:
https://github.com/emscripten-core/emscripten/blob/33c9d38d0dd4c27778e9f09428276fb5b0554263/emcc.py#L1088-L1091

**Comment by rth** [comment]
Thanks for investigating. Then `WASM_BACKEND=1` (and in turn `WASM_OBJECT_FILES=1`)  is blocked by https://github.com/iodide-project/pyodide/issues/476 for now. So there isn't much we can do about this directly.

**Comment by nopid** [comment]
Makes sense, `.bc` seems to be the default also in emscripten before 2.0.

If needed, we could still recompile libjpeg and libpng as `.a` either by having our own copy or by patching the recipes of the ports.

**Comment by rth** [comment]
I believe this was resolved by https://github.com/iodide-project/pyodide/pull/1102
