### ISSUE TITLE
Allow Micropip to download from relative urls

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#867]
I think to allow relative urls, we'd only need to change the check here:

https://github.com/iodide-project/pyodide/blob/3a06f5dfcb9b536e9ece1f68f6963717acf82486/packages/micropip/micropip/micropip.py#L201

to `if "/" in requirement` or `if requirement.endswith(".whl")`.

Also, the documentation of `micropip.install` is a bit lacking. It'd be good to add an explanation of how `micropip` decides what a url is.
But for instance, it could be helpful to indicate the case where `url` is `"some_package-vers-py3-none-any.whl"`: does this expect a file `some_package-vers-py3-none-any.whl` to be in the current directory?

Would be good to mention that all wheels need to be named according to pep 427 too.
https://www.python.org/dev/peps/pep-0427/#file-name-convention

**Comment by rth** [comment]
> change the check here: [...] to `if requirement.endswith(".whl")`

+1 for this. Would you like to make a PR (and improve documentation) ? :)

There are currently two places for micropip documentation,
 - the [user manual](https://pyodide.readthedocs.io/en/latest/loading_packages.html#micropip)
 - the [docstring](https://pyodide.readthedocs.io/en/latest/micropip-api/micropip.install.html#micropip.install)

and it would be good to cross link them better. With typically a short description in the docstring (but still more extensive than what we have now) linking to the user manual for more details.

**Comment by hoodmane** [comment]
Yeah I'll do that. I've been planning to make some PRs to improve the docs but I keep being struck by laziness.
