### ISSUE TITLE
window.addEventListener not working

### ISSUE THREAD

**Issue by mdamien** [iodide-project/pyodide#885]
if I do:
```python
from js import addEventListener

addEventListener('hashchange', lambda *args: print('test'))
```
I get this error:

`TypeError: 'addEventListener' called on an object that does not implement interface EventTarget`

EDIT: When using jQuery, it works:

`jQuery(WINDOW).on('hashchange', lambda *args: print('test'))`

**Comment by casatir** [comment]
Try with

```python
from js import window

window.addEventListener('hashchange', lambda *args: print('test'))```

**Comment by mdamien** [comment]
Thanks
