### ISSUE TITLE
Add meta.yaml option to vendor packages in site-packages

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#895]
Right now we have Python packages that have a `meta.yaml` and are built with the python build system. And some Python packages that built [using Makefiles and are vendored into `site-packages`](https://github.com/iodide-project/pyodide/blob/4e976df8973975b32f9f1488e28830553f45ec60/Makefile#L184) of the core pyodide package (currently six.py, jedi, parso, pyodide.py).

It would be good to standardize this approach and built everything with the python build system, with some `meta.yaml` flag to indicate that a package should be vendored (e.g. `vendor_core = True`). This should then be reflected in the `packages.json` , that e.g. `jedi` does have a dependency on `parso` but that it doesn't need to be loaded, since it's already included in `site-packages.` For this second part we would likely need to address https://github.com/iodide-project/pyodide/issues/791 first.

This also could mean that `pyodide-py` could be a regular python package under `packages/` but that is vendored with Cpython.

Related to https://github.com/iodide-project/pyodide/issues/713

**Comment by dalcde** [comment]
I think a more reasonable approach would be to not vendor *any* package, c.f. #1010 and #987 (apart from pyodide-py)

**Comment by hoodmane** [comment]
I would say that we should vendor `pyodide-interrupts`, but I think we should actually add it to core.

**Comment by rth** [comment]
> I think a more reasonable approach would be to not vendor any package, c.f. #1010 and #987 (apart from pyodide-py)

Agreed. 

> I think we should actually add it to core.

We could assuming it's stable enough.
