### ISSUE TITLE
Create a pyodide Python package

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#896]
We now probably have enough custom Python code that needs to be used in WASM VM to put it into a single python package. Namely,
 - src/pyodide.py
 - src/webworker.py
 - the REPL helper classes (private) from https://github.com/iodide-project/pyodide/pull/875
 - likely a web loop from https://github.com/iodide-project/pyodide/pull/880

So we could maybe make a `pyodide-py` package (imported as `pyodide`), by analogy with the pyodide-js library https://github.com/iodide-project/pyodide/pull/792.

I'm not sure where to put it though,
 - in `packages/pyodide-py/pyodide/` to prepare https://github.com/iodide-project/pyodide/issues/895 and to indicate that it's not different from any other package. For contributors it might be a bit harder to find though.
 - keep it under `src/pyodide-py/pyodide/` as we are doing now, but that would mean to continue handling it differently from other packages in the Makefile.

I'm also wondering if we should move micropip as `pyodide.pip` at some later time, but the issue there is its dependency on distlib.

WDYT?

**Comment by casatir** [comment]
Thank you @rth to think about it.

(Think there is a typo in your post: `python-py` should be `pyodide-py`)

First approach seems much more confusing to me. From the user side, it's a module like others but from the dev side it's not.

The way I see it is: put external (built) packages in `packages/` and internal in `src/pyodide-py/`. This is in favor of your `pyodide.pip` which is a great idea.

I will have a look at `distlib` dependency in `micropip`. I now that some parts can be replaced using `distutils`.

**Comment by casatir** [comment]
Not sure about the fact that the REPL part should be private. It may be useful for users.

**Comment by hoodmane** [comment]
I think we should add some new apis to make it easier to implement repls. Particularly in the case when pyodide is running in a worker, it is currently necessary to write a lot of code to make things work smoothly.

**Comment by rth** [comment]
Thanks for the feedback!

OK, let's keep it in `src/pyodide-py` then. 

About new API to implement REPLs, sure if there is consensus on how they should look we can certainly make it public. My point was that from the moment we make it public we have to care about backward compatibility to avoid breaking users code. So for something like https://github.com/iodide-project/pyodide/pull/875 I would still keep it private, and then have a more detailed discussion on what that API should look like. Don't hesitate to open an issue about it BTW.

**Comment by hoodmane** [comment]
That sounds very reasonable. I have some fairly specific ideas about what an API could look like since I already implemented something that works pretty well on my downstream project. I'll open an issue with a detailed proposal about this.
