### ISSUE TITLE
Funny bug

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#922]
In a fresh copy of `console.html`:
```python
>>> pyodide.version()
0.15.0
>>> pyodide.version()
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 65, in eval_code
    return eval(compile(expr, "<eval>", mode="eval"), ns, ns)
  File "<eval>", line 1, in <module>
AttributeError: module 'pyodide' has no attribute 'version'
```
Hilarious. 

Not sure the best way to deal with `jspyodide` vs `pypyodide` for naming purposes.

**Comment by rth** [comment]
Yes, that's certainly confusing,
```
>>> pyodide
[object Object]
>>> pyodide.version()
0.15.0
>>> pyodide
<module 'pyodide' from '/lib/python3.8/site-packages/pyodide/__init__.py'>
```

> Not sure the best way to deal with jspyodide vs pypyodide for naming purposes.

If we change one or both names, that would also break backward compatibility, wouldn't it? For the package names so far we went with `pyodide-js` and `pyodide-py` but I'm not sure about imports. 

This is only an issue with REPL isn't it, maybe we can just makes sure the JS module is not accessible in the Python REPL?

**Comment by hoodmane** [comment]
Yeah somewhere in the C code it sets `globals["pyodide"] = Module`. This is probably a bad decision.

**Comment by dalcde** [comment]
Do you want to open an issue for the underlying problem?

**Comment by hoodmane** [comment]
Sounds like a good idea.

**Comment by hoodmane** [comment]
Oh I already did that: #1000.
