### ISSUE TITLE
Port zarr-python package

### ISSUE THREAD

**Issue by oeway** [iodide-project/pyodide#924]
> Zarr is a format for the storage of chunked, compressed, N-dimensional arrays. 

[Zarr](https://github.com/zarr-developers/zarr-python) has relatively clean dependency tree:
```
dependencies = [
    'asciitree',
    'numpy>=1.7',
    'fasteners',
    'numcodecs>=0.6.4',
]
```
Basically, we only need to figure out how to port [numcodecs](https://github.com/zarr-developers/numcodecs) and the rest are pure python packages (except numpy).

As a reference, numcodecs has already been ported to wasm as a [npm package](https://github.com/manzt/numcodecs.js) by @manzt, this is a [build script](https://github.com/manzt/numcodecs.js/blob/main/codecs/blosc/build.sh) which might be helpful for us.

Also see here: https://github.com/zarr-developers/community/issues/14

**Comment by manzt** [comment]
Just for reference, the numcodecs port is pretty incomplete. But I actually was able to add zstd and lz4 codecs today.
