### ISSUE TITLE
Deprecate pyimport?

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#926]
The docs say that `globals` is a "more convenient alternative to `pyimport`" suggesting `pyodide.globals.foo` instead of `pyodide.pyimport("foo")`. This raises the question: can we deprecate `pyimport`? What purpose does it serve? If there is a purpose to `pyimport` we should document it, if not we should deprecate it in favor of `globals`.

**Comment by hoodmane** [comment]
Maybe the point of `pyimport` is that it raises an error when the key is missing rather than returning `undefined`?

**Comment by rth** [comment]
yes, I'm not sure in JS but in Python `pyodide.pyimport("foo")` would certainly be considered a better API than `pyodide.globals.foo`. Also as you noted package name validation can be done more explicitly. It's mostly the same number of characters so I'm not sure why we recommend the latter.

**Comment by hoodmane** [comment]
As a user I think I'd prefer the api `pyodide.pyimport("foo")` to `pyodide.globals.foo`. The redundancy kind of bugs me from a design perspective, but it's not a big deal. I would say to instead deprecate `pyodide.globals` but I want it to be a public API so that the definition of `runPython` only involves public apis so people can define their own variants.

On the other hand, what about something like `pyodide.globals.get("foo")`? I guess `pyimport` is a more descriptive name.


In #923 I made `pyimport` into a trivial wrapper around `pyodide.globals` which should make it much easier to maintain.

**Comment by rth** [comment]
What bothers me a bit with `pyodide.pyimport('x')` is that we are not really importing that variable, but rather loading it from Python. So the "import" term is a bit confusing.  With `pyodide.globals` what's not clear to me is that we are talking about Python globals not JS globals.

**Comment by hoodmane** [comment]
Exactly! So maybe come up with a third name, deprecate `pyimport` and tell people to use `globals` as an argument to `eval_code` and friends?

**Comment by hoodmane** [comment]
Okay on more thought, the further problem with `pyimport` is that it assumes that there will only be one namespace. The correct API should be a method on a `PyNamespace` object. So I think maybe we should deprecate `globals` and `pyimport` and make a new `pyodide.pynamespace` maybe with methods like `pyodide.pynamespace.get("blah")`, `pyodide.pynamespace.set("blah", 2)`.

Then if someone has a second namespace, it will implement the same methods.

**Comment by rth** [comment]
Coming back to this issue, I agree that `pyodide.globals.get("x")` is much preferable to `pyodide.pyimport` because,
 - it also has a setter
 - can indeed  apply to any namespace

So I'm +1 to deprecate it, pending removal one version from now (in 0.18.0), and remove it from the user guide examples for 0.17.0.
