### ISSUE TITLE
Page crashes when importing python library after a previous cell outputted a string

### ISSUE THREAD

**Issue by enymuss** [iodide-project/pyodide#93]
Page crashes when calling pyodide.loadPackage() after any previous cell, called after downloading python, outputted a string.

PS. Thank you for adding Iodide and Pyodide to work on Chrome

### What I Did

In the Matplotlib demo:
1) Run plugin cell to import python.
2) Create new py cell, with contents:
```
import sys
sys.version
```
3) Run cell to get string output.
4) Run js cell to import matplotlib.

In Matplotlib demo page, the page crashes straight away.
In Python demo page, get TypeError then crash after numpy.data has been downloaded.

### What I Expected

Expected the matplotlib library and dependencies to download.

### What Happened 

Chrome page crash. Get 'Aw, snap!' screen.

### (OPTIONAL) notebook that reproduces bug

Matplotlib Demo: https://iodide.io/pyodide-demo/matplotlib.html
Python Demo: https://iodide.io/iodide-examples/python.html

Error from Python Demo (might not be relevant as the .js file is from April):
TypeError: Cannot read property 'await' of undefined
    at Object.loadPackage (eval at xhrObj.addEventListener (https://iodide.io/dist/iodide.pyodide-20180420.js:12101:45), <anonymous>:66:31)
    at eval (eval at <anonymous> (https://iodide.io/dist/iodide.pyodide-20180420.js:11988:49), <anonymous>:1:9)
    at eval (<anonymous>)
    at https://iodide.io/dist/iodide.pyodide-20180420.js:11988:49
    at https://iodide.io/dist/iodide.pyodide-20180420.js:75578:18
    at dispatch (https://iodide.io/dist/iodide.pyodide-20180420.js:49465:18)
    at https://iodide.io/dist/iodide.pyodide-20180420.js:12144:20
    at Object.dispatch (https://iodide.io/dist/iodide.pyodide-20180420.js:75578:18)
    at Object.dispatcher.(anonymous function).params [as evaluateCell] (https://iodide.io/dist/iodide.pyodide-20180420.js:11263:95)
    at UserTask.callback (https://iodide.io/dist/iodide.pyodide-20180420.js:11285:16)

### Further Tests

Print statements that are ok (can import python library after running the cell):
```
import math
math.log(1024, 2)
```

```
import numpy as np
np.zeros((16, 16))
```

`1+2.5`, `[1, 2]`, `[]`, `{}`, `[0, 1, 32.0, b'bytes']`

Print statements which cause crash:
```
import sys
sys.version
```
```
import os
os.getcwd()
```
`['asd']`, `complex(1, 2)`, `()`, `True`

The not ok print statements do not have to be run straight before to cause crash.
Running cells in the following order after importing python:
`2+3`
`()`
`3+3`
`pyodide.loadPackage()`
also causes crash.

Example which will cause crash:
![example of setup to cause crash](https://user-images.githubusercontent.com/5191207/43252659-57e38902-90c3-11e8-8c87-9f5d4ff32b63.png)

Example of ok statements
![ok statments examples](https://user-images.githubusercontent.com/5191207/43252623-3e689c56-90c3-11e8-81ad-886e933974eb.png)

**Comment by mdboom** [comment]
Thanks for the detailed report.  It is definitely Chrome-specific.

**Comment by mdboom** [comment]
This was an interesting bug!

As far as I can tell, there is just a bug in Chrome that the `TextDecoder` interacts negatively with instantiating WebAssembly.

It is sufficient to reproduce the bug to just add a JS cell with:

```
x = new Uint8Array(pyodide.HEAPU8.buffer, 0, 4)
y = new TextDecoder('utf-8').decode(x)
y
```

then `loadPackage` will fail after that.  I should have a fix in a PR shortly.

**Comment by mdboom** [comment]
Chromium bug filed here: https://bugs.chromium.org/p/chromium/issues/detail?id=868404
