### ISSUE TITLE
CLAPACK.js is missing from the dev branch

### ISSUE THREAD

**Issue by oeway** [iodide-project/pyodide#930]
For some reason, I started to see the CLAPACK.js missing error when using pyodide from https://cdn.jsdelivr.net/pyodide/dev/full/:

```
Couldn't load package from URL https://cdn.jsdelivr.net/pyodide/dev/full/CLAPACK.js
```

**Comment by dalcde** [comment]
This is due to #927, because CLAPACK is now listed as a dependency of
scipy, despite the fact that it is already statically linked.

**Comment by rth** [comment]
It's interesting that tests didn't catch this.
