### ISSUE TITLE
Upgrade to 0.16.0. Packages can't be loaded.

### ISSUE THREAD

**Issue by leopsidom** [iodide-project/pyodide#944]
Getting 404 on the package URL, for instance, pandas package: https://cdn.jsdelivr.net/pyodide/v0.16.0/full/pandas.js. 

```
<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: v0.16.0/full/pandas.js</li>
<li>RequestId: BYBS5H4SEG3M9RET</li>
<li>HostId: mMpquzsUYgCLOZRm18BcUfcY9ic3FQGoiadwiFDIHVirJ3u8X9KFg3vAMw/dWbEMPKNIeOgWrJ4=</li>
</ul>
<hr/>
</body>
</html>
```

Wonder if this is the CDN issue ? Or something I missed.

It seems I can access package version under 0.15.0 though: https://cdn.jsdelivr.net/pyodide/v0.15.0/full/pandas.js

**Comment by dalcde** [comment]
We somehow have a broken CI pipeline, c.f. https://app.circleci.com/pipelines/github/iodide-project/pyodide/781/workflows/6d6e961f-cf9c-4f60-a775-355a249a2b6d

It didn't build packages before deploying. The config requires `test-packages-firefox`, though, so I don't see how this happened.

**Comment by dalcde** [comment]
This is due to the `build-packages` job not specifying `filters/tags/only: /.*/`.

**Comment by rth** [comment]
This should be now fixed with https://github.com/iodide-project/pyodide/pull/950 and the 0.16.1 release.
