### ISSUE TITLE
Upgrade to 0.16.0. Packages releases dont have all the package file

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [iodide-project/pyodide#949]
i dev a product that use pyodido in offline env.
so, all the data must provide from local/LAN.

the v0.15.0 is work well , but when i upgrade to v0.16.0, all the ext package lost.

you can see the release page

https://github.com/iodide-project/pyodide/releases

![2020-12-25 17_47_08-Releases · iodide-project_pyodide — Mozilla Firefox](https://user-images.githubusercontent.com/6566869/103130900-9cf3c100-46d9-11eb-90a3-1fd795db6feb.png)

v0.16.0 smaller than v0.15.0 , and it lost all the package file.

seems like something wrong ?
ref #944

**Comment by dalcde** [comment]
This is indeed #944. The issue in the build pipeline should be fixed in
master and we are waiting a release/rebuild.

**Comment by Lyoko-Jeremie** [comment]
thank you very much~~

**Comment by Lyoko-Jeremie** [comment]
i'm waiting the fix online ~ XD
