### ISSUE TITLE
Configurable "import js"

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#960]
Add a `pyodide.mountPackage("name", object)` api that mounts `object` at `name`, so that `import "name"` imports `object`, and `from name import field` imports `object.field` as `field`.

For example, the current `js` import would then be installed by saying `pyodide.mountPackage("js", globalThis)` though we would keep the current behavior as the default. We could get rid of `import js` by saying `pyodide.mountPackage("js", undefined)`.

**Comment by Lyoko-Jeremie** [comment]
sounds great.

BTW, have any way to bannd other import ? example about the `micropip` ?

Example, a bool config to enable or disable the `micropip` can or cannot be use ?

**Comment by hoodmane** [comment]
You can do that yourself by [using Emscripten FS](https://emscripten.org/docs/api_reference/Filesystem-API.html?highlight=fs#FS.unlink) to delete the `micropip` package. The filesystem is found either under `pyodide.FS` at start of load or under `pyodide._module.FS` once load is completed.

**Comment by Lyoko-Jeremie** [comment]
@hoodmane Oh, thank you~ 

is the `pyodide` package can be delete same as that ?

**Comment by dalcde** [comment]
`micropip` is a pure python package, so there isn't much point in "banning" it; users can simply re-implement it. Further, micropip is only useful for installing pure python packages, and again banning those won't do you much good either. Just by having python around you essentially have full access to the virtual filesystem to insert whatever you want, including compiled C code, by importing `os`.

Thus, I believe any sort of sandboxing along these lines ought to come from restricting along the JS-wasm boundary, and nothing within python itself.

**Comment by Lyoko-Jeremie** [comment]
`micropip is a pure python package, so there isn't much point in "banning" it;`

so, this means that i need bannd the HTTP api, not the package ?

so, where is the network API ?

**Comment by Lyoko-Jeremie** [comment]
> Thus, I believe any sort of sandboxing along these lines ought to come from restricting along the JS-wasm boundary, and nothing within python itself.

yes , you are right !!!

**Comment by dalcde** [comment]
>so, this means that i need bannd the HTTP api, not the package ?
>
>so, where is the network API ?
 
I believe we use XMLHTTPRequest imported from JavaScript

**Comment by Lyoko-Jeremie** [comment]
> I believe we use XMLHTTPRequest imported from JavaScript

so, how to disable it ? example, make a config to disable the import ?

**Comment by dalcde** [comment]
At the moment, we use XMLHTTPRequest via the js module, which currently allows arbitrary js execution. I think a reasonable approach would be to make our network requests use the emscripten fetch api, so that it can be used without the js module, then make the js module a configurable compile time option.

**Comment by Lyoko-Jeremie** [comment]
if use the `use the emscripten fetch api` , please let it become disable feature .

**Comment by hoodmane** [comment]
@dalcde I don't think it's necessary even to have the js module be a compile time option. Inside `pyodide.js` we can do `mountPackage("js", globalThis)` and then if you don't want that then you can edit `pyodide.js` to remove that. So you wouldn't have to build a separate wasm binary.

**Comment by dalcde** [comment]
I don't think this would work from a security perspective. The functions needed to enable to JS module are already imported into wasm. We need to disable it during compile time so that emscripten does not do the import. Again, users can re-insert the files into the emscripten virtual fs.

**Comment by hoodmane** [comment]
@dalcde I thought the point was that the wasm can call any javascript function it has a reference to, but if you don't ever give it a reference then it can't call it?

**Comment by dalcde** [comment]
That is true, but the "reference" is the literal string name of the imported function. When instantiating a wasm module, you supply an object consisting of imports the wasm module is allowed to access, and the wasm module uses the imports by referring to its name (see https://developer.mozilla.org/en-US/docs/WebAssembly/Understanding_the_text_format#Importing_functions_from_JavaScript )

Thus, any import we pass on to a wasm module will be usable, and the list of imports is determined by emscripten at compile time.

**Comment by oeway** [comment]
Have you checked [RistrictedPython](https://restrictedpython.readthedocs.io/en/latest/)? Its a pure python package and allows applying custom restrictions to the import function.

**Comment by Lyoko-Jeremie** [comment]
@oeway 

thanks for your notice ~

---

but you can read in there https://restrictedpython.readthedocs.io/en/latest/idea.html

> There should be additional preventive measures taken to ensure integrity of the application and the server itself, according to information security best practice and unrelated to RestrictedPython.

so, make a sandboxied runtime / limit avaiable import package are still nesssary. 

---

but the `RestrictedPython` seems like a good tools to help make a safe OJ runtime.

**Comment by oeway** [comment]
On Sun 27 Dec 2020 at 11:23, LyokoJeremie <notifications@github.com> wrote:

> @oeway <https://github.com/oeway>
>
> thanks for your notice ~
> ------------------------------
>
> but you can read in there
> https://restrictedpython.readthedocs.io/en/latest/idea.html
>
> There should be additional preventive measures taken to ensure integrity
> of the application and the server itself, according to information security
> best practice and unrelated to RestrictedPython.
>
> so, make a sandboxied runtime / limit avaiable import package are still
> nesssary.
>
Well, ensuring the integrity typically typically means you need to make
sure the python runtime , module or scripts are downloaded from
reliable source, with hash value verified etc., I don’t think they mean you
need additional sandbox mechanism.

RestrictedPython itself will do the sandboxing, if you read here:
https://restrictedpython.readthedocs.io/en/latest/usage/policy.html#implementing-a-policy
they let you implement your own import policy to limit packages.

**Comment by oeway** [comment]
If I understand correctly, the goal of this issue is to provide some restrictions on accessing js, if we lift the restriction already in pyodide (either in the JS-wasm boundary or through `mountPackage("js", globalThis)`), many packages patched via js won't work (e.g. a web loop for asyncio, or a http client module that calls js.fetch). 

In my opinion, using `RestrictedPython` to create a restricted environment inside Python with a set of custom policy is much more flexible.

**Comment by Lyoko-Jeremie** [comment]
> Well, ensuring the integrity typically means you need to make sure the python runtime , module or scripts are downloaded from reliable source, with hash value verified .

but the code maybe come from a untrusted user.

please see [this ](https://github.com/iodide-project/pyodide/issues/959#issuecomment-751421344) , and [this](https://github.com/iodide-project/pyodide/issues/959#issuecomment-751424230) and [this](https://github.com/iodide-project/pyodide/issues/959#issuecomment-751429757) .

---

Python is a dynamic language, and it can be patch everywhere, no one understand where will be the next sandbox escape vulnerability .

so i think the configurable `import` or a configurable runtime is need to build a great sandbox , make something configurable in the JS-wasm boundary is a best choose . 

and i think that , if we have `mountPackage("js", globalThis)` and `unmountPackage("js")` , between two `runPython` call, the `many packages patched via js won't work (e.g. a web loop for asyncio, or a http client module that calls js.fetch).` maybe not be a issue. also, the `RestrictedPython` still a necessary tools to make the seconed guard  wall .

**Comment by oeway** [comment]
> but the code maybe come from a untrusted user.

Yes, but you can run untrusted code within RestrictedPython, as it advertised **it helps to define a trusted environment and execute untrusted code inside of it**. In other words, you don't need to do anything within the python runtime, and unstrusted code can run directly within RestrictedPython. It is designed to run untrusted code on the server-side (e.g. with zope which is a web app server) in a native Python environment without additional protection.

> 
> please see [this ](https://github.com/iodide-project/pyodide/issues/959#issuecomment-751421344) , and [this](https://github.com/iodide-project/pyodide/issues/959#issuecomment-751424230) and [this](https://github.com/iodide-project/pyodide/issues/959#issuecomment-751429757) .

I try to read the thread, but I got confused as well, @dalcde thinks this might be useful when Pyodide is run in a server which totally make sense to me. And I think we can then use RestrictedPython, my feeling is a more thorough solution than trying to prevent importing js from pyodide itself.

However, it seems you are actually trying to run Pyodide on the client-side which I don't think any of these will work, as @hoodmane pointed out, an evil user can always open a browser console and run js code to remove any restrictions you applied. If you assume the user cannot access the browser console, then you can simply assume all the code can be executed by RestrictedPython where you can configure any import restrictions, including blacklist the js module and potentially much more, no?

>  i think that , if we have mountPackage("js", globalThis) and unmountPackage("js") , between two runPython call, the `many packages patched via js won't work (e.g. a web loop for asyncio, or a http client module that calls js.fetch). ` maybe not be a issue. also, the RestrictedPython still a necessary tools to make the seconed guard wall .

Unfortunately, many js patches will be applied during runtime, not all of them import everything when the package is loaded.

**Comment by hoodmane** [comment]
@oeway If you want to argue that it's impossible to do what @Lyoko-Jeremie is doing, can you please do it on the original thread #959?
I am now convinced that what @Lyoko-Jeremie is doing is code obfuscation, which is impossible in theory but possible in practice.

**Comment by hoodmane** [comment]
@oeway The reason I suggested this feature is because I think it is easy to implement (looking at jsimport.c it's a very small change) and it adds useful flexibility. In particular, I'm less interested in unmounting `js` as @Lyoko-Jeremie wants to do, and more interested in being able to set up several different javascript implemented "packages".

**Comment by hoodmane** [comment]
> Thus, any import we pass on to a wasm module will be usable, and the list of imports is determined by emscripten at compile time.

This is impossible. It is possible to pass a wasm function a js callback defined at runtime. The reference to the js callback is some sort of pointer. The compiler can't know at compile time what arguments it will be called with at runtime.

**Comment by oeway** [comment]
> @oeway If you want to argue that it's impossible to do what @Lyoko-Jeremie is doing, can you please do it on the original thread #959?

OK, It's indeed related to that, but I meant for proposing using RestrictedPython instead of switching to the fetch api of emscripten and apply the restrictions to the js-wasm interface. 

> The reason I suggested this feature is because I think it is easy to implement (looking at jsimport.c it's a very small change) and it adds useful flexibility. In particular, I'm less interested in unmounting js as @Lyoko-Jeremie wants to do, and more interested in being able to set up several different javascript implemented "packages".

I see, if that's easy enough, totally make sense to me. Bing able to mountPackage js packages are certainly interesting to me, I am actually thinking along that, for example importing tensorflow.js. For that I will need to also patch the python to js and js to python data type conversion though.

**Comment by hoodmane** [comment]
> proposing using RestrictedPython

Still seems like it's more on topic in the original thread.

> I will need to also patch the python to js and js to python data type conversion though.

This sounds interesting. I will open another issue to discuss this.

**Comment by dalcde** [comment]
>This is impossible. It is possible to pass a wasm function a js callback defined at runtime. The reference to the js callback is some sort of pointer. The compiler can't know at compile time what arguments it will be called with at runtime.

Fair point. You can add functions to the table at runtime. However, the wasm imports used by the js module lets you access javascript globals, hence window.eval. Thus, we already have full access to the javascript runtime before we add any new functions at runtime.

**Comment by Lyoko-Jeremie** [comment]
> for example importing tensorflow.js. For that I will need to also patch the python to js and js to python data type conversion though.

about this, i have a similar idea in my brain , the official Python version OpenCV seems like dependence the OpenCV binary runtime, try to port it into pyodide maybe wast many proof. but we have a [OpenCV.js](https://docs.opencv.org/3.4/d5/d10/tutorial_js_root.html) , and now it now on dev, you can setup it [follow this](https://docs.opencv.org/3.4/d0/d84/tutorial_js_usage.html) , or [download opencv.js from there](https://docs.opencv.org/3.4.0/opencv.js) .

so , we can simple make the Python version OpenCV running in Brower use OpenCV.js and a simple Python Wrapper .

**Comment by Lyoko-Jeremie** [comment]
> However, the wasm imports used by the js module lets you access javascript globals, hence window.eval. Thus, we already have full access to the javascript runtime before we add any new functions at runtime.

so we need a way to limit the `import js` or disable it like the topic title, right ?

**Comment by hoodmane** [comment]
I'm working on a PR for this.

**Comment by dalcde** [comment]
I think as a first step we could make disabling js disable network requests too. We can later re-enable it by hand, using the fetch API or otherwise

**Comment by hoodmane** [comment]
> make disabling js disable network requests too

Is disabling network requests a compile time thing? What I'm doing is entirely at runtime.

**Comment by dalcde** [comment]
network requests (specifically micropip) are done via the js module, so if the js module is gone that would break too

**Comment by Lyoko-Jeremie** [comment]
@oeway 

> Have you checked `RistrictedPython` ? Its a pure python package and allows applying custom restrictions to the import function.

now i try it, it always throw `__import__ not found` like follow, i guess that the pyodide have a custom __import__  impl that different from normal CPython , so the RistrictedPython patch not work as expected.

```
Traceback (most recent call last):
  File "<exec>", line 77, in importRestrictedPython
  File "code.RPY", line 42, in <module>
ImportError: __import__ not found
```

**Comment by Lyoko-Jeremie** [comment]
@hoodmane 

> You can do that yourself by using Emscripten FS to delete the micropip package from the dummy file system. The filesystem is found either under pyodide.FS at start of load or under pyodide._module.FS once load is completed.


Hi, i find it in the path `pyodide._module.FS.root.contents.lib.contents['python3.8'].contents['site-packages'].contents` , can i direct delete it use `FS.rmdir('/lib/python3.8/site-packages/xxxxx')` ?

**Comment by dalcde** [comment]
As a concrete example of my objection, I've added a JS2 package in my branch here: https://github.com/dalcde/pyodide/tree/js2 . It's source code is basically copied from `jsimport.c`, and it acts exactly the same as the existing `js`. If you build the branch, you can import `js2` and get the same functionality.

Now a python package is just a bunch of files in the virtual filesystem. Even if you hide the `js` package, a malicious user can still write the same bytes into the virtual fs using `open/write`, and now you have full javascript access. This will work as long as the relevant functions in hiwire and js2python exist and is compiled.

**Comment by dalcde** [comment]
That said, I'm still a fan of #972
