### ISSUE TITLE
Adjust makefile so that each .bc file depends on all .h files

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#969]
The file `some_name.bc` depends on the file `some_name.c` and also any header files it includes. Building the `.bc` files is really fast, so it's better to have a rule that rebuilds them more often than to wait for a linker or runtime error because a `.bc` file was built with out of date headers.

@dalcde Could you do this?

**Comment by dalcde** [comment]
Isn't building .bc all of the compilation work? I think they are the
equivalent of the .o files in our context.

But I suppose essentially all of src/*.c is fairly small; the slow part
is the final linking step with all the cpython source.

If you want to do this, I think you should replace line 164 with

%.bc: %.c $(CPYTHONLIB) $(wildcard src/**/*.h)

That said, surely this is a solved problem in the C world.

**Comment by hoodmane** [comment]
> But I suppose essentially all of src/*.c is fairly small; the slow part
is the final linking step with all the cpython source.

Yeah on my computer building all of `src/*.c` takes maybe 5-10 seconds, whereas the linking step is very inconsistent but I would say it takes 1-10 minutes.
