### ISSUE TITLE
Bug: JsProxy.__call__ calls the js function with an extra argument

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#974]
Javascript:
```javascript
window.a = function(){return arguments.length;}
a(1) // ==> 1
a(1,2,3) // ==> 3
```
Python:
```python
from js import a
a(1) # ==> 2
a(1,2,3) # ==> 4
```

**Comment by hoodmane** [comment]
Well the problem is [here](https://github.com/iodide-project/pyodide/blob/28d0dc2874da398d9b802f0c9d0eb94ae366ab84/src/type_conversion/jsproxy.c#L126):
```C
  if (PyDict_Size(kwargs)) {
    JsRef idkwargs = python2js(kwargs);
    hiwire_push_array(idargs, idkwargs);
    hiwire_decref(idkwargs);
  }
```
I'm not sure what the correct code should be, but this definitely isn't it. I think `kwargs` is allowed to be `NULL`. I think the most reasonable thing to do is to throw an error if a `JsProxy` is called with key word arguments?
@dalcde opinions?

**Comment by dalcde** [comment]
Sounds reasonable to me.

**Comment by hoodmane** [comment]
I will make up a PR for this then.

**Comment by hoodmane** [comment]
While I'm at it I can switch to using `VectorCall`.
