### ISSUE TITLE
Remove `pyodide.get_completions` and `pyodide.repr`

### ISSUE THREAD

**Issue by hoodmane** [iodide-project/pyodide#984]
`pyodide.get_completions` should be removed, it is a bad reexport of the Jedi API. A couple of days ago I think I was talking to someone who was confused by it. I also got confused when I tried to use `get_completions` and finally went to the Jedi docs and used Jedi directly. I don't understand what value `get_completions` adds compared to telling people that Jedi is available and suggesting they use it themselves. We could update the docs to prominently link to Jedi, though we should add a warning about the recursion errors #821.

`pyodide.repr` is also a bad API. It is not idiomatic javascript. We should get rid of it in favor of `PyProxy.toString()` or perhaps add `PyProxy.repr()`.

See also my other issues about public APIs #926 and #870.

**Comment by rth** [comment]
I think the motivation for `get_completion` was that different iodide language plugins needed to have this method to make competition work. +1 to remove it and make jeudi a regular package (i.e. remove it from the core pyodide package) which should reduce the initial download size by 1MB or so.

>  We should get rid of it in favor of PyProxy.toString() or perhaps add PyProxy.repr()

We could indeed.

We would need to think how to handle breaking changes. In the python world one would first deprecate and then remove in a version or two, but I'm not sure that would work for us. So maybe making the change, and make it very prominent in the change log (maybe with badges as in https://scikit-learn.org/stable/whats_new/v0.24.html) would be fine.

**Comment by dalcde** [comment]
>We would need to think how to handle breaking changes. In the python world one would first deprecate and then remove in a version or two, but I'm not sure that would work for us. So maybe making the change, and make it very prominent in the change log (maybe with badges as in https://scikit-learn.org/stable/whats_new/v0.24.html) would be fine.

 From the semver point of view, I would consider upgrading from 0.x._ to 0.y._ to be a "major" release (similar to 1._._ to 2._._). For python it's within the same major release, so they "shouldn't" remove anything at all.

**Comment by rth** [comment]
> From the semver point of view, I would consider upgrading from 0.x._ to 0.y._ to be a "major" release

Yes, I know, but few scientific python packages actually follow semver. For instance in numpy, pandas, matplorlib, rather use rolling deprecation approach see [NEP 23](https://github.com/numpy/numpy/pull/18097) and will have breaking changes between 1.1 and 1.5 after a deprecation cycle. It's true that say Rust ecosystem is much better in that respect, but they also have much smaller packages. In our case, each 0.x release is indeed a "major" release semver wise and I think that's fine, but it would still be good to clearly indicate breaking changes in the changelog.

More thoughts about it in https://github.com/iodide-project/pyodide/issues/988

**Comment by hoodmane** [comment]
Closed by #1066 and #1067.
