### ISSUE TITLE
Create a Python package out of common functions in tools

### ISSUE THREAD

**Issue by rth** [iodide-project/pyodide#99]
Currently scripts under `tools/` define a few common functions. Testing these (or generally using them in tests) currently requires some sys.path manipulation. Would be worth putting them into a standalone python package (e.g. `pyodide_build`) ?

**Comment by mdboom** [comment]
Yes.  Also, I think we'll want to grow some command line utilities for:

- Converting a local or remote Python package into a Pyodide package
- Converting a conda-forge `meta.yaml` into a Pyodide `meta.yaml`
- Building packages outside of the main tree.

For the main pyodide build (what `make` does), it should continue to use the local copy of the tools in the git repo.  a) the user shouldn't be required to install the pyodide build tools if they are just building pyodide and, b) there's the potential for problems/confusion if the installed and local versions don't match.

**Comment by rth** [comment]
Closing as resolved with the `pyodide_build/` folder.
